- mysql_qcache_inserts:
    title: "查询缓存插入个数"
    metric_names: "mysql"
    type: "mysql_remove"
    order: 7
    defines:
      diff.qcache_inserts:
        label: ""
        unit: ""
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
    parameters:

