- mysql_innodb_buffer_pool_pages_total:
    title: "InnoDB缓冲池的页面总数"
    metric_names: "mysql"
    type: "mysql_remove"
    order: 15
    defines:
      avg.innodb_buffer_pool_pages_total:
        label: ""
        unit: ""
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
    parameters:

