- mysql_innodb_buffer_pool_reads:
    title: "InnoDB缓冲池读从磁盘读页面的次数"
    metric_names: "mysql"
    type: "mysql_remove"
    order: 18
    defines:
      diff.innodb_buffer_pool_reads:
        label: ""
        unit: ""
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
    parameters:

