- mysql_commands_insert_select:
    title: "选择插入语句的个数"
    metric_names: "mysql"
    type: "mysql_remove"
    order: 27
    defines:
      diff.commands_insert_select:
        label: ""
        unit: ""
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
    parameters:

