- gateway_connection:
    title: "连接数"
    metric_names: "application_http"
    type: "gateway"
    order: 0
    defines:
      max.total_conns_max:
        label: "峰值连接数"
        unit: ""
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
      avg.active_conns_mean:
        label: "平均连接数"
        unit: ""
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
      avg.idle_conns_mean:
        label: "平均连接数"
        unit: ""
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
      avg.total_conns_mean:
        label: "平均连接数"
        unit: ""
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
      max.active_conns_max:
        label: "峰值连接数"
        unit: ""
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
      max.idle_conns_max:
        label: "峰值连接数"
        unit: ""
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
    parameters:

