// Code generated by protoc-gen-go-register. DO NOT EDIT.
// Sources: notify.proto

package pb

import (
	transport "github.com/erda-project/erda-infra/pkg/transport"
	reflect "reflect"
)

// RegisterNotifyServiceImp notify.proto
func RegisterNotifyServiceImp(regester transport.Register, srv NotifyServiceServer, opts ...transport.ServiceOption) {
	_ops := transport.DefaultServiceOptions()
	for _, op := range opts {
		op(_ops)
	}
	RegisterNotifyServiceHandler(regester, NotifyServiceHandler(srv), _ops.HTTP...)
	RegisterNotifyServiceServer(regester, srv, _ops.GRPC...)
}

// ServiceNames return all service names
func ServiceNames(svr ...string) []string {
	return append(svr,
		"erda.core.services.notify.NotifyService",
	)
}

var (
	notifyServiceClientType  = reflect.TypeOf((*NotifyServiceClient)(nil)).Elem()
	notifyServiceServerType  = reflect.TypeOf((*NotifyServiceServer)(nil)).Elem()
	notifyServiceHandlerType = reflect.TypeOf((*NotifyServiceHandler)(nil)).Elem()
)

// NotifyServiceClientType .
func NotifyServiceClientType() reflect.Type { return notifyServiceClientType }

// NotifyServiceServerType .
func NotifyServiceServerType() reflect.Type { return notifyServiceServerType }

// NotifyServiceHandlerType .
func NotifyServiceHandlerType() reflect.Type { return notifyServiceHandlerType }

func Types() []reflect.Type {
	return []reflect.Type{
		// client types
		notifyServiceClientType,
		// server types
		notifyServiceServerType,
		// handler types
		notifyServiceHandlerType,
	}
}
