- ai_overview:
    title: "应用性能(1小时内)"
    metric_names: "application_http"
    type: "ai"
    order: 0
    defines:
      avg.elapsed_mean:
        label: "响应时间"
        unit: "ms"
        unit_type: "time"
        axis_index: 0
        chart_type: ""
      sumCpm.elapsed_count:
        label: "吞吐量"
        unit: ""
        unit_type: ""
        axis_index: 0
        chart_type: ""
    parameters:

