version: "1.1"
stages:
- stage:
  - git:
      alias: repo
      params:
        depth: 1
- stage:
  - buildpack:
      alias: build
      params:
        context: ${repo}
        modules:
        - image:
            name: registry.cn-hangzhou.aliyuncs.com/dice/addon-platform:3.4.0-((date.YYYYMMDD))-((gittar.commit.abbrev))
            password: pass
            username: user
          name: addon-platform
          path: .
- stage:
  - dicehub:
      alias: dicehub
      params:
        check_diceyml: false
        dice_yml: ${repo}/dice.yml
        init_sql: ${repo}/sql/init.sql
        release_id_path: dicehub
        replacement_images:
        - ${build}/pack-result
- stage:
  - custom-script:
      commands:
        - echo ${git-checkout:OUTPUT:BRANCH}
