name: "HTTP Slow"
tags:
    cluster_name:
        name: "Cluster Name"
    component:
        name: "Component"
    host:
        name: "Host"
    host_ip:
        name: "Host IP"
    http_method:
        name: "HTTP Method"
    http_path:
        name: "HTTP Path"
    http_status_code:
        name: "HTTP Status Code"
    http_url:
        name: "HTTP URL"
    org_name:
        name: "Org Name"
    peer_hostname:
        name: "Peer Hostname"
    req_client_err:
        name: "Req Client Err"
    req_host:
        name: "Req Host"
    req_server_err:
        name: "Req Server Err"
    req_success:
        name: "Req Success"
    request_id:
        name: "Request ID"
    source_addon_id:
        name: "Source Addon ID"
    source_addon_type:
        name: "Source Addon Type"
    span_host:
        name: "Span Host"
    target_addon_id:
        name: "Target Addon ID"
    target_addon_type:
        name: "Target Addon Type"
    target_application_id:
        name: "Target Application ID"
    target_application_name:
        name: "Target Application Name"
    target_instance_id:
        name: "Target Instance ID"
    target_org_id:
        name: "Target Org ID"
    target_project_id:
        name: "Target Project ID"
    target_project_name:
        name: "Target Project Name"
    target_runtime_id:
        name: "Target Runtime ID"
    target_runtime_name:
        name: "Target Runtime Name"
    target_service_id:
        name: "Target Service ID"
    target_service_instance_id:
        name: "Target Service Instance ID"
    target_service_name:
        name: "Target Service Name"
    target_terminus_key:
        name: "Target Terminus Key"
    target_workspace:
        name: "Target Workspace"
        values:
            - value: "DEV"
              name: "Develop"
            - value: "TEST"
              name: "Test"
            - value: "STAGING"
              name: "Staging"
            - value: "PROD"
              name: "Production"
    trace_sampled:
        name: "Trace Sampled"
fields:
    active_conns_count:
        type: "number"
        name: "Active Conns Count"
        uint: 
    active_conns_max:
        type: "number"
        name: "Active Conns Maximum"
        uint: 
    active_conns_mean:
        type: "number"
        name: "Active Conns Mean"
        uint: 
    active_conns_min:
        type: "number"
        name: "Active Conns Minimum"
        uint: 
    active_conns_sum:
        type: "number"
        name: "Active Conns Sum"
        uint: 
    cnt_count:
        type: "number"
        name: "Cnt Count"
        uint: 
    cnt_max:
        type: "number"
        name: "Cnt Maximum"
        uint: 
    cnt_mean:
        type: "number"
        name: "Cnt Mean"
        uint: 
    cnt_min:
        type: "number"
        name: "Cnt Minimum"
        uint: 
    cnt_sum:
        type: "number"
        name: "Cnt Sum"
        uint: 
    elapsed_count:
        type: "number"
        name: "Request Count"
        uint: 
    elapsed_max:
        type: "number"
        name: "Elapsed Maximum"
        uint: 
    elapsed_mean:
        type: "number"
        name: "Elapsed Mean"
        uint: 
    elapsed_min:
        type: "number"
        name: "Elapsed Minimum"
        uint: 
    elapsed_sum:
        type: "number"
        name: "Elapsed"
        uint: 
    http_status_code_max:
        type: "number"
        name: "HTTP Status Code Maximum"
        uint: 
    http_status_code_mean:
        type: "number"
        name: "HTTP Status Code Mean"
        uint: 
    http_status_code_min:
        type: "number"
        name: "HTTP Status Code Minimum"
        uint: 
    http_status_code_sum:
        type: "number"
        name: "HTTP Status Code Sum"
        uint: 
    idle_conns_count:
        type: "number"
        name: "Idle Conns Count"
        uint: 
    idle_conns_max:
        type: "number"
        name: "Idle Conns Maximum"
        uint: 
    idle_conns_mean:
        type: "number"
        name: "Idle Conns Mean"
        uint: 
    idle_conns_min:
        type: "number"
        name: "Idle Conns Minimum"
        uint: 
    idle_conns_sum:
        type: "number"
        name: "Idle Conns Sum"
        uint: 
    in_bytes_count:
        type: "number"
        name: "In Bytes Count"
        uint: 
    in_bytes_max:
        type: "number"
        name: "In Bytes Maximum"
        uint: 
    in_bytes_mean:
        type: "number"
        name: "In Bytes Mean"
        uint: 
    in_bytes_min:
        type: "number"
        name: "In Bytes Minimum"
        uint: 
    in_bytes_sum:
        type: "number"
        name: "In Bytes Sum"
        uint: 
    latency_count:
        type: "number"
        name: "Latency Count"
        uint: 
    latency_max:
        type: "number"
        name: "Latency Maximum"
        uint: 
    latency_mean:
        type: "number"
        name: "Latency Mean"
        uint: 
    latency_min:
        type: "number"
        name: "Latency Minimum"
        uint: 
    latency_sum:
        type: "number"
        name: "Latency Sum"
        uint: 
    out_bytes_count:
        type: "number"
        name: "Out Bytes Count"
        uint: 
    out_bytes_max:
        type: "number"
        name: "Out Bytes Maximum"
        uint: 
    out_bytes_mean:
        type: "number"
        name: "Out Bytes Mean"
        uint: 
    out_bytes_min:
        type: "number"
        name: "Out Bytes Minimum"
        uint: 
    out_bytes_sum:
        type: "number"
        name: "Out Bytes Sum"
        uint: 
    total_conns_count:
        type: "number"
        name: "Total Conns Count"
        uint: 
    total_conns_max:
        type: "number"
        name: "Total Conns Maximum"
        uint: 
    total_conns_mean:
        type: "number"
        name: "Total Conns Mean"
        uint: 
    total_conns_min:
        type: "number"
        name: "Total Conns Minimum"
        uint: 
    total_conns_sum:
        type: "number"
        name: "Total Conns Sum"
        uint: 
    upstream_latency_count:
        type: "number"
        name: "Upstream Latency Count"
        uint: 
    upstream_latency_max:
        type: "number"
        name: "Upstream Latency Maximum"
        uint: 
    upstream_latency_mean:
        type: "number"
        name: "Upstream Latency Mean"
        uint: 
    upstream_latency_min:
        type: "number"
        name: "Upstream Latency Minimum"
        uint: 
    upstream_latency_sum:
        type: "number"
        name: "Upstream Latency Sum"
        uint: 

