@url = http://localhost:8081

### ListServices
GET {{url}}/api/msp/diagnosis/09293f90cbc9ed09e0ec9a9df2b69212/services
Accept: application/json
Content-Type: application/json
User-ID: 1100
Org-ID: 1

### StartDiagnosis
POST {{url}}/api/msp/diagnosis/09293f90cbc9ed09e0ec9a9df2b69212
    ?clusterName=terminus-dev
    &instanceIP=10.112.3.147
Accept: application/json
Content-Type: application/json
User-ID: 1100
Org-ID: 1

### QueryDiagnosisStatus
GET {{url}}/api/msp/diagnosis/09293f90cbc9ed09e0ec9a9df2b69212/status
    ?clusterName=terminus-dev
    &instanceIP=10.112.3.147
Accept: application/json
User-ID: 1100
Org-ID: 1

### StopDiagnosis
DELETE {{url}}/api/msp/diagnosis/09293f90cbc9ed09e0ec9a9df2b69212
    ?clusterName=terminus-dev
    &instanceIP=10.112.3.147
Accept: application/json
User-ID: 1100
Org-ID: 1

### ListProcesses
GET {{url}}/api/msp/diagnosis/09293f90cbc9ed09e0ec9a9df2b69212/processes
    ?clusterName=terminus-dev
    &instanceIP=10.112.3.147
Accept: application/json
User-ID: 1100
Org-ID: 1
