// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Source: unittest.proto

package pb

import (
	context "context"
	http1 "net/http"
	strconv "strconv"
	strings "strings"

	transport "github.com/erda-project/erda-infra/pkg/transport"
	http "github.com/erda-project/erda-infra/pkg/transport/http"
	httprule "github.com/erda-project/erda-infra/pkg/transport/http/httprule"
	runtime "github.com/erda-project/erda-infra/pkg/transport/http/runtime"
	urlenc "github.com/erda-project/erda-infra/pkg/urlenc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "github.com/erda-project/erda-infra/pkg/transport/http" package it is being compiled against.
const _ = http.SupportPackageIsVersion1

// UnitTestServiceHandler is the server API for UnitTestService service.
type UnitTestServiceHandler interface {
	// POST /api/qa/actions/test-callback
	Callback(context.Context, *TestCallBackRequest) (*TestCallBackResponse, error)
	// GET /api/qa/actions/all-test-type
	GetTestTypes(context.Context, *TestTypeRequest) (*TestTypeResponse, error)
	// GET /api/qa/actions/test-list
	ListRecords(context.Context, *TestRecordPagingRequest) (*TestRecordPagingResponse, error)
	// GET /api/qa/test/{id}
	GetRecord(context.Context, *TestRecordGetRequest) (*TestRecordGetResponse, error)
}

// RegisterUnitTestServiceHandler register UnitTestServiceHandler to http.Router.
func RegisterUnitTestServiceHandler(r http.Router, srv UnitTestServiceHandler, opts ...http.HandleOption) {
	h := http.DefaultHandleOptions()
	for _, op := range opts {
		op(h)
	}
	encodeFunc := func(fn func(http1.ResponseWriter, *http1.Request) (interface{}, error)) http.HandlerFunc {
		handler := func(w http1.ResponseWriter, r *http1.Request) {
			out, err := fn(w, r)
			if err != nil {
				h.Error(w, r, err)
				return
			}
			if err := h.Encode(w, r, out); err != nil {
				h.Error(w, r, err)
			}
		}
		if h.HTTPInterceptor != nil {
			handler = h.HTTPInterceptor(handler)
		}
		return handler
	}

	add_Callback := func(method, path string, fn func(context.Context, *TestCallBackRequest) (*TestCallBackResponse, error)) {
		handler := func(ctx context.Context, req interface{}) (interface{}, error) {
			return fn(ctx, req.(*TestCallBackRequest))
		}
		var Callback_info transport.ServiceInfo
		if h.Interceptor != nil {
			Callback_info = transport.NewServiceInfo("erda.dop.qa.unittest.UnitTestService", "Callback", srv)
			handler = h.Interceptor(handler)
		}
		r.Add(method, path, encodeFunc(
			func(w http1.ResponseWriter, r *http1.Request) (interface{}, error) {
				ctx := http.WithRequest(r.Context(), r)
				ctx = transport.WithHTTPHeaderForServer(ctx, r.Header)
				if h.Interceptor != nil {
					ctx = context.WithValue(ctx, transport.ServiceInfoContextKey, Callback_info)
				}
				r = r.WithContext(ctx)
				var in TestCallBackRequest
				if err := h.Decode(r, &in); err != nil {
					return nil, err
				}
				var input interface{} = &in
				if u, ok := (input).(urlenc.URLValuesUnmarshaler); ok {
					if err := u.UnmarshalURLValues("", r.URL.Query()); err != nil {
						return nil, err
					}
				}
				out, err := handler(ctx, &in)
				if err != nil {
					return out, err
				}
				return out, nil
			}),
		)
	}

	add_GetTestTypes := func(method, path string, fn func(context.Context, *TestTypeRequest) (*TestTypeResponse, error)) {
		handler := func(ctx context.Context, req interface{}) (interface{}, error) {
			return fn(ctx, req.(*TestTypeRequest))
		}
		var GetTestTypes_info transport.ServiceInfo
		if h.Interceptor != nil {
			GetTestTypes_info = transport.NewServiceInfo("erda.dop.qa.unittest.UnitTestService", "GetTestTypes", srv)
			handler = h.Interceptor(handler)
		}
		r.Add(method, path, encodeFunc(
			func(w http1.ResponseWriter, r *http1.Request) (interface{}, error) {
				ctx := http.WithRequest(r.Context(), r)
				ctx = transport.WithHTTPHeaderForServer(ctx, r.Header)
				if h.Interceptor != nil {
					ctx = context.WithValue(ctx, transport.ServiceInfoContextKey, GetTestTypes_info)
				}
				r = r.WithContext(ctx)
				var in TestTypeRequest
				if err := h.Decode(r, &in); err != nil {
					return nil, err
				}
				var input interface{} = &in
				if u, ok := (input).(urlenc.URLValuesUnmarshaler); ok {
					if err := u.UnmarshalURLValues("", r.URL.Query()); err != nil {
						return nil, err
					}
				}
				out, err := handler(ctx, &in)
				if err != nil {
					return out, err
				}
				return out, nil
			}),
		)
	}

	add_ListRecords := func(method, path string, fn func(context.Context, *TestRecordPagingRequest) (*TestRecordPagingResponse, error)) {
		handler := func(ctx context.Context, req interface{}) (interface{}, error) {
			return fn(ctx, req.(*TestRecordPagingRequest))
		}
		var ListRecords_info transport.ServiceInfo
		if h.Interceptor != nil {
			ListRecords_info = transport.NewServiceInfo("erda.dop.qa.unittest.UnitTestService", "ListRecords", srv)
			handler = h.Interceptor(handler)
		}
		r.Add(method, path, encodeFunc(
			func(w http1.ResponseWriter, r *http1.Request) (interface{}, error) {
				ctx := http.WithRequest(r.Context(), r)
				ctx = transport.WithHTTPHeaderForServer(ctx, r.Header)
				if h.Interceptor != nil {
					ctx = context.WithValue(ctx, transport.ServiceInfoContextKey, ListRecords_info)
				}
				r = r.WithContext(ctx)
				var in TestRecordPagingRequest
				if err := h.Decode(r, &in); err != nil {
					return nil, err
				}
				var input interface{} = &in
				if u, ok := (input).(urlenc.URLValuesUnmarshaler); ok {
					if err := u.UnmarshalURLValues("", r.URL.Query()); err != nil {
						return nil, err
					}
				}
				out, err := handler(ctx, &in)
				if err != nil {
					return out, err
				}
				return out, nil
			}),
		)
	}

	add_GetRecord := func(method, path string, fn func(context.Context, *TestRecordGetRequest) (*TestRecordGetResponse, error)) {
		handler := func(ctx context.Context, req interface{}) (interface{}, error) {
			return fn(ctx, req.(*TestRecordGetRequest))
		}
		var GetRecord_info transport.ServiceInfo
		if h.Interceptor != nil {
			GetRecord_info = transport.NewServiceInfo("erda.dop.qa.unittest.UnitTestService", "GetRecord", srv)
			handler = h.Interceptor(handler)
		}
		compiler, _ := httprule.Parse(path)
		temp := compiler.Compile()
		pattern, _ := runtime.NewPattern(httprule.SupportPackageIsVersion1, temp.OpCodes, temp.Pool, temp.Verb)
		r.Add(method, path, encodeFunc(
			func(w http1.ResponseWriter, r *http1.Request) (interface{}, error) {
				ctx := http.WithRequest(r.Context(), r)
				ctx = transport.WithHTTPHeaderForServer(ctx, r.Header)
				if h.Interceptor != nil {
					ctx = context.WithValue(ctx, transport.ServiceInfoContextKey, GetRecord_info)
				}
				r = r.WithContext(ctx)
				var in TestRecordGetRequest
				if err := h.Decode(r, &in); err != nil {
					return nil, err
				}
				var input interface{} = &in
				if u, ok := (input).(urlenc.URLValuesUnmarshaler); ok {
					if err := u.UnmarshalURLValues("", r.URL.Query()); err != nil {
						return nil, err
					}
				}
				path := r.URL.Path
				if len(path) > 0 {
					components := strings.Split(path[1:], "/")
					last := len(components) - 1
					var verb string
					if idx := strings.LastIndex(components[last], ":"); idx >= 0 {
						c := components[last]
						components[last], verb = c[:idx], c[idx+1:]
					}
					vars, err := pattern.Match(components, verb)
					if err != nil {
						return nil, err
					}
					for k, val := range vars {
						switch k {
						case "id":
							val, err := strconv.ParseUint(val, 10, 64)
							if err != nil {
								return nil, err
							}
							in.Id = val
						}
					}
				}
				out, err := handler(ctx, &in)
				if err != nil {
					return out, err
				}
				return out, nil
			}),
		)
	}

	add_Callback("POST", "/api/qa/actions/test-callback", srv.Callback)
	add_GetTestTypes("GET", "/api/qa/actions/all-test-type", srv.GetTestTypes)
	add_ListRecords("GET", "/api/qa/actions/test-list", srv.ListRecords)
	add_GetRecord("GET", "/api/qa/test/{id}", srv.GetRecord)
}
