// Code generated by protoc-gen-go-json. DO NOT EDIT.
// Source: project.proto

package pb

import (
	bytes "bytes"
	json "encoding/json"

	jsonpb "github.com/erda-project/erda-infra/pkg/transport/http/encoding/jsonpb"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "encoding/json" package it is being compiled against.
var _ json.Marshaler = (*ProjectHome)(nil)
var _ json.Unmarshaler = (*ProjectHome)(nil)
var _ json.Marshaler = (*Link)(nil)
var _ json.Unmarshaler = (*Link)(nil)
var _ json.Marshaler = (*GetProjectHomeRequest)(nil)
var _ json.Unmarshaler = (*GetProjectHomeRequest)(nil)
var _ json.Marshaler = (*GetProjectHomeResponse)(nil)
var _ json.Unmarshaler = (*GetProjectHomeResponse)(nil)
var _ json.Marshaler = (*CreateOrUpdateProjectHomeRequest)(nil)
var _ json.Unmarshaler = (*CreateOrUpdateProjectHomeRequest)(nil)
var _ json.Marshaler = (*CreateOrUpdateProjectHomeResponse)(nil)
var _ json.Unmarshaler = (*CreateOrUpdateProjectHomeResponse)(nil)

// ProjectHome implement json.Marshaler.
func (m *ProjectHome) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// ProjectHome implement json.Marshaler.
func (m *ProjectHome) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// Link implement json.Marshaler.
func (m *Link) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// Link implement json.Marshaler.
func (m *Link) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// GetProjectHomeRequest implement json.Marshaler.
func (m *GetProjectHomeRequest) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// GetProjectHomeRequest implement json.Marshaler.
func (m *GetProjectHomeRequest) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// GetProjectHomeResponse implement json.Marshaler.
func (m *GetProjectHomeResponse) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// GetProjectHomeResponse implement json.Marshaler.
func (m *GetProjectHomeResponse) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// CreateOrUpdateProjectHomeRequest implement json.Marshaler.
func (m *CreateOrUpdateProjectHomeRequest) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// CreateOrUpdateProjectHomeRequest implement json.Marshaler.
func (m *CreateOrUpdateProjectHomeRequest) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}

// CreateOrUpdateProjectHomeResponse implement json.Marshaler.
func (m *CreateOrUpdateProjectHomeResponse) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	err := (&jsonpb.Marshaler{
		OrigName:     false,
		EnumsAsInts:  false,
		EmitDefaults: true,
	}).Marshal(buf, m)
	return buf.Bytes(), err
}

// CreateOrUpdateProjectHomeResponse implement json.Marshaler.
func (m *CreateOrUpdateProjectHomeResponse) UnmarshalJSON(b []byte) error {
	return (&protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}).Unmarshal(b, m)
}
