- ajs_alloc:
    title: "Addon Service Job 资源分配"
    metric_names: "docker_container_summary"
    defines:
      group_reduce.{group=tags.service_id&avg=fields.cpu_allocation&reduce=sum}:
        label: "service"
        unit: ""
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
      group_reduce.{group=tags.addon_id&avg=fields.cpu_allocation&reduce=sum}:
        label: "addon"
        unit: ""
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
      group_reduce.{group=tags.job_id&avg=fields.cpu_allocation&reduce=sum}:
        label: "job"
        unit: ""
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
      group_reduce.{group=tags.service_id&avg=fields.mem_allocation&reduce=sum}:
        label: "service"
        unit: "B"
        unit_type: "CAPACITY"
        axis_index: 0
        chart_type: "line"
      group_reduce.{group=tags.addon_id&avg=fields.mem_allocation&reduce=sum}:
        label: "addon"
        unit: "B"
        unit_type: "CAPACITY"
        axis_index: 0
        chart_type: "line"
      group_reduce.{group=tags.job_id&avg=fields.mem_allocation&reduce=sum}:
        label: "job"
        unit: "B"
        unit_type: "CAPACITY"
        axis_index: 0
        chart_type: "line"
    default: null
    parameters: null

- ajs_count:
    title: "Addon Service Job 数量"
    metric_names: "docker_container_summary"
    defines:
      cardinality.tags.job_id:
        label: "job"
      cardinality.tags.addon_id:
        label: "addon"
      cardinality.tags.service_id:
        label: "service"
    default: null
    parameters: null


- container_top:
    title: "容器监控"
    metric_names: "docker_container_summary"
    defines:
      last.mem_limit:
        label: "内存限制"
        unit: "B"
        axis_index: 0
        chart_type: "line"
        unit_type: "CAPACITY"
      last.mem_usage:
        label: "内存使用量(含cache)"
        unit: "B"
        axis_index: 0
        chart_type: "line"
        unit_type: "CAPACITY"
      last.mem_usage_percent:
        label: "内存使用量百分比"
        unit: "%"
        unit_type: "PERCENT"
        axis_index: 0
        chart_type: "line"
      last.cpu_usage_percent:
        label: "cpu使用量百分比"
        unit: "%"
        unit_type: "PERCENT"
        axis_index: 0
        chart_type: "line"
      diffps.blk_read_bytes:
        label: "读取"
        unit: "B/s"
        unit_type: "TRAFFIC"
        axis_index: 0
        chart_type: "line"
      diffps.blk_write_bytes:
        label: "写入"
        unit: "B/s"
        unit_type: "TRAFFIC"
        axis_index: 0
        chart_type: "line"
      diffps.rx_bytes:
        label: "接收"
        unit: "B/s"
        unit_type: "TRAFFIC"
        axis_index: 0
        chart_type: "line"
      diffps.tx_bytes:
        label: "发送"
        unit: "B/s"
        unit_type: "TRAFFIC"
        axis_index: 0
        chart_type: "line"
    default: null
    parameters: null
