openapi: 3.0.0
info:
  description: |
    marketplace 接口文档.
  version: "2.2.0"
  title: Erda Marketplace
  contact:
    email: rainchan365@163.com
servers:
  - url: 'https://openapi.dev.terminus.io'
tags:
  - name: gallery
    description: gallery

paths:
  /api/marketplace/gallery:
    get:
      tags:
        - gallery
      summary: 查询组织下所有的 gallery 资源
      description: 查询组织下所有的 artifacts 资源 (extensions 和 上架的项目制品)
      parameters:
        - name: type
          in: query
          description: 根据 type 可筛选 artifacts 类型; 不传时查询所有类型
          required: false
          schema:
            type: string
            enum:
              - extension/action
              - extension/addon
              - artifacts/project
            example: "extension/addon"
        - name: keyword
          in: query
          description: 搜索关键字
          x-todo: 搜索什么字段
          required: false
          schema:
              type: string
              default: ""
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            default: 1
        - name: pageNo
          in: query
          required: false
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      "total":
                        description: 数量
                        type: integer
                      "list":
                        description: 列表
                        type: array
                        items:
                          type: object
                          properties:
                            "id":
                              type: string
                            "releaseID":
                              type: string
                              description: 仅 type=artifacts/project 时有有效的值
                            "type":
                              description: gallery 类型
                              type: string
                              enum:
                                - extension/action
                                - extension/addon
                                - artifacts/project
                            "name":
                              description: gallery 名称
                              type: string
                            "displayName":
                              type: string
                            "category":
                              type: string
                            "displayCategory":
                              type: string
                              description: with i18n
                            "desc":
                              description: 描述信息
                            "publisher":
                              type: object
                              properties:
                                "id":
                                  type: string
                                "name":
                                  type: string
                                "nickName":
                                  type: string
                              description: Erda 官方发布的 extensions 值为 Erda Cloud.
                            "logoUrl":
                              type: string

  /api/marketplace/gallery/{name}:
    parameters:
      - name: name
        in: path
        description: gallery name
        required: true
        schema:
          type: string

    get:
      tags:
        - gallery
      summary: 某 gallery 的详情
      description: 某 gallery 的详情
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                type: object
                properties:
                  "data":
                    type: array
                    items:
                      type: object
                      properties:
                        "name":
                          type: string
                        "displayName":
                          type: string
                        "version":
                          type: string
                        "type":
                          type: string
                        "category":
                          type: string
                        "logoUrl":
                          type: string
                        "dice":
                          type: object
                          allOf:
                            - $ref: '#/components/schemas/JSONRawMessage'
                        "spec":
                          type: object
                          allOf:
                            - $ref: '#/components/schemas/JSONRawMessage'
                        "readme":
                          type: string
                          description: |-
                            with i18n. 英文时优先返回 readme.en.md 文本内容;
                            中文时优先返回 readme.zh_CN.md 的文本内容;
                            若没有这样的文件, 则返回 readme.md 的文本内容.
                        "changeLog":
                          type: string
                          description: extensions 显示 readme, artifacts 显示 changeLog
                        "isDefault":
                          type: boolean
                          description: 最多只有一个 {item}.isDefault 为 true, 如果有, 肯定排在第一个.
                        "createdAt":
                          type: string
                          format: date-time
                        "updatedAt":
                          type: string
                          format: date-time
                        "publisher":
                          type: object
                          properties:
                            "id":
                              type: string
                            "name":
                              type: string
                            "displayName":
                              type: string
                        "params":
                          description: action 的入参
                          type: array
                          items:
                            type: object
                            properties:
                              "name":
                                type: string
                              "type":
                                type: string
                              "desc":
                                type: string
                                description: with i18n
                              "required":
                                type: boolean
                              "default":
                                type: string
                        "outputs":
                          description: action 的出参
                          type: array
                          items:
                            type: object
                            properties:
                              "name":
                                type: string
                              "type":
                                type: string
                              "desc":
                                type: string
                        "configVars":
                          description: 自定义 addon 的环境变量
                          type: array
                          items:
                            type: string

    delete:
      tags:
        - gallery
      summary: 制品下架
      parameters:
        - name: version
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            "application/json":
              schema:
                $ref: '#/components/schemas/BaseResponse'

  /api/marketplace/gallery/{name}/actions/gen-shared-url:
    parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
    post:
      tags:
        - gallery
      summary: 生成页面分享查看链接
      requestBody:
        $ref: "#/components/requestBodies/GenerateSharedURL"
      responses:
        "200":
          description: successful operation
          content:
            "application/json":
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                properties:
                  "data":
                    type: object
                    properties:
                      "name":
                        type: string
                      "version":
                        type: string
                      "url":
                        type: string

  /api/releases/{id}/actions/publish:
    parameters:
      - name: id
        in: path
        description: release id
        required: true
        schema:
          type: string
    post:
      tags:
        - gallery
      summary: 制品上架
      description: 发布制品到 gallery
      requestBody:
        $ref: "#/components/requestBodies/PublishGallery"
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponse'
                properties:
                  "data":
                    type: object
                    properties:
                      "id":
                        type: string


components:
  schemas:
    BaseResponse:
      type: object
      properties:
        success:
          type: boolean
        err:
          type: object

    JSONRawMessage:
      type: object

  requestBodies:
    GenerateSharedURL:
      content:
        "application/json":
          schema:
            type: object
            properties:
              "name":
                type: string
              "version":
                type: string
      required: true
    PublishGallery:
      content:
        "application/json":
          schema:
            type: object
            properties:
              "name":
                type: string
                description: |-
                  todo: 是否需要用户取名 ?
