// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: legacy_upstream_lb.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/protobuf/types/known/structpb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *UpstreamLb) Validate() error {
	return nil
}
func (this *TargetOnlineRequest) Validate() error {
	if this.Lb != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Lb); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Lb", err)
		}
	}
	return nil
}
func (this *TargetOnlineResponse) Validate() error {
	return nil
}
func (this *TargetOfflineRequest) Validate() error {
	if this.Lb != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Lb); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Lb", err)
		}
	}
	return nil
}
func (this *TargetOfflineResponse) Validate() error {
	return nil
}
