@url = http://localhost:8080

### List File
GET {{url}}/api/container/6e7bbccdc0db85d158aee8cf413c04b1f868017482e6f2e9dd29efde976e6e55/files
    ?hostIP=10.167.0.101
    &path=/
    &scope=org
Accept: application/json
User-ID: 1100
Org-ID: 1

### List File
GET {{url}}/api/container/a302ff5f972b25da25e12f8b3842a68de3dd905414fba8156b23aa271b8e8995/files
    ?hostIP=10.0.0.85
    &path=/
    &scope=org
Accept: application/json
User-ID: 1100
Org-ID: 1

### ReadFile
GET {{url}}/api/container/ea0d72abd63a620381f761dda96aeba2bcc8d751e6a244cf7b965393ebbc1f9b/file
    ?hostIP=10.0.6.219
    &path=/xxxxx1.txt
    &scope=org
Accept: application/json
User-ID: 1100
Org-ID: 1

### WriteFile
POST {{url}}/api/container/ea0d72abd63a620381f761dda96aeba2bcc8d751e6a244cf7b965393ebbc1f9b/file
    ?hostIP=10.0.6.219
    &path=/xxxxx1.txt
    &action=
    &scope=org
Content-Type: application/json
Accept: application/json
User-ID: 1100
Org-ID: 1

{
    "encoding": "base64",
    "content": "eHh4eHh4"
}

### MakeDirectory
POST {{url}}/api/container/ea0d72abd63a620381f761dda96aeba2bcc8d751e6a244cf7b965393ebbc1f9b/files/mkdir
    ?hostIP=10.0.6.219
    &path=/xxxxx1dir/xxx/yyy/zzzz
    &all=true
    &scope=org
Content-Type: application/json
Accept: application/json
User-ID: 1100
Org-ID: 1

### MoveFile
POST {{url}}/api/container/ea0d72abd63a620381f761dda96aeba2bcc8d751e6a244cf7b965393ebbc1f9b/files/mv
    ?hostIP=10.0.6.219
    &scope=org
Content-Type: application/json
Accept: application/json
User-ID: 1100
Org-ID: 1

{
    "source": "/xxxxx1dir/xxxxx4.txt",
    "destination": "/xxxxx1dir/xxxxx5.txt"
}

### DeleteFile
DELETE {{url}}/api/container/ea0d72abd63a620381f761dda96aeba2bcc8d751e6a244cf7b965393ebbc1f9b/file
    ?hostIP=10.0.6.219
    &path=/xxxxx1dir/xxxxx5.txt
    &scope=org
Accept: application/json
User-ID: 1100
Org-ID: 1

### DownloadFile
GET {{url}}/api/container/ea0d72abd63a620381f761dda96aeba2bcc8d751e6a244cf7b965393ebbc1f9b/files/download
    ?hostIP=10.0.6.219
    &path=/xxxxx2.txt
    &scope=org
User-ID: 1100
Org-ID: 1