- mysql_slow_queries:
    title: "慢查询频率"
    metric_names: "mysql"
    type: "mysql"
    order: 2
    defines:
      diffps.slow_queries:
        label: ""
        unit: "次/s"
        unit_type: "NPS"
        axis_index: 0
        chart_type: "line"
    parameters:
      group:
        - "server"

