- system_addon_cassandra_old_gc_time:
    title: "老年代GC累计耗时"
    metric_names: "addon_java_garbagecollector"
    type: "cassandra"
    order: 4
    defines:
      max.CollectionTime:
        label: "GC累计耗时"
        unit: "ms"
        unit_type: "time"
        axis_index: 0
        chart_type: "line"
        original_unit: "ms"
    parameters:
      group:
        - "jolokia_host"
      match_name:
        - "*Old*"

