codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

comment: # this is a top-level key
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false   # if true: only post the comment if coverage changes
  require_base: false      # [yes :: must have a base report to post]
  require_head: false      # [yes :: must have a head report to post]
#  branches:               # branch names that can post comment

coverage:
  precision: 2
  round: down
  range: "60...100"
  status:
    project:
      default:
        # basic
        target: 10%
        threshold: 0%
        base: auto
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        if_ci_failed: error
        only_pulls: false

github_checks:
  annotations: true

ignore:
  # ignore the boilerplate code
  - "internal/**/conf"
  - "internal/**/dbclient"
  - "internal/**/dao"
  - "bundle"
  - "api/proto-go"
  - "internal/tools/openapi/legacy/api/apis/**/*.go"
