// Code generated by protoc-gen-go-form. DO NOT EDIT.
// Source: event.proto

package pb

import (
	url "net/url"
	strconv "strconv"

	urlenc "github.com/erda-project/erda-infra/pkg/urlenc"
	pb "github.com/erda-project/erda-proto-go/oap/common/pb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "github.com/erda-project/erda-infra/pkg/urlenc" package it is being compiled against.
var _ urlenc.URLValuesUnmarshaler = (*Event)(nil)

// Event implement urlenc.URLValuesUnmarshaler.
func (m *Event) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "eventID":
				m.EventID = vals[0]
			case "severity":
				m.Severity = vals[0]
			case "name":
				m.Name = vals[0]
			case "kind":
			case "timeUnixNano":
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.TimeUnixNano = val
			case "relations":
				if m.Relations == nil {
					m.Relations = &pb.Relation{}
				}
			case "relations.traceID":
				if m.Relations == nil {
					m.Relations = &pb.Relation{}
				}
				m.Relations.TraceID = vals[0]
			case "relations.resID":
				if m.Relations == nil {
					m.Relations = &pb.Relation{}
				}
				m.Relations.ResID = vals[0]
			case "relations.resType":
				if m.Relations == nil {
					m.Relations = &pb.Relation{}
				}
				m.Relations.ResType = vals[0]
			case "relations.resourceKeys":
				if m.Relations == nil {
					m.Relations = &pb.Relation{}
				}
				m.Relations.ResourceKeys = vals
			case "message":
				m.Message = vals[0]
			}
		}
	}
	return nil
}
