- system_addon_kafka_gc:
    title: "老年代GC次数"
    metric_names: "addon_java_garbagecollector"
    type: "kafka"
    order: 3
    defines:
      diffps.CollectionCount:
        label: ""
        unit: "次/s"
        unit_type: "NPS"
        axis_index: 0
        chart_type: "line"
    parameters:
      group:
        - "jolokia_host"
      match_name:
        - "*Old*"

