# see: internal/pkg/ai-proxy/route/route.go#Routes

routes:
  - path: /v1/chat/completions
    method: POST
    router: null
    filters:
      - name: initialize
      - name: log-http
      - name: rate-limit
      - name: context
#      - name: body-size-limit
#        config:
#          maxSize: 102400
#          message: { "messages": [ { "role": "ai-proxy", "content": "问题超长啦, 请重置会话", "name": "ai-proxy" } ] }
      - name: context-chat
        config:
        #sysMsg: "background: Your name is Erda AI Assistant. You are trained by Erda."
      - name: audit-before-llm-director
      - name: azure-director
        config:
          directors:
            - TransAuthorization
            - SetModelAPIVersionIfNotSpecified
            - DefaultQueries("api-version=2023-07-01-preview")
            - RewriteScheme
            - RewriteHost
            - RewritePath("/openai/deployments/${ provider.metadata.deployment_id }/chat/completions")
            - AddContextMessages
      - name: openai-director
        config:
          directors:
            - TransAuthorization
            - RewriteScheme
            - RewriteHost
            - AddModelInRequestBody
            - AddContextMessages
      - name: bailian-director
      - name: dashscope-director
      - name: openai-director
      - name: audit-after-llm-director
      - name: finalize
  - path: /v1/embeddings
    method: POST
    router: null
    filters:
      - name: initialize
      - name: log-http
      - name: rate-limit
      - name: context
      - name: context-embedding
      - name: audit-before-llm-director
      - name: azure-director
        config:
          directors:
            - TransAuthorization
            - SetModelAPIVersionIfNotSpecified
            - DefaultQueries("api-version=2023-07-01-preview")
            - RewriteScheme
            - RewriteHost
            - RewritePath("/openai/deployments/${ provider.metadata.deployment_id }/embeddings")
      - name: openai-director
        config:
          directors:
            - TransAuthorization
            - RewriteScheme
            - RewriteHost
            - AddModelInRequestBody
      - name: audit-after-llm-director
      - name: finalize
  - path: /v1/audio/transcriptions
    method: POST
    router: null
    filters:
      - name: initialize
      - name: log-http
      - name: rate-limit
      - name: context
      - name: context-audio
        config:
          maxAudioSize: 25MB
          supportedAudioFileTypes: [ "flac", "mp3", "mp4", "mpeg", "mpga", "m4a", "ogg", "wav", "webm" ]
          defaultOpenAIAudioModel: whisper-1
      - name: audit-before-llm-director
      - name: azure-director
        config:
          directors:
            - TransAuthorization
            - SetModelAPIVersionIfNotSpecified
            - DefaultQueries("api-version=2023-09-01-preview")
            - RewriteScheme
            - RewriteHost
            - RewritePath("/openai/deployments/${ provider.metadata.deployment_id }/audio/transcriptions")
      - name: openai-director
        config:
          directors:
            - TransAuthorization
            - RewriteScheme
            - RewriteHost
            - AddModelInRequestBody
      - name: audit-after-llm-director
      - name: finalize
  - path: /v1/images/generations
    method: POST
    router: null
    filters:
      - name: initialize
      - name: log-http
      - name: rate-limit
      - name: context
      - name: context-image
        config:
          supportedResponseFormats: [ "url" ] # url, b64_json
      - name: audit-before-llm-director
      - name: azure-director
        config:
          directors:
            - TransAuthorization
            - SetModelAPIVersionIfNotSpecified
            - DefaultQueries("api-version=2023-12-01-preview")
            - RewriteScheme
            - RewriteHost
            - RewritePath("/openai/deployments/${ provider.metadata.deployment_id }/images/generations")
      - name: openai-director
        config:
          directors:
            - TransAuthorization
            - RewriteScheme
            - RewriteHost
            - AddModelInRequestBody
      - name: audit-after-llm-director
      - name: finalize
