- redis_used_memory:
    title: "Redis管理的内存"
    metric_names: "redis"
    type: "redis"
    order: 9
    defines:
      max.used_memory:
        label: ""
        unit: "B"
        unit_type: "CAPACITY"
        axis_index: 0
        chart_type: "line"
    parameters:
      group:
        - "server"

