// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Source: task_error.proto

package pb

import (
	context "context"
	http1 "net/http"

	transport "github.com/erda-project/erda-infra/pkg/transport"
	http "github.com/erda-project/erda-infra/pkg/transport/http"
	urlenc "github.com/erda-project/erda-infra/pkg/urlenc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "github.com/erda-project/erda-infra/pkg/transport/http" package it is being compiled against.
const _ = http.SupportPackageIsVersion1

// TaskErrorServiceHandler is the server API for TaskErrorService service.
type TaskErrorServiceHandler interface {
	// GET /api/task-error/actions/list
	ListErrorLog(context.Context, *ErrorLogListRequest) (*ErrorLogListResponseData, error)
}

// RegisterTaskErrorServiceHandler register TaskErrorServiceHandler to http.Router.
func RegisterTaskErrorServiceHandler(r http.Router, srv TaskErrorServiceHandler, opts ...http.HandleOption) {
	h := http.DefaultHandleOptions()
	for _, op := range opts {
		op(h)
	}
	encodeFunc := func(fn func(http1.ResponseWriter, *http1.Request) (interface{}, error)) http.HandlerFunc {
		handler := func(w http1.ResponseWriter, r *http1.Request) {
			out, err := fn(w, r)
			if err != nil {
				h.Error(w, r, err)
				return
			}
			if err := h.Encode(w, r, out); err != nil {
				h.Error(w, r, err)
			}
		}
		if h.HTTPInterceptor != nil {
			handler = h.HTTPInterceptor(handler)
		}
		return handler
	}

	add_ListErrorLog := func(method, path string, fn func(context.Context, *ErrorLogListRequest) (*ErrorLogListResponseData, error)) {
		handler := func(ctx context.Context, req interface{}) (interface{}, error) {
			return fn(ctx, req.(*ErrorLogListRequest))
		}
		var ListErrorLog_info transport.ServiceInfo
		if h.Interceptor != nil {
			ListErrorLog_info = transport.NewServiceInfo("erda.core.dop.taskerror.TaskErrorService", "ListErrorLog", srv)
			handler = h.Interceptor(handler)
		}
		r.Add(method, path, encodeFunc(
			func(w http1.ResponseWriter, r *http1.Request) (interface{}, error) {
				ctx := http.WithRequest(r.Context(), r)
				ctx = transport.WithHTTPHeaderForServer(ctx, r.Header)
				if h.Interceptor != nil {
					ctx = context.WithValue(ctx, transport.ServiceInfoContextKey, ListErrorLog_info)
				}
				r = r.WithContext(ctx)
				var in ErrorLogListRequest
				if err := h.Decode(r, &in); err != nil {
					return nil, err
				}
				var input interface{} = &in
				if u, ok := (input).(urlenc.URLValuesUnmarshaler); ok {
					if err := u.UnmarshalURLValues("", r.URL.Query()); err != nil {
						return nil, err
					}
				}
				out, err := handler(ctx, &in)
				if err != nil {
					return out, err
				}
				return out, nil
			}),
		)
	}

	add_ListErrorLog("GET", "/api/task-error/actions/list", srv.ListErrorLog)
}
