services:
  ai-proxy:
    image: registry.cn-hangzhou.aliyuncs.com/dspo/ai-proxy:2.3-alpha-20230423161004-c8fc039cf
    cmd: /erda/cmd/ai-proxy/bin
    deployments:
      replicas: 1
    envs:
      DEBUG: 'true'
    health_check:
      http:
        duration: 120
        path: /health
        port: 8080
    ports:
      - port: 8080
        protocol: TCP
        l4_protocol: TCP
        expose: true
    resources:
      cpu: 0.5
      mem: 1024
    expose: []
    hosts: []
    binds: []
addons:
  mysql:
    plan: mysql:basic
    options:
      version: 5.7.29
envs: {}