- zookeeper_min_latency:
    title: "最小延迟"
    metric_names: "zookeeper"
    type: "zookeeper_remove"
    order: 11
    defines:
      min.min_latency:
        label: ""
        unit: "MS"
        unit_type: "TIME"
        axis_index: 0
        chart_type: "line"
    parameters:
      group:
        - "server"

