- redis_rdb_changes_since_last_save:
    title: "自上次dump后rdb的改动次数"
    metric_names: "redis"
    type: "redis_remove"
    order: 21
    defines:
      avg.rdb_changes_since_last_save:
        label: ""
        unit: ""
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
    parameters:

