version: "1.1"
stages:
  - stage:
      - git-checkout:
          alias: github
          description: 代码仓库克隆
          version: "1.0"
          params:
            branch: ((branch))
            depth: 1
            uri: ((remote.dspo))
          loop:
            break: task_status == 'Success'
            strategy:
              max_times: 5
              decline_ratio: 2
              decline_limit_sec: 60
              interval_sec: 5
  - stage:
      - custom-script:
          alias: erda
          description: 运行自定义命令
          version: "1.0"
          commands:
            - cd ../github
            - make prepare
            - MODULE_PATH=cmp make build-push-image
          loop:
            break: task_status == 'Success'
            strategy:
              max_times: 5
              decline_ratio: 2
              decline_limit_sec: 60
              interval_sec: 5
          resources:
            cpu: 1
            mem: 2048