version: "1.1"
name: ""
stages:
  - stage:
      - git-checkout:
          alias: raw-erda
          description: 代码仓库克隆
          params:
            depth: 1
      - git-checkout:
          alias: erda-actions
          description: 代码仓库克隆
          params:
            branch: master
            depth: 1
            uri: https://erda.cloud/erda/dop/erda-project/erda-actions-mirror
      - git-checkout:
          alias: erda-addons
          description: 代码仓库克隆
          params:
            branch: master
            depth: 1
            uri: https://erda.cloud/erda/dop/erda-project/erda-addons-mirror
  - stage:
      - custom-script:
          alias: erda
          description: 运行自定义命令
          image: registry.erda.cloud/erda/gohub:1.0.7
          commands:
            - cp -a ${{ dirs.raw-erda }}/. .
            - make proto-go-in-local
          resources:
            cpu: 0.5
            mem: 2048
  - stage:
      - extract-repo-version:
          alias: extract-repo-version
          description: 从 git 代码仓库中解析提交信息，生成仓库版本
          params:
            git_dir: ${{ dirs.erda }}
  - stage:
      - custom-script:
          alias: build-erda
          description: 运行自定义命令
          image: registry.erda.cloud/erda/erda-base:20220726
          commands:
            - cd ${{ dirs.erda }}
            - mkdir -p extensions
            - cp -r ${{ dirs.erda-actions }} extensions
            - cp -r ${{ dirs.erda-addons }} extensions
            - export ERDA_VERSION=${{ outputs.extract-repo-version.major_minor_version }}
            - make prepare
            - make build-push-all
          loop:
            break: task_status == 'Success'
            strategy:
              max_times: 5
              decline_ratio: 2
              decline_limit_sec: 60
              interval_sec: 5
          resources:
            cpu: 1
            mem: 2048
      - custom-script:
          alias: build-cluster-agent
          description: 运行自定义命令
          commands:
            - cd ${{ dirs.erda }}
            - export ERDA_VERSION=${{ outputs.extract-repo-version.major_minor_version }}
            - MODULE_PATH=cluster-agent make build-push-image
          loop:
            break: task_status == 'Success'
            strategy:
              max_times: 5
              decline_ratio: 2
              decline_limit_sec: 60
              interval_sec: 5
          resources:
            cpu: 1
            mem: 2048
