version: "1.1"

# every day 13:00, 17:00, 20:00
cron: 0 0 13,17,20 * * ?

stages:
  - stage:
      - git-checkout:
          alias: erda
          params:
            depth: 1
  - stage:
      - git-checkout:
          alias: erda-ui
          params:
            uri: https://erda.cloud/erda/dop/erda-project/erda-ui-mirror
            branch: ${{ outputs.erda.branch }}
      - git-checkout:
          alias: erda-analyzer
          params:
            uri: https://erda.cloud/erda/dop/erda-project/erda-analyzer-mirror
            branch: ${{ outputs.erda.branch }}
            depth: 1
      - git-checkout:
          alias: erda-fluent-bit
          params:
            uri: https://erda.cloud/erda/dop/erda-project/erda-fluent-bit-mirror
            branch: ${{ outputs.erda.branch }}
            depth: 1
      - git-checkout:
          alias: erda-telegraf
          params:
            uri: https://erda.cloud/erda/dop/erda-project/telegraf-mirror
            branch: ${{ outputs.erda.branch }}
            depth: 1
      - git-checkout:
          alias: uc
          params:
            uri: https://erda.cloud/erda/dop/erda-project/uc-deploy
            branch: release/2.0 # always 2.0
            depth: 1
  - stage:
      - release-fetch:
          alias: fetch-release-erda
          params:
            application_name: erda-mirror
            branch: ${{ outputs.erda.branch }}
            #check_commit: ${{ outputs.erda.commit }}
      - release-fetch:
          alias: fetch-release-erda-ui
          params:
            application_name: erda-ui-mirror
            branch: ${{ outputs.erda-ui.branch }}
            #check_commit: ${{ outputs.erda-ui.commit }}
      - release-fetch:
          alias: fetch-release-erda-analyzer
          params:
            application_name: erda-analyzer-mirror
            branch: ${{ outputs.erda-analyzer.branch }}
            #check_commit: ${{ outputs.erda-analyzer.commit }}
      - release-fetch:
          alias: fetch-release-erda-fluent-bit
          params:
            application_name: erda-fluent-bit-mirror
            branch: ${{ outputs.erda-fluent-bit.branch }}
            #check_commit: ${{ outputs.erda-fluent-bit.commit }}
      - release-fetch:
          alias: fetch-release-erda-telegraf
          params:
            application_name: telegraf-mirror
            branch: ${{ outputs.erda-telegraf.branch }}
            #check_commit: ${{ outputs.erda-telegraf.commit }}
      - release-fetch:
          alias: fetch-release-uc
          params:
            application_name: uc-deploy
            branch: ${{ outputs.uc.branch }}
            #check_commit: ${{ outputs.uc.commit }}
  - stage:
      - erda-mysql-migration:
          alias: dryrun-on-mysql80
          version: 1.0-80
          params:
            database: erda
            lint_config: .erda/migrations/config.yml
            migrationdir: .erda/migrations
            mysql_host: ${{ configs.legacy_migration_mysql_host }}
            mysql_port: 3306
            mysql_username: ${{ configs.legacy_migration_mysql_username }}
            mysql_password: ${{ configs.legacy_migration_mysql_password }}
            retry_timeout: 150
            skip_migration: "true"
            skip_pre_migration: true
            workdir: ${{ dirs.erda }}
      - erda-mysql-migration:
          alias: dryrun-on-mysql56
          version: 1.0-56
          params:
            database: erda
            lint_config: .erda/migrations/config.yml
            migrationdir: .erda/migrations
            mysql_host: ${{ configs.legacy_migration_mysql_host }}
            mysql_port: 3306
            mysql_username: ${{ configs.legacy_migration_mysql_username }}
            mysql_password: ${{ configs.legacy_migration_mysql_password }}
            retry_timeout: 150
            skip_migration: "true"
            skip_pre_migration: true
            workdir: ${{ dirs.erda }}
  - stage:
      - erda-mysql-migration:
          alias: erda-mysql-migration
          version: 1.0-57
          params:
            database: erda
            lint_config: .erda/migrations/config.yml
            migrationdir: .erda/migrations
            mysql_host: ${{ configs.legacy_migration_mysql_host }}
            mysql_port: 3306
            mysql_username: ${{ configs.legacy_migration_mysql_username }}
            mysql_password: ${{ configs.legacy_migration_mysql_password }}
            retry_timeout: 150
            skip_lint: "true"
            skip_pre_migration: true
            workdir: ${{ dirs.erda }}
  - stage:
      - dice:
          alias: deploy-erda
          params:
            release_name: ${{ outputs.fetch-release-erda.release_name }}
            workspace: TEST
            type: application
            application_name: erda-mirror
      - dice:
          alias: deploy-erda-ui
          params:
            release_name: ${{ outputs.fetch-release-erda-ui.release_name }}
            workspace: TEST
            application_name: erda-ui-mirror
            type: application
      - dice:
          alias: deploy-erda-analyzer
          params:
            release_name: ${{ outputs.fetch-release-erda-analyzer.release_name }}
            workspace: TEST
            application_name: erda-analyzer-mirror
            type: application
      - dice:
          alias: deploy-erda-fluent-bit
          params:
            release_name: ${{ outputs.fetch-release-erda-fluent-bit.release_name }}
            workspace: TEST
            application_name: erda-fluent-bit-mirror
            type: application
      - dice:
          alias: deploy-erda-telegraf
          params:
            release_name: ${{ outputs.fetch-release-erda-telegraf.release_name }}
            workspace: TEST
            application_name: telegraf-mirror
            type: application
      - dice:
          alias: deploy-uc
          params:
            release_name: ${{ outputs.fetch-release-uc.release_name }}
            workspace: TEST
            application_name: uc-deploy
            type: application
