// Copyright (c) 2021 Terminus, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by erda-cli. DO NOT EDIT.
// Source: bin/erda-cli gorm gen -f .erda/ai-proxy/migrations/ai-proxy/20230823-ai-proxy.sql -o internal/apps/ai-proxy/models

package models

import (
	"time"

	"gorm.io/gorm"
)

var (
	_ time.Time
)

var (
	_ CRUDer = (*AIProxyModel)(nil)
	_ Lister = (*AIProxyModelList)(nil)
)

// FieldBaseModel returns the Field interface{} for the field ai_proxy_model.id
func (this AIProxyModel) FieldBaseModel() Field { return field{name: "id"} }

// FieldName returns the Field interface{} for the field ai_proxy_model.name
func (this AIProxyModel) FieldName() Field { return field{name: "name"} }

// FieldDesc returns the Field interface{} for the field ai_proxy_model.desc
func (this AIProxyModel) FieldDesc() Field { return field{name: "desc"} }

// FieldType returns the Field interface{} for the field ai_proxy_model.type
func (this AIProxyModel) FieldType() Field { return field{name: "type"} }

// FieldProviderID returns the Field interface{} for the field ai_proxy_model.provider_id
func (this AIProxyModel) FieldProviderID() Field { return field{name: "provider_id"} }

// FieldAPIKey returns the Field interface{} for the field ai_proxy_model.api_key
func (this AIProxyModel) FieldAPIKey() Field { return field{name: "api_key"} }

// FieldMetadata returns the Field interface{} for the field ai_proxy_model.metadata
func (this AIProxyModel) FieldMetadata() Field { return field{name: "metadata"} }

// Creator returns a Creator interface that you can create record with.
func (this *AIProxyModel) Creator(db *gorm.DB) Creator {
	return &creator{db: db, model: this}
}

// Retriever returns a Retriever that you can select one record with.
func (this *AIProxyModel) Retriever(db *gorm.DB) Retriever {
	return &retriever{
		db:    db.Model(this),
		model: this,
		where: make([]Where, 0),
	}
}

// Updater returns an Updater that you can update records with.
func (this *AIProxyModel) Updater(db *gorm.DB) Updater {
	return &updater{
		db:      db.Model(this),
		model:   this,
		where:   nil,
		updates: make(map[string]any),
	}
}

// Deleter returns a Deleter that you can delete records with.
func (this *AIProxyModel) Deleter(db *gorm.DB) Deleter {
	return &deleter{
		db:    db.Model(this),
		model: this,
		where: make([]Where, 0),
	}
}

// FieldName returns the Field interface{} for the field ai_proxy_model.name
func (list AIProxyModelList) FieldName() Field { return field{name: "name"} }

// FieldDesc returns the Field interface{} for the field ai_proxy_model.desc
func (list AIProxyModelList) FieldDesc() Field { return field{name: "desc"} }

// FieldType returns the Field interface{} for the field ai_proxy_model.type
func (list AIProxyModelList) FieldType() Field { return field{name: "type"} }

// FieldProviderID returns the Field interface{} for the field ai_proxy_model.provider_id
func (list AIProxyModelList) FieldProviderID() Field { return field{name: "provider_id"} }

// FieldAPIKey returns the Field interface{} for the field ai_proxy_model.api_key
func (list AIProxyModelList) FieldAPIKey() Field { return field{name: "api_key"} }

// FieldMetadata returns the Field interface{} for the field ai_proxy_model.metadata
func (list AIProxyModelList) FieldMetadata() Field { return field{name: "metadata"} }

// FieldBaseModelList returns a slice for the field BaseModel

func (list AIProxyModelList) FieldBaseModelList() BaseModelList {
	var results BaseModelList
	for _, v := range list {
		results = append(results, &v.BaseModel)
	}
	return results
}

// FieldNameList returns a slice for the field Name

func (list AIProxyModelList) FieldNameList() []string {
	var results []string
	for _, v := range list {
		results = append(results, v.Name)
	}
	return results
}

// FieldDescList returns a slice for the field Desc

func (list AIProxyModelList) FieldDescList() []string {
	var results []string
	for _, v := range list {
		results = append(results, v.Desc)
	}
	return results
}

// FieldTypeList returns a slice for the field Type

func (list AIProxyModelList) FieldTypeList() []string {
	var results []string
	for _, v := range list {
		results = append(results, v.Type)
	}
	return results
}

// FieldProviderIDList returns a slice for the field ProviderID

func (list AIProxyModelList) FieldProviderIDList() []string {
	var results []string
	for _, v := range list {
		results = append(results, v.ProviderID)
	}
	return results
}

// FieldAPIKeyList returns a slice for the field APIKey

func (list AIProxyModelList) FieldAPIKeyList() []string {
	var results []string
	for _, v := range list {
		results = append(results, v.APIKey)
	}
	return results
}

// FieldMetadataList returns a slice for the field Metadata

func (list AIProxyModelList) FieldMetadataList() []Metadata {
	var results []Metadata
	for _, v := range list {
		results = append(results, v.Metadata)
	}
	return results
}

// Pager returns a Pager that you can query records by paging with.
func (list *AIProxyModelList) Pager(db *gorm.DB) Pager {
	return &pager{
		db:    db,
		list:  list,
		where: nil,
	}
}
