// Copyright (c) 2021 Terminus, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by erda-cli. DO NOT EDIT.
// Source: bin/erda-cli gorm gen -f .erda/ai-proxy/migrations/ai-proxy/20230823-ai-proxy.sql -o internal/apps/ai-proxy/models

package models

import (
	"time"

	"github.com/erda-project/erda-infra/providers/mysql/v2/plugins/fields"
)

var (
	_ time.Time
	_ fields.UUID
)

// AIProxyPrompt is the table ai_proxy_prompt
type AIProxyPrompt struct {
	BaseModel
	Name     string   `gorm:"column:name;type:varchar(191)" json:"name" yaml:"name"`
	Desc     string   `gorm:"column:desc;type:varchar(1024)" json:"desc" yaml:"desc"`
	ClientID string   `gorm:"column:client_id;type:char(36)" json:"clientID" yaml:"clientID"`
	Messages Messages `gorm:"column:messages;type:longtext" json:"messages" yaml:"messages"`
	Metadata Metadata `gorm:"column:metadata;type:mediumtext" json:"metadata" yaml:"metadata"`
}

// TableName returns the table name ai_proxy_prompt
func (AIProxyPrompt) TableName() string { return "ai_proxy_prompt" }

type AIProxyPromptList []*AIProxyPrompt

// TableName returns the table name ai_proxy_prompt
func (AIProxyPromptList) TableName() string { return "ai_proxy_prompt" }
