// Copyright (c) 2021 Terminus, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by erda-cli. DO NOT EDIT.
// Source: bin/erda-cli gorm gen -f .erda/ai-proxy/migrations/ai-proxy/20230823-ai-proxy.sql -o internal/apps/ai-proxy/models

package models

import (
	"time"

	"gorm.io/gorm"
)

var (
	_ time.Time
)

var (
	_ CRUDer = (*AIProxyModelProvider)(nil)
	_ Lister = (*AIProxyModelProviderList)(nil)
)

// FieldBaseModel returns the Field interface{} for the field ai_proxy_model_provider.id
func (this AIProxyModelProvider) FieldBaseModel() Field { return field{name: "id"} }

// FieldName returns the Field interface{} for the field ai_proxy_model_provider.name
func (this AIProxyModelProvider) FieldName() Field { return field{name: "name"} }

// FieldDesc returns the Field interface{} for the field ai_proxy_model_provider.desc
func (this AIProxyModelProvider) FieldDesc() Field { return field{name: "desc"} }

// FieldType returns the Field interface{} for the field ai_proxy_model_provider.type
func (this AIProxyModelProvider) FieldType() Field { return field{name: "type"} }

// FieldAPIKey returns the Field interface{} for the field ai_proxy_model_provider.api_key
func (this AIProxyModelProvider) FieldAPIKey() Field { return field{name: "api_key"} }

// FieldMetadata returns the Field interface{} for the field ai_proxy_model_provider.metadata
func (this AIProxyModelProvider) FieldMetadata() Field { return field{name: "metadata"} }

// Creator returns a Creator interface that you can create record with.
func (this *AIProxyModelProvider) Creator(db *gorm.DB) Creator {
	return &creator{db: db, model: this}
}

// Retriever returns a Retriever that you can select one record with.
func (this *AIProxyModelProvider) Retriever(db *gorm.DB) Retriever {
	return &retriever{
		db:    db.Model(this),
		model: this,
		where: make([]Where, 0),
	}
}

// Updater returns an Updater that you can update records with.
func (this *AIProxyModelProvider) Updater(db *gorm.DB) Updater {
	return &updater{
		db:      db.Model(this),
		model:   this,
		where:   nil,
		updates: make(map[string]any),
	}
}

// Deleter returns a Deleter that you can delete records with.
func (this *AIProxyModelProvider) Deleter(db *gorm.DB) Deleter {
	return &deleter{
		db:    db.Model(this),
		model: this,
		where: make([]Where, 0),
	}
}

// FieldName returns the Field interface{} for the field ai_proxy_model_provider.name
func (list AIProxyModelProviderList) FieldName() Field { return field{name: "name"} }

// FieldDesc returns the Field interface{} for the field ai_proxy_model_provider.desc
func (list AIProxyModelProviderList) FieldDesc() Field { return field{name: "desc"} }

// FieldType returns the Field interface{} for the field ai_proxy_model_provider.type
func (list AIProxyModelProviderList) FieldType() Field { return field{name: "type"} }

// FieldAPIKey returns the Field interface{} for the field ai_proxy_model_provider.api_key
func (list AIProxyModelProviderList) FieldAPIKey() Field { return field{name: "api_key"} }

// FieldMetadata returns the Field interface{} for the field ai_proxy_model_provider.metadata
func (list AIProxyModelProviderList) FieldMetadata() Field { return field{name: "metadata"} }

// FieldBaseModelList returns a slice for the field BaseModel

func (list AIProxyModelProviderList) FieldBaseModelList() BaseModelList {
	var results BaseModelList
	for _, v := range list {
		results = append(results, &v.BaseModel)
	}
	return results
}

// FieldNameList returns a slice for the field Name

func (list AIProxyModelProviderList) FieldNameList() []string {
	var results []string
	for _, v := range list {
		results = append(results, v.Name)
	}
	return results
}

// FieldDescList returns a slice for the field Desc

func (list AIProxyModelProviderList) FieldDescList() []string {
	var results []string
	for _, v := range list {
		results = append(results, v.Desc)
	}
	return results
}

// FieldTypeList returns a slice for the field Type

func (list AIProxyModelProviderList) FieldTypeList() []string {
	var results []string
	for _, v := range list {
		results = append(results, v.Type)
	}
	return results
}

// FieldAPIKeyList returns a slice for the field APIKey

func (list AIProxyModelProviderList) FieldAPIKeyList() []string {
	var results []string
	for _, v := range list {
		results = append(results, v.APIKey)
	}
	return results
}

// FieldMetadataList returns a slice for the field Metadata

func (list AIProxyModelProviderList) FieldMetadataList() []Metadata {
	var results []Metadata
	for _, v := range list {
		results = append(results, v.Metadata)
	}
	return results
}

// Pager returns a Pager that you can query records by paging with.
func (list *AIProxyModelProviderList) Pager(db *gorm.DB) Pager {
	return &pager{
		db:    db,
		list:  list,
		where: nil,
	}
}
