# SQL 句型启用禁用清单
- name: AllowedStmtLinter
  meta:
    - stmtType: CreateDatabaseStmt
      forbidden: true
    - stmtType: AlterDatabaseStmt
      forbidden: true
    - stmtType: DropDatabaseStmt
      forbidden: true
    - stmtType: DropUserStmt
      forbidden: true
    - stmtType: CreateTableStmt
    - stmtType: DropTableStmt
      forbidden: true
    - stmtType: DropSequenceStmt
      forbidden: true
    - stmtType: RenameTableStmt
      forbidden: true
    - stmtType: CreateViewStmt
      forbidden: true
    - stmtType: CreateSequenceStmt
      forbidden: true
    - stmtType: CreateIndexStmt
    - stmtType: DropIndexStmt
    - stmtType: LockTablesStmt
      forbidden: true
    - stmtType: UnlockTablesStmt
      forbidden: true
    - stmtType: CleanupTableLockStmt
      forbidden: true
    - stmtType: RepairTableStmt
      forbidden: true
    - stmtType: TruncateTableStmt
      forbidden: true
    - stmtType: RecoverTableStmt
      forbidden: true
    - stmtType: FlashBackTableStmt
      forbidden: true
    - stmtType: AlterTableStmt
    - stmtType: AlterTableStmt.AlterTableOption
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableAddColumns
    - stmtType: AlterTableStmt.AlterTableAddConstraint
    - stmtType: AlterTableStmt.AlterTableDropColumn
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableDropPrimaryKey
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableDropIndex
    - stmtType: AlterTableStmt.AlterTableDropForeignKey
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableModifyColumn
    - stmtType: AlterTableStmt.AlterTableChangeColumn
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableRenameColumn
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableRenameTable
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableAlterColumn
    - stmtType: AlterTableStmt.AlterTableLock
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableAlgorithm
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableRenameIndex
    - stmtType: AlterTableStmt.AlterTableForce
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableAddPartitions
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableCoalescePartitions
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableDropPartition
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableTruncatePartition
      forbidden: true
    - stmtType: AlterTableStmt.AlterTablePartition
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableEnableKeys
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableDisableKeys
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableRemovePartitioning
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableWithValidation
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableWithoutValidation
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableSecondaryLoad
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableSecondaryUnload
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableRebuildPartition
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableReorganizePartition
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableCheckPartitions
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableExchangePartition
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableOptimizePartition
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableRepairPartition
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableImportPartitionTablespace
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableDiscardPartitionTablespace
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableAlterCheck
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableDropCheck
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableImportTablespace
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableDiscardTablespace
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableIndexInvisible
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableOrderByColumns
      forbidden: true
    - stmtType: AlterTableStmt.AlterTableSetTiFlashReplica
      forbidden: true
    - stmtType: SelectStmt
    - stmtType: UnionStmt
    - stmtType: LoadDataStmt
      forbidden: true
    - stmtType: InsertStmt
    - stmtType: DeleteStmt
    - stmtType: UpdateStmt
    - stmtType: ShowStmt
    - stmtType: SplitRegionStmt
      forbidden: true

# 布尔值命名与类型校验
- name: BooleanFieldLinter

# 必须设置表 character set
# 可以用 NecessaryTableOptionLinter 替代
- name: CharsetLinter
  meta:
    tableOptionCharset:
      utf8: true
      utf8mb4: true

# 列命名校验
- name: ColumnNameLinter
  meta:
    patterns:
      - "^[0-9a-z_]{1,64}$"

# id 字段类型校验
- name: ColumnTypeLinter
  alias: "字段类型校验: id 应当为 varchar(36) 或 char(36)"
  meta:
    columnName: id
    types:
      - type: varchar
        flen: 36
      - type: char
        flen: 36

# org_name 字段类型校验
- name: ColumnTypeLinter
  alias: "字段类型校验: org_name 应当为 varchar(50)"
  switch: off
  meta:
    columnName: org_name
    types:
      - type: varchar
        flen: 50

# created_at 类型校验
- name: ColumnTypeLinter
  alias: "字段类型校验: created_at 应当为 datetime 类型"
  meta:
    columnName: created_at
    types:
      - type: datetime

# updated_at 类型校验
- name: ColumnTypeLinter
  alias: "字段类型校验: updated_at 应当为 datetime 类型"
  meta:
    columnName: updated_at
    types:
      - type: datetime

# creator_id 字段类型校验
- name: ColumnTypeLinter
  alias: "字段类型校验: creator_id 应当为 varchar(255)"
  meta:
    columnName: creator_id
    types:
      - type: varchar
        flen: 255

# updater_id 字段类型校验
- name: ColumnTypeLinter
  alias: "字段类型校验: updater_id 应当为 varchar(255)"
  meta:
    columnName: updater_id
    types:
      - type: varchar
        flen: 255

# complete insert 校验
- name: CompleteInsertLinter

# created_at 字段默认值校验
- name: DefaultValueLinter
  alias: "默认值校验: created_at 默认值为 CURRENT_TIMESTAMP"
  meta:
    columnName: created_at
    defaultValue: CURRENT_TIMESTAMP

# updated 默认值校验
- name: DefaultValueLinter
  alias: "默认值校验: updated_at 默认值为 CURRENT_TIMESTAMP"
  meta:
    columnName: updated_at
    defaultValue: CURRENT_TIMESTAMP

# explicit_collation 校验
- name: ExplicitCollationLinter

# 小数类型校验
- name: FloatDoubleLinter

# 外键校验
- name: ForeignKeyLinter

# 索引长度校验
- name: IndexLengthLinter

# 索引名称校验
- name: IndexNameLinter
  meta:
    indexPattern: "^idx_.*"
    uniqPattern: "^uk_.*"

# MySQL 关键字 保留字检查: 不能将关键字作为表名或字段名
- name: KeywordsLinter
  meta:
    "ALL": true
    "ALTER": true
    "AND": true
    "ANY": true
    "AS": true
    "ENABLE": true
    "DISABLE": true
    "ASC": true
    "BETWEEN": true
    "BY": true
    "CASE": true
    "CAST": true
    "CHECK": true
    "CONSTRAINT": true
    "CREATE": true
    "DATABASE": true
    "DEFAULT": true
    "COLUMN": true
    "TABLESPACE": true
    "PROCEDURE": true
    "FUNCTION": true
    "DELETE": true
    "DESC": false
    "DISTINCT": true
    "DROP": true
    "ELSE": true
    "EXPLAIN": true
    "EXCEPT": true
    "END": true
    "ESCAPE": true
    "EXISTS": true
    "FOR": true
    "FOREIGN": true
    "FROM": true
    "FULL": true
    "GROUP": true
    "HAVING": true
    "IN": true
    "INDEX": true
    "INNER": true
    "INSERT": true
    "INTERSECT": true
    "INTERVAL": true
    "INTO": true
    "IS": true
    "JOIN": true
    "KEY": true
    "LEFT": true
    "LIKE": true
    "LOCK": true
    "MINUS": true
    "NOT": true
    "NULL": true
    "ON": true
    "OR": true
    "ORDER": true
    "OUTER": true
    "PRIMARY": true
    "REFERENCES": true
    "RIGHT": true
    "SCHEMA": true
    "SELECT": true
    "SET": true
    "SOME": true
    "TABLE": true
    "THEN": true
    "TRUNCATE": true
    "UNION": true
    "UNIQUE": true
    "UPDATE": true
    "VALUES": true
    "VIEW": true
    "SEQUENCE": true
    "TRIGGER": true
    "USER": true
    "WHEN": true
    "WHERE": true
    "XOR": true
    "OVER": true
    "TO": true
    "USE": true
    "REPLACE": true
    "COMMENT": true
    "COMPUTE": true
    "WITH": true
    "GRANT": true
    "REVOKE": true
    "WHILE": true
    "DO": true
    "DECLARE": true
    "LOOP": true
    "LEAVE": true
    "ITERATE": true
    "REPEAT": true
    "UNTIL": true
    "OPEN": true
    "CLOSE": true
    "CURSOR": true
    "FETCH": true
    "OUT": true
    "INOUT": true
    "LIMIT": true
    "DUAL": true
    "FALSE": true
    "IF": true
    "KILL": true
    "TRUE": true
    "BINARY": true
    "SHOW": true
    "CACHE": true
    "ANALYZE": true
    "OPTIMIZE": true
    "ROW": true
    "BEGIN": true
    "DIV": true
    "MERGE": true
    "PARTITION": true
    "CONTINUE": true
    "UNDO": true
    "SQLSTATE": true
    "CONDITION": true
    "MOD": true
    "CONTAINS": true
    "RLIKE": true
    "FULLTEXT": true

# 显式插入时间校验
- name: ManualTimeSetterLinter
  alias: "禁止显示插入 created_at 的值"
  meta:
    columnName: created_at

# 显式插入时间校验
- name: ManualTimeSetterLinter
  alias: "禁止显示插入 updated_at 的值"
  meta:
    columnName: updated_at

# 必要字段 id
- name: NecessaryColumnLinter
  alias: 必要字段.id
  meta:
    columnName:
      - id

# 必要字段 created_at
- name: NecessaryColumnLinter
  alias: 必要字段.created_at
  meta:
    columnName:
      - created_at

# 必要字段 updated_at
- name: NecessaryColumnLinter
  alias: 必要字段.updated_at
  meta:
    columnName:
      - updated_at

# 必要字段 org_name
- name: NecessaryColumnLinter
  alias: 必要字段.org_name
  meta:
    columnName:
      - org_name

# 必要字段 org_id
- name: NecessaryColumnLinter
  alias: 必要字段.org_id
  meta:
    columnName:
      - org_id

# 必要字段 deleted_at 或 soft_deleted_at
- name: NecessaryColumnLinter
  alias: 必要字段.deleted_at或soft_deleted_at
  meta:
    columnName:
      - deleted_at
      - soft_deleted_at

# 必要列选项: comment
- name: NecessaryColumnOptionLinter
  alias: "列应当有注释"
  meta:
    columnOptionType:
      - "ColumnOptionComment"

# not null 校验: 所有字段应当显示定义为 not null
- name: NecessaryColumnOptionLinter
  alias: "列要么是主键要么是 not null 的"
  meta:
    columnOptionType:
      - "ColumnOptionNotNull"
      - "ColumnOptionPrimaryKey"

# updated_at 跟踪更新时间校验
- name: NecessaryColumnOptionLinter
  alias: "updated_at 应当自动跟踪更新时间"
  switch: on
  meta:
    columnName: "updated_at"
    columnOptionType:
      - "ColumnOptionOnUpdate"

# 必要的 tableOption：所有表应当有表注释
- name: NecessaryTableOptionLinter
  alias: "必要的 tableOption: 表应当有 comment"
  meta:
    key: TableOptionComment

# 必要的 tableOption: 表应当注明 charset
- name: NecessaryTableOptionLinter
  alias: "必要的 tableOption: 表应当注明 charset 为 utf8 或 utf8mb4"
  meta:
    key: TableOptionCharset
    values:
      - "utf8"
      - "utf8mb4"

# id 必须是主键, 主键必须是 id
- name: PrimaryKeyLinter
  meta:
    columnName: id

# 文件名称校验
- name: ScriptNameLinter
  meta:
    patterns:
      - ^202([0-9]{5})-.+(\.sql|\.py)$

# 文件 checksum 校验 锁定列表中的文件 checksum 以防篡改
# 执行 select concat('- scriptName: ', filename, '\n', '  checksum: ', checksum) record from schema_migration_history where created_at < '2022-07-01 00:00:00';
# 获取要锁定修改的 scriptName 及其对应的 checksum
- name: ScriptChecksumLinter
  switch: off

# 表名称校验 表名应当以 erda 开头
- name: TableNameLinter
  alias: "TableNameLinter: 以 erda_ 开头仅包含小写英文字母数字下划线"
  meta:
    patterns:
      - "^erda_[a-z0-9_]{1,59}"
      - "^tb_gateway_[a-z0-9_]{1,59}"

# varchar 长度校验
- name: VarcharLengthLinter
