CREATE TABLE `tb_gateway_credential`
(
    `id`                      VARCHAR(36)   NOT NULL DEFAULT '' COMMENT '唯一id',
    `create_time`             DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`             DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_at`              DATETIME      NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '删除时间',
    `is_deleted`              VARCHAR(1)    NOT NULL DEFAULT 'N' COMMENT '逻辑删除',
    `consumer_id`             VARCHAR(128)  NOT NULL DEFAULT '' COMMENT 'consumer id',
    `consumer_name`           VARCHAR(128)  NOT NULL DEFAULT '' COMMENT 'consumer name',
    `plugin_name`             VARCHAR(128)  NOT NULL DEFAULT '' COMMENT 'plugin name',
    `org_name`                VARCHAR(50)  NOT NULL DEFAULT '' COMMENT '企业名称',
    `org_id`                  VARCHAR(32)   NOT NULL COMMENT '企业id',
    `project_id`              VARCHAR(32)   NOT NULL COMMENT '项目id',
    `env`                     VARCHAR(32)   NOT NULL COMMENT '环境',
    `az`                      VARCHAR(32)   NOT NULL COMMENT '集群名',
    `auth_key`                VARCHAR(128)  NOT NULL DEFAULT '' COMMENT 'auth key for key-auth(credential)、basic-auth and hmac-auth',
    `secret`                  VARCHAR(128)  NOT NULL DEFAULT '' COMMENT 'secret for sign-auth、hmac-auth',
    `username`                VARCHAR(128)  NOT NULL DEFAULT '' COMMENT 'user name for hmac-auth',
    `issuer`                  VARCHAR(128)  NOT NULL DEFAULT '' COMMENT 'issuer for JWT-AUTH',
    `jwks`                    VARCHAR(4096) NOT NULL DEFAULT '' COMMENT 'jwks for JWT-AUTH',
    `from_params`             VARCHAR(1024) NOT NULL DEFAULT 'access_token' COMMENT 'from_params for JWT-AUTH',
    `from_cookies`            VARCHAR(4096) NOT NULL DEFAULT '-' COMMENT 'from_cookies for JWT-AUTH',
    `keep_token`              VARCHAR(1)    NOT NULL DEFAULT 'Y' COMMENT 'keep_token for JWT-AUTH',
    `clock_skew_seconds`      VARCHAR(32)   NOT NULL DEFAULT '60' COMMENT 'clock_skew_seconds for JWT-AUTH',
    `oauth2_redirect_url`     VARCHAR(1024) NOT NULL DEFAULT '' COMMENT 'oauth2 v1 转发 url',
    `oauth2_v2_redirect_urls` VARCHAR(4096) NOT NULL DEFAULT '' COMMENT 'oauth2 v2 转发 urls',
    `oauth2_name`             VARCHAR(128)  NOT NULL DEFAULT '' COMMENT 'OAuth2 名称',
    `oauth2_client_id`        VARCHAR(128)  NOT NULL DEFAULT '' COMMENT 'OAuth2 客户端 ID',
    `oauth2_client_secret`    VARCHAR(128)  NOT NULL DEFAULT '' COMMENT 'OAuth2 客户端 Secret',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='网关 API 调用方授权信息';