- elasticsearch_store_size:
    title: "索引存储量"
    metric_names: "elasticsearch_indices"
    type: "terminus-elasticsearch"
    order: 1
    defines:
      max.store_size_in_bytes:
        label: ""
        unit: "B"
        unit_type: "CAPACITY"
        axis_index: 0
        chart_type: "line"
    parameters:
      group:
        - "node_name"

