- redis_aof_current_size:
    title: "AOF文件大小"
    metric_names: "redis"
    type: "redis"
    order: 7
    defines:
      max.aof_current_size:
        label: ""
        unit: "B"
        unit_type: "CAPACITY"
        axis_index: 0
        chart_type: "line"
    parameters:
      group:
        - "server"

