- scope: "project"
  name: "项目 > 新建应用"
  resource: "UI"
  action: "addApp"
  role: "Owner,Lead"
- scope: "project"
  name: "项目 > 编辑项目"
  resource: "UI"
  action: "editProject"
  role: "Owner,Lead"
- scope: "project"
  name: "项目 > 删除项目"
  resource: "UI"
  action: "deleteProject"
  role: "Owner,Lead"
- scope: "project"
  name: "项目 > 服务目录 > 添加项目服务"
  resource: "UI.service"
  action: "addProjectService"
  role: "Owner,Lead"
- scope: "project"
  name: "项目 > 服务目录 > 查看"
  resource: "UI.service"
  action: "viewService"
  role: "Owner,Lead,PM,PD,Dev,QA,Support,Ops"
- scope: "project"
  name: "项目 > 迭代 > 查看"
  resource: "UI.iteration"
  action: "read"
  role: "Owner,Lead,PM,PD,Dev,QA,Support,Ops,Guest"
- scope: "project"
  name: "项目 > 迭代 > 操作（新建/编辑/删除）"
  resource: "UI.iteration"
  action: "operation"
  role: "Owner,PM,Lead,PD"
- scope: "project"
  name: "项目 > 迭代 > 归档/取消归档"
  resource: "UI.iteration"
  action: "handleFiled"
  role: "Owner,PM"
- scope: "project"
  name: "项目 > 需求 > 查看"
  resource: "UI.requirement"
  action: "read"
  role: "Owner,Lead,PM,PD,Dev,QA,Support,Ops"
- scope: "project"
  name: "项目 > 需求 > 批量操作"
  resource: "UI.requirement"
  action: "batchOperation"
  role: "Owner,Lead,PM,PD,Dev,QA"
- scope: "project"
  name: "项目 > 需求 > 新建"
  resource: "UI.requirement"
  action: "create"
  role: "Owner,Lead,PM,PD,Dev,QA"
- scope: "project"
  name: "项目 > 需求 > 编辑"
  resource: "UI.requirement"
  action: "edit"
  role: "Owner,PM,PD,Lead,Dev,QA"
  resource_role: "Creator,Assignee"
- scope: "project"
  name: "项目 > 需求 > 删除"
  resource: "UI.requirement"
  action: "delete"
  role: "Owner,PM,PD"
  resource_role: "Creator"
- scope: "project"
  name: "项目 > 需求 > 状态变更"
  resource: "UI.requirement"
  action: "updateStatus"
  role: "Owner,Lead,PM,PD,Dev,QA"
  resource_role: "Creator,Assignee"
- scope: "project"
  name: "项目 > 需求 > 导出"
  resource: "UI.requirement"
  action: "export"
  role: "Owner,Lead,PM,PD"
- scope: "project"
  name: "项目 > 需求 > 切换事项类型"
  resource: "UI.requirement"
  action: "switchType"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > 需求 > 导入"
  resource: "UI.requirement"
  action: "import"
  role: "Owner,Lead,PM,PD,Dev,QA"
- scope: "project"
  name: "项目 > 里程碑 > 查看"
  resource: "UI.epic"
  action: "read"
  role: "Owner,Lead,PM,PD,Dev,QA,Support,Ops"
- scope: "project"
  name: "项目 > 里程碑 > 新建"
  resource: "UI.epic"
  action: "create"
  role: "Owner,Lead,PM,PD,Dev,QA"
- scope: "project"
  name: "项目 > 里程碑 > 编辑"
  resource: "UI.epic"
  action: "edit"
  role: "Owner,PM,PD,Lead,Dev,QA"
  resource_role: "Creator,Assignee"
- scope: "project"
  name: "项目 > 里程碑 > 删除"
  resource: "UI.epic"
  action: "delete"
  role: "Owner,PM,PD"
  resource_role: "Creator"
- scope: "project"
  name: "项目 > 里程碑 > 状态变更"
  resource: "UI.epic"
  action: "updateStatus"
  role: "Owner,Lead,PM,PD,Dev,QA"
  resource_role: "Creator,Assignee"
- scope: "project"
  name: "项目 > 里程碑 > 导出"
  resource: "UI.epic"
  action: "export"
  role: "Owner,Lead,PM,PD"
- scope: "project"
  name: "项目 > 任务 > 查看"
  resource: "UI.task"
  action: "read"
  role: "Owner,Lead,PM,PD,Dev,QA,Support,Ops"
- scope: "project"
  name: "项目 > 任务 > 批量操作"
  resource: "UI.task"
  action: "batchOperation"
  role: "Owner,Lead,PM,PD,Dev,QA"
- scope: "project"
  name: "项目 > 任务 > 新建"
  resource: "UI.task"
  action: "create"
  role: "Owner,Lead,PM,PD,Dev,QA"
- scope: "project"
  name: "项目 > 任务 > 编辑"
  resource: "UI.task"
  action: "edit"
  role: "Owner,Lead,QA,PM,PD,Dev"
  resource_role: "Creator,Assignee"
- scope: "project"
  name: "项目 > 任务 > 删除"
  resource: "UI.task"
  action: "delete"
  role: "Owner,Lead"
  resource_role: "Creator"
- scope: "project"
  name: "项目 > 任务 > 状态修改"
  resource: "UI.task"
  action: "updateStatus"
  role: "Owner,Lead,Dev"
  resource_role: "Creator,Assignee"
- scope: "project"
  name: "项目 > 任务 > 导出"
  resource: "UI.task"
  action: "export"
  role: "Owner,Lead,PM,PD,Dev"
- scope: "project"
  name: "项目 > 任务 > 切换事项类型"
  resource: "UI.task"
  action: "switchType"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > 任务 > 导入"
  resource: "UI.task"
  action: "import"
  role: "Owner,Lead,PM,PD,Dev,QA"
- scope: "project"
  name: "项目 > 缺陷 > 查看"
  resource: "UI.bug"
  action: "read"
  role: "Owner,Lead,PM,PD,Dev,QA,Support,Ops"
- scope: "project"
  name: "项目 > 缺陷 > 删除"
  resource: "UI.bug"
  action: "delete"
  role: "Owner,Lead,PM,QA"
  resource_role: "Creator"
- scope: "project"
  name: "项目 > 缺陷 > 导出"
  resource: "UI.bug"
  action: "export"
  role: "Owner,Lead,PM,PD,QA"
- scope: "project"
  name: "项目 > 缺陷 > 批量操作"
  resource: "UI.bug"
  action: "batchOperation"
  role: "Owner,Lead,PM,PD,Dev,QA"
- scope: "project"
  name: "项目 > 缺陷 > 创建"
  resource: "UI.bug"
  action: "create"
  role: "Owner,Lead,PM,PD,Dev,QA"
- scope: "project"
  name: "项目 > 缺陷 > 编辑"
  resource: "UI.bug"
  action: "edit"
  role: "Owner,PM,QA,Lead,PD,Dev"
  resource_role: "Creator,Assignee"
- scope: "project"
  name: "项目 > 缺陷 > 状态变更"
  resource: "UI.bug"
  action: "updateStatus"
  role: "Owner,Lead,PM,PD,Dev,QA"
  resource_role: "Creator,Assignee"
- scope: "project"
  name: "项目 > 缺陷 > 关闭"
  resource: "UI.bug"
  action: "closeBug"
  role: "Owner,QA"
  resource_role: "Creator"
- scope: "project"
  name: "项目 > 缺陷 > 切换事项类型"
  resource: "UI.bug"
  action: "switchType"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > 缺陷 > 导入"
  resource: "UI.bug"
  action: "import"
  role: "Owner,Lead,PM,PD,Dev,QA"
- scope: "project"
  name: "项目 > 项目成员管理 > 添加"
  resource: "UI.member"
  action: "addProjectMember"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > 项目成员管理 > 编辑"
  resource: "UI.member"
  action: "editProjectMember"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > 项目成员管理 > 删除"
  resource: "UI.member"
  action: "removeProjectMember"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > 项目成员管理 > 授权"
  resource: "UI.member"
  action: "showAuthorize"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > 项目设置 > 分支规则 > 操作（增删改）"
  resource: "UI.setting.branchRule"
  action: "operation"
  role: "Owner,Lead"
- scope: "project"
  name: "项目 > 项目设置 > 扫描规则 > 操作（增删改）"
  resource: "UI.setting.scanRule"
  action: "operation"
  role: "Owner,Lead"
- scope: "project"
  name: "项目 > 项目设置 > 工作流管理 > 操作（增删改）"
  resource: "UI.setting.customWorkflow"
  action: "operation"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > 项目设置 > 封网 > 申请解封"
  resource: "UI.setting.blockNetwork"
  action: "applyUnblock"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > 项目设置 > 查看"
  resource: "UI.setting"
  action: "viewSetting"
  role: "Owner,Lead,PM,PD,Dev,QA,Support,Ops"
- scope: "project"
  name: "项目 > 工单 > 查看"
  resource: "UI.ticket"
  action: "read"
  role: "Owner,Lead,PM,PD,Dev,QA,Support,Ops,Reporter,Guest"
- scope: "project"
  name: "项目 > 工单 > 创建"
  resource: "UI.ticket"
  action: "create"
  role: "Owner,Lead,PM,PD,Dev,QA,Reporter,Guest"
- scope: "project"
  name: "项目 > 工单 > 编辑"
  resource: "UI.ticket"
  action: "edit"
  role: "Owner,Lead,PM,PD,Dev,QA"
  resource_role: "Creator,Assignee"
- scope: "project"
  name: "项目 > 工单 > 状态变更"
  resource: "UI.ticket"
  action: "updateStatus"
  role: "Owner,Lead,PM,PD,Dev,QA"
  resource_role: "Assignee"
- scope: "project"
  name: "项目 > 工单 > 删除"
  resource: "UI.ticket"
  action: "delete"
  role: "Owner,Lead,PM,PD,Dev,QA"
  resource_role: "Creator,Assignee"
- scope: "project"
  name: "项目 > API 管理 > API 集市 > 查看"
  resource: "UI.apiManage.apiMarket"
  action: "read"
  role: "Owner,Lead,PM,PD,Dev,QA,Support,Ops"
- scope: "project"
  name: "项目 > API 管理 > API 集市 > 编辑资源"
  resource: "UI.apiManage.apiMarket"
  action: "edit"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > API 管理 > API 集市 > 删除资源"
  resource: "UI.apiManage.apiMarket"
  action: "delete"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > API 管理 > API 集市 > 公开"
  resource: "UI.apiManage.apiMarket"
  action: "publicAsset"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > API 管理 > API 集市 > 添加版本"
  resource: "UI.apiManage.apiMarket"
  action: "addVersion"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > API 管理 > API 集市 > 删除版本"
  resource: "UI.apiManage.apiMarket"
  action: "deleteVersion"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > API 管理 > API 集市 > 关联项目/应用"
  resource: "UI.apiManage.apiMarket"
  action: "relatedProjectOrApp"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > API 管理 > API 集市 > 关联实例"
  resource: "UI.apiManage.apiMarket"
  action: "relatedInstance"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > API 管理 > 访问管理 > 查看"
  resource: "UI.apiManage.accessManage"
  action: "read"
  role: "Owner,Lead,PM,PD,Dev,QA,Support,Ops"
- scope: "project"
  name: "项目 > API 管理 > 访问管理 > 编辑"
  resource: "UI.apiManage.accessManage"
  action: "edit"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > API 管理 > 访问管理 > 删除"
  resource: "UI.apiManage.accessManage"
  action: "delete"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > API 管理 > 访问管理 > 审批"
  resource: "UI.apiManage.accessManage"
  action: "approve"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > 应用列表 > 查看"
  resource: "UI.appList"
  action: "viewAppList"
  role: "Owner,Lead,PM,PD,Dev,QA,Support,Ops,Guest"
- scope: "project"
  name: "项目 > 待办事项 > 查看"
  resource: "UI.backLog"
  action: "viewBackLog"
  role: "Owner,Lead,PM,PD,Dev,QA,Support,Ops,Guest"
- scope: "project"
  name: "项目 > 测试管理 > 查看"
  resource: "UI.testManage"
  action: "viewTest"
  role: "Owner,Lead,PM,PD,Dev,QA,Support,Ops"
- scope: "project"
  name: "项目 > 项目大盘 > 查看"
  resource: "UI.dashboard"
  action: "viewDashboard"
  role: "Owner,Lead,PM,PD,Dev,QA,Support,Ops"
- scope: "project"
  name: "项目 > 资源汇总 > 查看"
  resource: "UI.resource"
  action: "viewResource"
  role: "Owner,Lead,PM,PD,Dev,QA,Support,Ops"
- scope: "project"
  name: "项目 > 事项 > 查看"
  resource: "UI.issue"
  action: "viewIssue"
  role: "Owner,Lead,PM,PD,Dev,QA,Support,Ops,Guest"
- scope: "project"
  name: "项目 > 数据银行 > 数据源 > 查看"
  resource: "UI.dataBank.dataSource"
  action: "view"
  role: "Owner,Lead,PM,PD,Dev,QA,Ops"
- scope: "project"
  name: "项目 > 数据银行 > 配置单 > 查看"
  resource: "UI.dataBank.configData"
  action: "view"
  role: "Owner,Lead,PM,PD,Dev,QA,Ops"
- scope: "project"
  name: "项目 > 流水线 > 查看"
  resource: "UI.pipeline"
  action: "view"
  role: "Owner,Lead,PM"
- scope: "project"
  name: "项目 > 里程碑 > 查看"
  resource: "UI.milestone"
  action: "view"
  role: "Owner,Lead,PM,PD,Dev,QA,Ops,Support"
- scope: "project"
  name: "项目 > 微服务治理平台 > 成员管理 > 添加成员"
  resource: "UI.microService.member"
  action: "addProjectMember"
  role: "Owner,Lead"
- scope: "project"
  name: "项目 > 微服务治理平台 > 成员管理 > 编辑成员"
  resource: "UI.microService.member"
  action: "editProjectMember"
  role: "Owner,Lead"
- scope: "project"
  name: "项目 > 微服务治理平台 > 成员管理 > 删除成员"
  resource: "UI.microService.member"
  action: "removeProjectMember"
  role: "Owner,Lead"
- scope: "project"
  name: "项目 > 微服务治理平台 > 接入配置 > 创建 AccessKey"
  resource: "UI.microService.accessConfiguration"
  action: "createAccessKey"
  role: "Owner,Lead"
- scope: "project"
  name: "项目 > 微服务治理平台 > 接入配置 > 删除 AccessKey"
  resource: "UI.microService.accessConfiguration"
  action: "deleteAccessKey"
  role: "Owner,Lead"
- scope: "project"
  name: "项目 > 微服务治理平台 > 接入配置 > 查看 AccessKeySecret"
  resource: "UI.microService.accessConfiguration"
  action: "viewAccessKeySecret"
  role: "Owner,Lead"
