@url = http://localhost:7096

### tags tree
GET {{url}}/api/org/logs/tags/tree
User-ID: 1100
Org-ID: 1

### 企业 日志查询
GET {{url}}/api/org/logs/search
    ?start=1605677619077
    &end=1605764019077
    &size=10
    &debug=true
User-ID: 1100
Org-ID: 1

### 企业 日志统计
GET {{url}}/api/org/logs/statistic/histogram
    ?start=1605677619077
    &end=1605764019077
    &points=60
    &debug=true
User-ID: 1100
Org-ID: 1

### tags tree
GET {{url}}/api/addon/logs/tags/tree
User-ID: 1100
Org-ID: 1

### addon 日志查询
GET {{url}}/api/addon/lda635ef36610446698b18d46b53de02f/logs/search
    ?start=1605677619077
    &end=1605764019077
    &size=10
    &debug=true
    &clusterName=terminus-dev
User-ID: 1100
Org-ID: 1

### addon 日志统计
GET {{url}}/api/addon/lda635ef36610446698b18d46b53de02f/logs/statistic/histogram
    ?start=1605677619077
    &end=1605764019077
    &points=60
    &debug=true
    &clusterName=terminus-dev
User-ID: 1100
Org-ID: 1

