- name: "kubernetes组件实例内存异常"
  trigger: "alert"
  target: "dingding,ticket,email,mbox,webhook,dingtalk_work_notice"
  language: "zh-CN"
  formats:
    mem_usage_percent_avg: "percent:2"
    mem_usage_value: "size:byte"
    mem_limit_value: "size:byte"
    mem_allocation_value: "size:byte"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}}内存使用率告警】
  template: |
    【kubernetes组件内存使用率告警】

    Pod: {{pod_name}}

    Pod_Ip: {{pod_ip}}

    使用率: {{mem_usage_percent_avg}}

    使用: {{mem_usage_value}}

    限制: {{mem_limit_value}}

    分配: {{mem_allocation_value}}

    集群: {{cluster_name}}

    机器: {{host_ip}}

    容器ID: {{container_id}}

    组织名称: {{org_name}}

    告警级别: {{level}}

    时间: {{timestamp}}

    [查看记录]({{record_url}})

- name: "kubernetes组件实例内存异常"
  trigger: "alert"
  target: "sms"
  language: "zh-CN"
  formats:
    mem_usage_percent_avg: "percent:2"
    mem_usage_value: "size:byte"
    mem_limit_value: "size:byte"
    mem_allocation_value: "size:byte"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}}内存使用率告警】
  template: |
    {{cluster_name}}集群{{pod_name}}组件触发kubernetes组件实例内存使用率异常告警，组织名称: {{org_name}}，使用率: {{mem_usage_percent_avg}}，告警级别: {{level}}

- name: "kubernetes组件实例内存异常"
  trigger: "alert"
  target: "vms"
  language: "zh-CN"
  formats:
    mem_usage_percent_avg: "percent:2"
    mem_usage_value: "size:byte"
    mem_limit_value: "size:byte"
    mem_allocation_value: "size:byte"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}}内存使用率告警】
  template: |
    {{cluster_name}}集群{{pod_name}}组件触发kubernetes组件实例内存使用率异常告警，组织名称: {{org_name}}，使用率: {{mem_usage_percent_avg}}，告警级别: {{level}}

- name: "kubernetes组件实例内存异常"
  trigger: "recover"
  target: "dingding,ticket,email,mbox,webhook,dingtalk_work_notice"
  language: "zh-CN"
  formats:
    mem_usage_percent_avg: "percent:2"
    trigger_duration: "time:ms"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}}内存使用率恢复】
  template: |
    【kubernetes组件内存使用率恢复】

    Pod: {{pod_name}}

    Pod_Ip: {{pod_ip}}

    使用率: {{mem_usage_percent_avg}}

    集群: {{cluster_name}}

    机器: {{host_ip}}

    容器ID: {{container_id}}

    组织名称: {{org_name}}

    持续时间: {{trigger_duration}}

    恢复时间: {{timestamp}}

    [查看记录]({{record_url}})

- name: "kubernetes组件实例内存异常"
  trigger: "recover"
  target: "sms"
  language: "zh-CN"
  formats:
    mem_usage_percent_avg: "percent:2"
    trigger_duration: "time:ms"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}}内存使用率恢复】
  template: |
    {{cluster_name}}集群{{pod_name}}组件触发kubernetes组件实例内存使用率异常告警恢复，组织名称: {{org_name}}，使用率: {{mem_usage_percent_avg}}
- name: "kubernetes组件实例内存异常"
  trigger: "recover"
  target: "vms"
  language: "zh-CN"
  formats:
    mem_usage_percent_avg: "percent:2"
    trigger_duration: "time:ms"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}}内存使用率恢复】
  template: |
    {{cluster_name}}集群{{pod_name}}组件触发kubernetes组件实例内存使用率异常告警恢复，组织名称: {{org_name}}，使用率: {{mem_usage_percent_avg}}

- name: "Memory exception of Kubernetes component instance"
  trigger: "alert"
  target: "dingding,ticket,email,mbox,webhook"
  language: "en-US"
  formats:
    mem_usage_percent_avg: "percent:2"
    mem_usage_value: "size:byte"
    mem_limit_value: "size:byte"
    mem_allocation_value: "size:byte"
  title: |
    [Memory usage alarm of Kubernetes component {{pod_name}} of cluster {{cluster_name}}]
  template: |
    [Memory usage alarm of Kubernetes component]

    Pod: {{pod_name}}

    Pod_Ip: {{pod_ip}}

    Usage rate: {{mem_usage_percent_avg}}

    Usage: {{mem_usage_value}}

    Limit: {{mem_limit_value}}

    Allocation: {{mem_allocation_value}}

    Cluster: {{cluster_name}}

    Machine: {{host_ip}}

    Container ID: {{container_id}}

    Organization name: {{org_name}}

    Time: {{timestamp}}

    [View records]({{record_url}})

- name: "Memory exception of Kubernetes component instance"
  trigger: "alert"
  target: "sms"
  language: "en-US"
  formats:
    mem_usage_percent_avg: "percent:2"
    mem_usage_value: "size:byte"
    mem_limit_value: "size:byte"
    mem_allocation_value: "size:byte"
  title: |
    [Memory usage alarm of Kubernetes component {{pod_name}} of cluster {{cluster_name}}]
  template: |
    Memory usage exception alarm of Kubernetes component instance triggered by component {{pod_name}} of cluster {{cluster_name}}, organization name: {{org_name}}, usage: {{mem_usage_percent_avg}}

- name: "Memory exception of Kubernetes component instance"
  trigger: "alert"
  target: "vms"
  language: "en-US"
  formats:
    mem_usage_percent_avg: "percent:2"
    mem_usage_value: "size:byte"
    mem_limit_value: "size:byte"
    mem_allocation_value: "size:byte"
  title: |
    [Memory usage alarm of Kubernetes component {{pod_name}} of cluster {{cluster_name}}]
  template: |
    Memory usage exception alarm of Kubernetes component instance triggered by component {{pod_name}} of cluster {{cluster_name}}, organization name: {{org_name}}, usage: {{mem_usage_percent_avg}}

- name: "Memory exception recovery of Kubernetes component instance"
  trigger: "recover"
  target: "dingding,ticket,email,mbox,webhook"
  language: "en-US"
  formats:
    mem_usage_percent_avg: "percent:2"
    trigger_duration: "time:ms"
  title: |
    [Memory usage recovery of Kubernetes component {{pod_name}} of cluster {{cluster_name}}]
  template: |
    [Memory usage recovery of Kubernetes component]

    Pod: {{pod_name}}

    Pod_Ip: {{pod_ip}}

    Usage rate: {{mem_usage_percent_avg}}

    Cluster: {{cluster_name}}

    Machine: {{host_ip}}

    Container ID: {{container_id}}

    Organization name: {{org_name}}

    Duration: {{trigger_duration}}

    Recovery time: {{timestamp}}

    [View records]({{record_url}})

- name: "Memory exception recovery of Kubernetes component instance"
  trigger: "recover"
  target: "sms"
  language: "en-US"
  formats:
    mem_usage_percent_avg: "percent:2"
    trigger_duration: "time:ms"
  title: |
    [Memory usage recovery of Kubernetes component {{pod_name}} of cluster {{cluster_name}}]
  template: |
    Memory usage exception alarm recovery of Kubernetes component instance triggered by component {{pod_name}} of cluster {{cluster_name}}, organization name: {{org_name}}, usage: {{mem_usage_percent_avg}}
- name: "Memory exception recovery of Kubernetes component instance"
  trigger: "recover"
  target: "vms"
  language: "en-US"
  formats:
    mem_usage_percent_avg: "percent:2"
    trigger_duration: "time:ms"
  title: |
    [Memory usage recovery of Kubernetes component {{pod_name}} of cluster {{cluster_name}}]
  template: |
    Memory usage exception alarm recovery of Kubernetes component instance triggered by component {{pod_name}} of cluster {{cluster_name}}, organization name: {{org_name}}, usage: {{mem_usage_percent_avg}}
