http-server:
  addr: ":80"

openapi-ng:

openapi-interceptor-csrf:
  order: 0
  allow_empty_referer: true
  cookie_name: "OPENAPI-CSRF-TOKEN"
  cookie_max_age: "12h"
  token_lookup: "header:OPENAPI-CSRF-TOKEN"
openapi-interceptor-filter-client-header:
  order: 1
openapi-interceptor-auth:
  order: 500
openapi-interceptor-audit:
  order: 1000
openapi-services:

# erda-discover:
fixed-discover:
  urls:
    user-center: "http://localhost:8080"