### 应用资源排行
GET http://openapi.dev.terminus.io/api/projects/5/applications-resources
lang: zh-CN
org-id: 1
user-id: 2
cookie: taid=f9902540-58d3-11ec-85d9-c226b743fa5b; u_c_captain_hkci_local=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2dpbiIsInBhdGgiOiIvIiwidG9rZW5LZXkiOiI5ODcyOTg4YzhkODMyMzZmZDE3ZTVmZGU5MmE0MTI5YWI0MjgwMmVmMmI4YWMwZWY1M2QxMDJjZWU0MzIxYWJlIiwibmJmIjoxNjM5Mzc0MTk4LCJkb21haW4iOiJ0ZXJtaW51cy5pbyIsImlzcyI6ImRyYWNvIiwidGVuYW50SWQiOjEsImV4cGlyZV90aW1lIjo2MDQ4MDAsImV4cCI6MTYzOTk3ODk5OCwiaWF0IjoxNjM5Mzc0MTk4fQ.lgU0s_SKGUA7RmEdw4MBrh3eF0MDgR72KfDNRU6j0K0; u_c_captain_dev_local=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2dpbiIsInBhdGgiOiIvIiwidG9rZW5LZXkiOiI5ZWJmMWI5MGM0ZmU3YWNlYmVlZGY4ZjM1YWY5NGY1N2E3YWVlZjQzNmNkNjk3NmM5OGFjODlmMTM5NmZkZjdjIiwibmJmIjoxNjM5NTU3MDkyLCJkb21haW4iOiJ0ZXJtaW51cy5pbyIsImlzcyI6ImRyYWNvIiwidGVuYW50SWQiOjEsImV4cGlyZV90aW1lIjo2MDQ4MDAsImV4cCI6MTY0MDE2MTg5MiwiaWF0IjoxNjM5NTU3MDkyfQ.78txc2PNyqtjsdyKz-2bhxqwxottHXvi-RvSItx6tqA; OPENAPISESSION=38238ecc-bd79-49fc-8276-fcaedbd6119d; OPENAPI-CSRF-TOKEN=tK4oCrHuQqV30941Kp5IFjdEvV2e8IAk

### 应用资源趋势
GET http://openapi.dev.terminus.io/api/projects/5/applications-resources/actions/trend?applicationID=6&end=1639644965000&start=1639126550000
lang: zh-CN
org-id: 1
user-id: 2
cookie: taid=f9902540-58d3-11ec-85d9-c226b743fa5b; u_c_captain_hkci_local=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2dpbiIsInBhdGgiOiIvIiwidG9rZW5LZXkiOiI5ODcyOTg4YzhkODMyMzZmZDE3ZTVmZGU5MmE0MTI5YWI0MjgwMmVmMmI4YWMwZWY1M2QxMDJjZWU0MzIxYWJlIiwibmJmIjoxNjM5Mzc0MTk4LCJkb21haW4iOiJ0ZXJtaW51cy5pbyIsImlzcyI6ImRyYWNvIiwidGVuYW50SWQiOjEsImV4cGlyZV90aW1lIjo2MDQ4MDAsImV4cCI6MTYzOTk3ODk5OCwiaWF0IjoxNjM5Mzc0MTk4fQ.lgU0s_SKGUA7RmEdw4MBrh3eF0MDgR72KfDNRU6j0K0; u_c_captain_dev_local=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2dpbiIsInBhdGgiOiIvIiwidG9rZW5LZXkiOiI5ZWJmMWI5MGM0ZmU3YWNlYmVlZGY4ZjM1YWY5NGY1N2E3YWVlZjQzNmNkNjk3NmM5OGFjODlmMTM5NmZkZjdjIiwibmJmIjoxNjM5NTU3MDkyLCJkb21haW4iOiJ0ZXJtaW51cy5pbyIsImlzcyI6ImRyYWNvIiwidGVuYW50SWQiOjEsImV4cGlyZV90aW1lIjo2MDQ4MDAsImV4cCI6MTY0MDE2MTg5MiwiaWF0IjoxNjM5NTU3MDkyfQ.78txc2PNyqtjsdyKz-2bhxqwxottHXvi-RvSItx6tqA; OPENAPISESSION=38238ecc-bd79-49fc-8276-fcaedbd6119d; OPENAPI-CSRF-TOKEN=tK4oCrHuQqV30941Kp5IFjdEvV2e8IAk
