### 应用资源排行
GET http://openapi.dev.terminus.io/api/projects/5/applications-resources
lang: zh-CN
org-id: 1
user-id: 2
cookie:u_c_captain_dev_local=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2dpbiIsInBhdGgiOiIvIiwidG9rZW5LZXkiOiI5ZWJmMWI5MGM0ZmU3YWNlYmVlZGY4ZjM1YWY5NGY1N2E3YWVlZjQzNmNkNjk3NmM5OGFjODlmMTM5NmZkZjdjIiwibmJmIjoxNjM4NDE0NzIxLCJkb21haW4iOiJ0ZXJtaW51cy5pbyIsImlzcyI6ImRyYWNvIiwidGVuYW50SWQiOjEsImV4cGlyZV90aW1lIjo2MDQ4MDAsImV4cCI6MTYzOTAxOTUyMSwiaWF0IjoxNjM4NDE0NzIxfQ.oVg5wj-uaeqipmdMvhO0XuItjoEO_jnwFChyWo_ODxA; OPENAPISESSION=712491ec-e8d0-4ce0-a979-8a3877f49fcf; OPENAPI-CSRF-TOKEN=BTXIaZrd0ZdwMta0Wy4uCccTgHDmUzKT; u_c_captain_hkci_local=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2dpbiIsInBhdGgiOiIvIiwidG9rZW5LZXkiOiI5ODcyOTg4YzhkODMyMzZmZDE3ZTVmZGU5MmE0MTI5YWI0MjgwMmVmMmI4YWMwZWY1M2QxMDJjZWU0MzIxYWJlIiwibmJmIjoxNjM4NzY4MjA3LCJkb21haW4iOiJ0ZXJtaW51cy5pbyIsImlzcyI6ImRyYWNvIiwidGVuYW50SWQiOjEsImV4cGlyZV90aW1lIjo2MDQ4MDAsImV4cCI6MTYzOTM3MzAwNywiaWF0IjoxNjM4NzY4MjA3fQ.6-3kh63SADxPnusXcJ4igPbppeiuUlxfmqn78zYCWEA
