- machine_mem:
    title: "内存使用率"
    metric_names: "host_summary"
    type: "machine"
    order: 2
    defines:
      avg.mem_used_percent:
        label: "内存使用率"
        unit: "%"
        unit_type: "PERCENT"
        axis_index: 0
        chart_type: "line"
    parameters:

