- machine_disk_io_write:
    title: "磁盘写"
    metric_names: "diskio"
    type: "machine"
    order: 6
    defines:
      max.write_rate:
        label: "写IO"
        unit: "B/s"
        unit_type: "TRAFFIC"
        axis_index: 0
        chart_type: "line"
    parameters:
      group:
        - "name"

