- machine_net_io_recv:
    title: "网络接收"
    metric_names: "net"
    type: "machine"
    order: 10
    defines:
      max.recv_rate:
        label: "读IO"
        unit: "B/s"
        unit_type: "TRAFFIC"
        axis_index: 0
        chart_type: "line"
    parameters:
      group:
        - "interface"

