- system_etcd_response_size:
    title: "HTTP累计响应大小"
    metric_names: "etcd"
    type: "etcd"
    order: 6
    defines:
      max.sum:
        label: ""
        unit: "B"
        unit_type: "CAPACITY"
        axis_index: 0
        chart_type: "line"
    parameters:
      group:
        - "url_host"
      filter_prom_metric:
        - "http_response_size_bytes"
      filter_prom_metric_type:
        - "summary"

