version: "1.0"

triggers:
- schedule:
    cron: "0 0 */1 * * ?"

stages:
- name: "repo"
  tasks:
  - get: "repo"
    params:
      depth: 1
- name: "custom-stage"
  tasks:
  - task: "custom-task"
    config:
      image_resource:
        type: "docker-image"
        source:
          repository: "((default.docker.image.repo))"
          tag: "((default.docker.image.tag))"
      inputs:
      - name: "repo"
      outputs:
      - name: "custom-output-1"
      - name: "custom-output-2"
      run:
        path: "sh"
        args:
        - "-xc"
        - "echo \"this is custom-output-1\" > custom-output-1 && echo \"this is custom-output-2\" > custom-output-2 && ls"
- name: "reuse-custom-outputs"
  tasks:
  - aggregate:
    - task: "dealwith-custom-outputs"
      config:
        image_resource:
          type: "docker-image"
          source:
            repository: "((default.docker.image.repo))"
            tag: "((default.docker.image.tag))"
        inputs:
        - name: "custom-output-1"
        - name: "custom-output-2"
        run:
          path: "cat"
          args:
          - "custom-output-1"
          - "custom-output-2"
- name: "buildpack"
  tasks:
  - aggregate:
    - put: "bp-backend"
      params:
        only_build: false
    - put: "bp-frontend"
      params:
        only_build: false
- name: "dicehub"
  tasks:
  - put: "dice-hub"
    params:
      dice_yml: "repo/dice.yml"
      init_sql: "repo/db"
      replacement_images:
      - "bp-backend/pack-result"
      - "bp-frontend/pack-result"
- name: "deploy"
  tasks:
  - put: "deploy"
    params:
      time_out: 600

resources:
- name: "repo"
  type: "git"
  source:
    uri: "((gittar.repo))"
    branch: "((gittar.branch))"
    username: "((gittar.username))"
    password: "((gittar.password))"
- name: "bp-backend"
  type: "buildpack"
  source:
    context: "repo/services/showcase"
    modules:
    - name: "blog-web"
    - name: "blog-service"
      path: "blog-service/blog-service-impl"
    - name: "user-service"
      path: "user-service/user-service-impl"
- name: "bp-frontend"
  type: "buildpack"
  source:
    context: "repo/endpoints/showcase-front"
    modules:
    - name: "showcase-front"
- name: "dice-hub"
  type: "dicehub"
  source:
    workspace: "((dice.env))"
- name: "deploy"
  type: "dice"
  source:
    app_id: "((dice.id))"
    uri: "((dice.url))"
    operator_id: "((dice.operator.id))"
    workspace: "((dice.env))"
    branch: "((gittar.branch))"
