### create devflow
POST http://localhost:9527/api/devflow
Content-Type: application/json
User-ID: 2
Org-ID: 1

{
  "issueID": 173,
  "appID": 365,
  "sourceBranch": "master",
  "targetBranch": "feature/test"
}

### delete devflow
DELETE  http://localhost:9527/api/devflow/39
Content-Type: application/json
User-ID: 2
Org-ID: 1

{
  "mergeID": "35",
  "issueID": "173"
}

### get devflow
GET http://localhost:9527/api/devflow/actions/info?mergeID=59&projectID=5
Content-Type: application/json
User-ID: 2
Org-ID: 1
