---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: volume-provisioner
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: volume-provisioner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events", "pods/exec"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: volume-provisioner
subjects:
  - kind: ServiceAccount
    name: volume-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: volume-provisioner
  apiGroup: rbac.authorization.k8s.io
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: volume-provisioner
  annotations:
    description: k8s volume provisioner
spec:
  updateStrategy:
    type: RollingUpdate      
  template:
    metadata:
      name: volume-provisioner
      labels:
        app: volume-provisioner
    spec:
      serviceAccount: volume-provisioner
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/dice/volume-provisioner:4.0-20210413-0f95415
          imagePullPolicy: Always
          name: volume-provisioner
          volumeMounts:
            - name: host-dir
              mountPath: "/hostfs"
      volumes:
        - name: host-dir
          hostPath:
            path: "/"
      imagePullSecrets:
        - name: aliyun-registry
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: dice-local-volume
provisioner: dice/local-volume
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: dice-nfs-volume
provisioner: dice/netdata-volume
