// Copyright (c) 2021 Terminus, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-register. DO NOT EDIT.
// Sources: details.proto

package pb

import (
	reflect "reflect"

	transport "github.com/erda-project/erda-infra/pkg/transport"
)

// RegisterAlertDetailServiceImp details.proto
func RegisterAlertDetailServiceImp(regester transport.Register, srv AlertDetailServiceServer, opts ...transport.ServiceOption) {
	_ops := transport.DefaultServiceOptions()
	for _, op := range opts {
		op(_ops)
	}
	RegisterAlertDetailServiceHandler(regester, AlertDetailServiceHandler(srv), _ops.HTTP...)
	RegisterAlertDetailServiceServer(regester, srv, _ops.GRPC...)
}

// ServiceNames return all service names
func ServiceNames(svr ...string) []string {
	return append(svr,
		"erda.core.monitor.alertdetail.AlertDetailService",
	)
}

var (
	alertDetailServiceClientType  = reflect.TypeOf((*AlertDetailServiceClient)(nil)).Elem()
	alertDetailServiceServerType  = reflect.TypeOf((*AlertDetailServiceServer)(nil)).Elem()
	alertDetailServiceHandlerType = reflect.TypeOf((*AlertDetailServiceHandler)(nil)).Elem()
)

// AlertDetailServiceClientType .
func AlertDetailServiceClientType() reflect.Type { return alertDetailServiceClientType }

// AlertDetailServiceServerType .
func AlertDetailServiceServerType() reflect.Type { return alertDetailServiceServerType }

// AlertDetailServiceHandlerType .
func AlertDetailServiceHandlerType() reflect.Type { return alertDetailServiceHandlerType }

func Types() []reflect.Type {
	return []reflect.Type{
		// client types
		alertDetailServiceClientType,
		// server types
		alertDetailServiceServerType,
		// handler types
		alertDetailServiceHandlerType,
	}
}
