- addon_container_diskio_read:
    title: "磁盘读速度"
    metric_names: "docker_container_blkio"
    type: "addon_container"
    order: 5
    defines:
      diffps.io_service_bytes_recursive_read:
        label: "读取"
        unit: "B/s"
        unit_type: "TRAFFIC"
        axis_index: 0
        chart_type: "line"
    parameters:
      group:
        - "container_id"

