- redis_repl_backlog_histlen:
    title: "积压空间中写入的新数据的大小"
    metric_names: "redis"
    type: "redis_remove"
    order: 22
    defines:
      avg.repl_backlog_histlen:
        label: ""
        unit: "B"
        unit_type: "CAPACITY"
        axis_index: 0
        chart_type: "line"
    parameters:

