- name: "kubernetes组件实例内存异常"
  trigger: "alert"
  target: "dingding,ticket,email,mbox,webhook,dingtalk_work_notice"
  formats:
    mem_usage_percent_avg: "percent:2"
    mem_usage_value: "size:byte"
    mem_limit_value: "size:byte"
    mem_allocation_value: "size:byte"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}}内存使用率告警】
  template: |
    【kubernetes组件内存使用率告警】

    Pod: {{pod_name}}

    Pod_Ip: {{pod_ip}}

    使用率: {{mem_usage_percent_avg}}

    使用: {{mem_usage_value}}

    限制: {{mem_limit_value}}

    分配: {{mem_allocation_value}}

    集群: {{cluster_name}}

    机器: {{host_ip}}

    容器ID: {{container_id}}

    组织名称: {{org_name}}

    告警级别: {{level}}

    时间: {{timestamp}}

    [查看记录]({{record_url}})

- name: "kubernetes组件实例内存异常"
  trigger: "alert"
  target: "sms"
  formats:
    mem_usage_percent_avg: "percent:2"
    mem_usage_value: "size:byte"
    mem_limit_value: "size:byte"
    mem_allocation_value: "size:byte"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}}内存使用率告警】
  template: |
    {{cluster_name}}集群{{pod_name}}组件触发kubernetes组件实例内存使用率异常告警，组织名称: {{org_name}}，使用率: {{mem_usage_percent_avg}}，告警级别: {{level}}

- name: "kubernetes组件实例内存异常"
  trigger: "alert"
  target: "vms"
  formats:
    mem_usage_percent_avg: "percent:2"
    mem_usage_value: "size:byte"
    mem_limit_value: "size:byte"
    mem_allocation_value: "size:byte"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}}内存使用率告警】
  template: |
    {{cluster_name}}集群{{pod_name}}组件触发kubernetes组件实例内存使用率异常告警，组织名称: {{org_name}}，使用率: {{mem_usage_percent_avg}}，告警级别: {{level}}

- name: "kubernetes组件实例内存异常"
  trigger: "recover"
  target: "dingding,ticket,email,mbox,webhook,dingtalk_work_notice"
  formats:
    mem_usage_percent_avg: "percent:2"
    trigger_duration: "time:ms"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}}内存使用率恢复】
  template: |
    【kubernetes组件内存使用率恢复】

    Pod: {{pod_name}}

    Pod_Ip: {{pod_ip}}

    使用率: {{mem_usage_percent_avg}}

    集群: {{cluster_name}}

    机器: {{host_ip}}

    容器ID: {{container_id}}

    组织名称: {{org_name}}

    持续时间: {{trigger_duration}}

    恢复时间: {{timestamp}}

    [查看记录]({{record_url}})

- name: "kubernetes组件实例内存异常"
  trigger: "recover"
  target: "sms"
  formats:
    mem_usage_percent_avg: "percent:2"
    trigger_duration: "time:ms"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}}内存使用率恢复】
  template: |
    {{cluster_name}}集群{{pod_name}}组件触发kubernetes组件实例内存使用率异常告警恢复，组织名称: {{org_name}}，使用率: {{mem_usage_percent_avg}}
- name: "kubernetes组件实例内存异常"
  trigger: "recover"
  target: "vms"
  formats:
    mem_usage_percent_avg: "percent:2"
    trigger_duration: "time:ms"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}}内存使用率恢复】
  template: |
    {{cluster_name}}集群{{pod_name}}组件触发kubernetes组件实例内存使用率异常告警恢复，组织名称: {{org_name}}，使用率: {{mem_usage_percent_avg}}
