- role: Owner,Lead
  scope: project
  resource: project
  action: CREATE
- role: Owner,Lead,PM,PD
  scope: project
  resource: project
  action: UPDATE
- role: Owner,Lead
  scope: project
  resource: project
  action: DELETE
- role: Owner,Lead,PM,PD,Dev,QA,Ops,Support,Reporter,Guest # 事件活动权限用的resource是project，所以ops要加上
  scope: project
  resource: project
  action: GET
- role: Owner,Lead,PM
  scope: project
  resource: app
  action: CREATE
## 项目公开状态 start
- role: Owner
  scope: project
  resource: project-public
  action: UPDATE
## 项目公开状态 end

## 项目功能配置 start
- role: Owner,Lead,PM,PD
  scope: project
  resource: projectFunction
  action: GET
- role: Owner,Lead,PM
  scope: project
  resource: projectFunction
  action: UPDATE
## 项目功能配置 end

## 通知 start
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: notify
  action: OPERATE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: notify
  action: CREATE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: notify
  action: DELETE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: notify
  action: UPDATE
- role: Owner,Lead,PM,PD,Dev,QA,Support,Guest
  scope: project
  resource: notify
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA,Support,Guest
  scope: project
  resource: notify
  action: LIST
## 通知 end

## approve start
- role: Owner,Lead,Dev,QA,Support
  scope: project
  resource: approve
  action: GET
- role: Owner,Lead,Dev,QA,
  scope: project
  resource: approve
  action: CREATE
- role: Owner,Lead,Dev,QA,Support
  scope: project
  resource: approve
  action: LIST
## approve end


## 监控 dashboard start
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: monitor_project_alert
  action: CREATE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: monitor_project_alert
  action: UPDATE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: monitor_project_alert
  action: DELETE
- role: Owner,Lead,PM,PD,Dev,QA,Support,Guest
  scope: project
  resource: monitor_project_alert
  action: LIST
- role: Owner,Lead,PM,PD,Dev,QA,Support,Guest
  scope: project
  resource: monitor_project_alert
  action: GET
- role: Owner,Lead,Support
  scope: project
  resource: monitor_alert_metrics
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA,Ops,Support,Reporter
  scope: project
  resource: monitor_project
  action: GET
## 监控 dashboard end

## 迭代 start
- scope: project
  resource: iteration
  action: CREATE
  role: Owner,Lead,PM,PD
- scope: project
  resource: iteration
  action: UPDATE
  role: Owner,Lead,PM,PD
- scope: project
  resource: iteration
  action: DELETE
  role: Owner,Lead,PM,PD
- scope: project
  resource: iteration
  action: LIST
  role: Owner,Lead,PM,PD,Dev,QA,Support,Guest
- scope: project
  resource: iteration
  action: GET
  role: Owner,Lead,PM,PD,Dev,QA,Support,Guest
## 迭代 end

## issue类型转换 start
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: issue-type
  action: UPDATE
## issue类型转换 end

## issue导入 start
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: issue-import
  action: CREATE
## issue导入 end

## issue需求 start
- scope: project
  resource: issue-requirement
  action: CREATE
  role: Owner,Lead,PM,PD,Dev,QA
  resource_role: Creator,Assignee
- scope: project
  resource: issue-requirement
  action: UPDATE
  # todo细化更新状态的权限，不放在update的action里(Lead,Dev,QA)
  role: Owner,Lead,PM,PD,Dev,QA
  resource_role: Creator,Assignee
- scope: project
  resource: issue-requirement
  action: LIST
  role: Owner,Lead,PM,PD,Dev,QA,Support,Guest
  resource_role: Creator,Assignee
- scope: project
  resource: issue-requirement
  action: GET
  role: Owner,Lead,PM,PD,Dev,QA,Support,Guest
  resource_role: Creator,Assignee
- scope: project
  resource: issue-requirement
  action: DELETE
  role: Owner,PM,PD
  resource_role: Creator
- scope: project
  resource: issue-requirement
  action: update-state-to-OPEN
  role: Owner,Lead,PM,PD,Dev,QA
- scope: project
  resource: issue-requirement
  action: update-state-to-WORKING
  role: Owner,Lead,PM,PD,Dev,QA
  resource_role: Creator,Assignee
- scope: project
  resource: issue-requirement
  action: update-state-to-TESTING
  role: Owner,Lead,PM,PD,Dev,QA
  resource_role: Creator,Assignee
- scope: project
  resource: issue-requirement
  action: update-state-to-DONE
  role: Owner,Lead,PM,PD,Dev,QA
  resource_role: Creator,Assignee
## issue需求 end

## issue任务 start
- scope: project
  resource: issue-task
  action: CREATE
  role: Owner,Lead,PM,PD,Dev,QA
  resource_role: Creator,Assignee
- scope: project
  resource: issue-task
  action: UPDATE
  # todo细化更新状态的权限，不放在update的action里(Dev)
  role: Owner,Lead,PM,PD,QA,Dev
  resource_role: Creator,Assignee
- scope: project
  resource: issue-task
  action: LIST
  role: Owner,Lead,PM,PD,Dev,QA,Support,Guest
  resource_role: Creator,Assignee
- scope: project
  resource: issue-task
  action: GET
  role: Owner,Lead,PM,PD,Dev,QA,Support,Guest
  resource_role: Creator,Assignee
- scope: project
  resource: issue-task
  action: DELETE
  role: Owner,Lead
  resource_role: Creator
- scope: project
  resource: issue-task
  action: update-state-to-WORKING
  role: Owner,Lead,Dev
  resource_role: Creator,Assignee
- scope: project
  resource: issue-task
  action: update-state-to-DONE
  role: Owner,Lead,Dev
  resource_role: Creator,Assignee
## issue任务 start

## issue缺陷 start
- scope: project
  resource: issue-bug
  action: CREATE
  role: Owner,Lead,PM,PD,Dev,QA
  resource_role: Creator,Assignee
- scope: project
  resource: issue-bug
  action: UPDATE
  # todo细化更新状态的权限，不放在update的action里(Lead,Dev)
  role: Owner,Lead,PM,PD,QA,Dev
  resource_role: Creator,Assignee
- scope: project
  resource: issue-bug
  action: LIST
  role: Owner,Lead,PM,PD,Dev,QA,Support,Guest
  resource_role: Creator,Assignee
- scope: project
  resource: issue-bug
  action: GET
  role: Owner,Lead,PM,PD,Dev,QA,Support,Guest
  resource_role: Creator,Assignee
- scope: project
  resource: issue-bug
  action: DELETE
  role: Owner,Lead,PM,QA
  resource_role: Creator
- scope: project
  resource: issue-bug
  action: update-state-to-RESOLVED
  role: Owner,Lead,PM,PD,Dev,QA
  resource_role: Creator,Assignee
- scope: project
  resource: issue-bug
  action: update-state-to-REOPEN
  role: Owner,Lead,PM,PD,Dev,QA
  resource_role: Creator,Assignee
- scope: project
  resource: issue-bug
  action: update-state-to-WONTFIX
  role: Owner,Lead,PM,PD,Dev,QA
  resource_role: Creator,Assignee
- scope: project
  resource: issue-bug
  action: update-state-to-DUP
  role: Owner,Lead,PM,PD,Dev,QA
  resource_role: Creator,Assignee
- scope: project
  resource: issue-bug
  action: update-state-to-CLOSED
  role: Owner,QA
  resource_role: Creator
## issue缺陷 end

## issue epic start
- scope: project
  resource: issue-epic
  action: CREATE
  role: Owner,Lead,PM,PD,Dev,QA
  resource_role: Creator,Assignee
- scope: project
  resource: issue-epic
  action: UPDATE
  role: Owner,Lead,PM,PD,QA,Dev
  resource_role: Creator,Assignee
- scope: project
  resource: issue-epic
  action: LIST
  role: Owner,Lead,PM,PD,Dev,QA,Support,Guest
  resource_role: Creator,Assignee
- scope: project
  resource: issue-epic
  action: GET
  role: Owner,Lead,PM,PD,Dev,QA,Support,Guest
  resource_role: Creator,Assignee
- scope: project
  resource: issue-epic
  action: DELETE
  role: Owner,PM,PD
  resource_role: Creator
## issue epic end

## issue工单 start
- scope: project
  resource: issue-ticket
  action: CREATE
  role: Owner,Lead,PM,PD,Dev,QA,Reporter
  resource_role: Creator,Assignee
- scope: project
  resource: issue-ticket
  action: UPDATE
  # todo细化更新状态的权限，不放在update的action里(Lead,Dev)
  role: Owner,Lead,PM,PD,QA,Dev
  resource_role: Creator,Assignee
- scope: project
  resource: issue-ticket
  action: LIST
  role: Owner,Lead,PM,PD,Dev,QA,Support,Reporter,Guest
  resource_role: Creator,Assignee
- scope: project
  resource: issue-ticket
  action: GET
  role: Owner,Lead,PM,PD,Dev,QA,Ops,Support,Reporter,Guest
  resource_role: Creator,Assignee
- scope: project
  resource: issue-ticket
  action: DELETE
  role: Owner,Lead,PM,PD,Dev,QA
  resource_role: Creator,Assignee
- scope: project
  resource: issue-ticket
  action: update-state-to-RESOLVED
  role: Owner,Lead,PM,PD,Dev,QA,Reporter
  resource_role: Creator,Assignee
- scope: project
  resource: issue-ticket
  action: update-state-to-REOPEN
  role: Owner,Lead,PM,PD,Dev,QA,Reporter
  resource_role: Creator,Assignee
- scope: project
  resource: issue-ticket
  action: update-state-to-WONTFIX
  role: Owner,Lead,PM,PD,Dev,QA,Reporter
  resource_role: Creator,Assignee
- scope: project
  resource: issue-ticket
  action: update-state-to-DUP
  role: Owner,Lead,PM,PD,Dev,QA,Reporter
  resource_role: Creator,Assignee
- scope: project
  resource: issue-ticket
  action: update-state-to-CLOSED
  role: Owner,QA,Reporter
  resource_role: Creator
## issue工单 end

## issue panel start
- scope: project
  resource: issue-panel
  action: CREATE
  role: Owner,Lead,PM,PD,Dev,QA
  resource_role: Creator
- scope: project
  resource: issue-panel
  action: UPDATE
  role: Owner,Lead,PM,PD,Dev,QA
  resource_role: Creator
- scope: project
  resource: issue-panel
  action: DELETE
  role: Owner,Lead,PM,PD,Dev,QA
  resource_role: Creator
- scope: project
  resource: issue-panel
  action: GET
  role: Owner,Lead,PM,PD,Dev,QA,Support,Guest
  resource_role: Creator
## issue panel end

## 成员 start
- role: Owner,Lead,PM
  scope: project
  resource: member
  action: CREATE
- role: Owner,Lead,PM
  scope: project
  resource: member
  action: UPDATE
- role: Owner,Lead,PM,PD,Dev,QA,Support,Guest
  scope: project
  resource: member
  action: LIST
- role: Owner,Lead
  scope: project
  resource: cloudaccount
  action: OPERATE
- role: Owner,Lead,Dev,QA,Support
  scope: project
  resource: terminal
  action: OPERATE
## 成员 end

## addon start
- role: Owner,Lead,Support
  scope: project
  resource: middleware
  action: GET
- role: Owner,Lead
  scope: project
  resource: customAddon
  action: UPDATE
- role: Owner,Lead
  scope: project
  resource: customAddon
  action: CREATE
- role: Owner,Lead,Dev,QA,Support
  scope: project
  resource: addon
  action: GET
- role: Owner,Lead,Dev,QA
  scope: project
  resource: addon
  action: DELETE
- role: Owner,Lead,Support
  scope: project
  resource: addon_env
  action: GET
## addon end

## TMC start
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: registercenter
  action: GET
- role: Owner,Lead,PM,PD,Dev
  scope: project
  resource: registercenter
  action: UPDATE
- role: Owner,Lead,PM,PD,Dev
  scope: project
  resource: registercenter
  action: DELETE
- role: Owner,Lead,PM,PD,Dev
  scope: project
  resource: registercenter
  action: CREATE
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: log_analytics
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: monitor
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: monitor_topology
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: monitor_error
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: monitor_error
  action: LIST
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: monitor_trace
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: monitor_trace
  action: LIST
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: monitor_trace
  action: UPDATE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: monitor_trace
  action: CREATE
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: microservice_metric
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: monitor_status
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: monitor_status
  action: CREATE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: monitor_status
  action: UPDATE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: monitor_status
  action: DELETE
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: monitor_status
  action: LIST
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: report
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: report
  action: UPDATE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: report
  action: DELETE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: report
  action: CREATE
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: report_settings
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: report_settings
  action: UPDATE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: report_settings
  action: DELETE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: report_settings
  action: CREATE
- role: Owner,Lead,PM,PD,Dev,Support
  scope: project
  resource: log_analytics
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: config-center_group
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: config-center_properties
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: config-center_properties
  action: UPDATE
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: menu
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: settings
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: service-mesh_circuit_breaker
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: service-mesh_circuit_breaker
  action: UPDATE
- role: Owner,Lead,PM,PD,Dev,QA,Support
  scope: project
  resource: service-mesh_fault_inject
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: service-mesh_fault_inject
  action: UPDATE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: service-mesh_fault_inject
  action: DELETE
## TMC end

## JVM Profiler start
- role: Owner,Lead,Support,Dev,QA
  scope: project
  resource: jvm_profiler
  action: LIST
- role: Owner,Lead,Support,Dev,QA
  scope: project
  resource: jvm_profiler
  action: GET
- role: Owner,Lead,Support
  scope: project
  resource: jvm_profiler
  action: CREATE
- role: Owner,Lead,Support
  scope: project
  resource: jvm_profiler
  action: UPDATE
## JVM Profiler end

## PMP start ##
- role: Owner,Lead,Dev,QA,Support
  scope: project
  resource: pmp
  action: OTHER
- role: Owner,Lead,Dev,QA,Support
  scope: project
  resource: pmp
  action: GET
## PMP end ##

- role: Owner,Lead,Dev,QA,Support
  scope: project
  resource: webhook
  action: OPERATE

## TestPlan start ##
- role: Owner,Lead,QA
  scope: project
  resource: testplan
  action: CREATE
- role: Owner,Lead,QA
  scope: project
  resource: testplan
  action: UPDATE
- role: Owner,Lead,QA
  scope: project
  resource: testplan
  action: DELETE
- role: Owner,Lead,PM,PD,Dev,QA,Support,Guest
  scope: project
  resource: testplan
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA,Support,Guest
  scope: project
  resource: testplan
  action: LIST
- role: Owner,Lead,QA
  scope: project
  resource: testplan
  action: OPERATE
- role: Owner,Lead,QA
  scope: project
  resource: testplanCaseRel
  action: CREATE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: testplanCaseRel
  action: UPDATE
## TestPlan end #

## TestPlanV2 start ##
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: testplanV2
  action: CREATE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: testplanV2
  action: UPDATE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: testplanV2
  action: DELETE
- role: Owner,Lead,PM,PD,Dev,QA,Support,Reporter,Guest
  scope: project
  resource: testplanV2
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA,Support,Reporter,Guest
  scope: project
  resource: testplanV2
  action: LIST
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: testplanV2
  action: OPERATE
## TestPlanV2 end #
-
## 自动化测试场景 start ##
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: autotest-scene
  action: CREATE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: autotest-scene
  action: UPDATE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: autotest-scene
  action: DELETE
- role: Owner,Lead,PM,PD,Dev,QA,Support,Reporter,Guest
  scope: project
  resource: autotest-scene
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA,Support,Reporter,Guest
  scope: project
  resource: autotest-scene
  action: LIST
## 自动化测试场景 end #

## 分支规则管理 start ##
- role: Owner,Lead
  scope: project
  resource: branch_rule
  action: OPERATE
## 分支规则管理 end ##

## 工作流 ##
- role: Owner,Lead,PM
  scope: project
  resource: issue-state
  action: CREATE
- role: Owner,Lead,PM
  scope: project
  resource: issue-state
  action: UPDATE
- role: Owner,Lead,PM
  scope: project
  resource: issue-state
  action: DELETE
## 工作流 ##

## 测试空间 ##
- role: Owner,PM
  scope: project
  resource: autotestSpace
  action: CREATE
- role: Owner,PM
  scope: project
  resource: autotestSpace
  action: UPDATE
- role: Owner,PM
  scope: project
  resource: autotestSpace
  action: DELETE
  ## 测试空间 ##

  ## Sceneset start ##
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: sceneset
  action: CREATE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: sceneset
  action: UPDATE
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: sceneset
  action: DELETE
- role: Owner,Lead,PM,PD,Dev,QA,Support,Reporter,Guest
  scope: project
  resource: sceneset
  action: GET
- role: Owner,Lead,PM,PD,Dev,QA,Support,Reporter,Guest
  scope: project
  resource: sceneset
  action: LIST
- role: Owner,Lead,PM,PD,Dev,QA
  scope: project
  resource: sceneset
  action: OPERATE
## Sceneset end #
