version: '3.1'

services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
    ports:
      - 3306:3306

  ai-proxy:
    image: "image"
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      mysql_username: root
      mysql_password: 1234567890
      mysql_database: ai
