POST http://localhost:7076/api/v1/collect/fluent-bit
Content-Type: application/json

[
  {
    "date": "2018-05-30T09:39:52.000681Z",
    "log": "hello world\n",
    "stream": "stdout",
    "time": "2021-08-16T07:56:01.025279973Z",
    "level": "INFO",
    "source": "container",
    "kubernetes": {
      "pod_name": "pod",
      "namespace": "ns",
      "container_name": "cname",
      "container_id": "cid",
      "pod_id": "pid",
      "labels": {
        "k": "v"
      },
      "annotations": {
        "k": "v"
      }
    }
  }
]
