// Code generated by protoc-gen-go-form. DO NOT EDIT.
// Source: autotest-plan.proto

package pb

import (
	url "net/url"
	strconv "strconv"

	urlenc "github.com/erda-project/erda-infra/pkg/urlenc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "github.com/erda-project/erda-infra/pkg/urlenc" package it is being compiled against.
var _ urlenc.URLValuesUnmarshaler = (*TestPlanUpdateByHookRequest)(nil)
var _ urlenc.URLValuesUnmarshaler = (*Content)(nil)
var _ urlenc.URLValuesUnmarshaler = (*TestPlanUpdateByHookResponse)(nil)

// TestPlanUpdateByHookRequest implement urlenc.URLValuesUnmarshaler.
func (m *TestPlanUpdateByHookRequest) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "event":
				m.Event = vals[0]
			case "action":
				m.Action = vals[0]
			case "orgID":
				m.OrgID = vals[0]
			case "projectID":
				m.ProjectID = vals[0]
			case "applicationID":
				m.ApplicationID = vals[0]
			case "env":
				m.Env = vals[0]
			case "timestamp":
				m.Timestamp = vals[0]
			case "content":
				if m.Content == nil {
					m.Content = &Content{}
				}
			case "content.testPlanID":
				if m.Content == nil {
					m.Content = &Content{}
				}
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Content.TestPlanID = val
			case "content.executeTime":
				if m.Content == nil {
					m.Content = &Content{}
				}
				m.Content.ExecuteTime = vals[0]
			case "content.passRate":
				if m.Content == nil {
					m.Content = &Content{}
				}
				val, err := strconv.ParseFloat(vals[0], 64)
				if err != nil {
					return err
				}
				m.Content.PassRate = val
			case "content.apiTotalNum":
				if m.Content == nil {
					m.Content = &Content{}
				}
				val, err := strconv.ParseInt(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Content.ApiTotalNum = val
			case "content.costTimeSec":
				if m.Content == nil {
					m.Content = &Content{}
				}
				val, err := strconv.ParseInt(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Content.CostTimeSec = val
			case "content.apiSuccessNum":
				if m.Content == nil {
					m.Content = &Content{}
				}
				val, err := strconv.ParseInt(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Content.ApiSuccessNum = val
			case "content.apiExecNum":
				if m.Content == nil {
					m.Content = &Content{}
				}
				val, err := strconv.ParseInt(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Content.ApiExecNum = val
			case "content.pipelineYml":
				if m.Content == nil {
					m.Content = &Content{}
				}
				m.Content.PipelineYml = vals[0]
			case "content.stepAPIType":
				if m.Content == nil {
					m.Content = &Content{}
				}
				m.Content.StepAPIType = vals[0]
			case "content.status":
				if m.Content == nil {
					m.Content = &Content{}
				}
				m.Content.Status = vals[0]
			case "content.sceneID":
				if m.Content == nil {
					m.Content = &Content{}
				}
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Content.SceneID = val
			case "content.sceneSetID":
				if m.Content == nil {
					m.Content = &Content{}
				}
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Content.SceneSetID = val
			case "content.parentID":
				if m.Content == nil {
					m.Content = &Content{}
				}
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Content.ParentID = val
			case "content.projectID":
				if m.Content == nil {
					m.Content = &Content{}
				}
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Content.ProjectID = val
			case "content.creatorID":
				if m.Content == nil {
					m.Content = &Content{}
				}
				m.Content.CreatorID = vals[0]
			case "content.iterationID":
				if m.Content == nil {
					m.Content = &Content{}
				}
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Content.IterationID = val
			case "content.stepID":
				if m.Content == nil {
					m.Content = &Content{}
				}
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Content.StepID = val
			case "content.ExecuteRate":
				if m.Content == nil {
					m.Content = &Content{}
				}
				val, err := strconv.ParseFloat(vals[0], 64)
				if err != nil {
					return err
				}
				m.Content.ExecuteRate = val
			case "content.executeDuration":
				if m.Content == nil {
					m.Content = &Content{}
				}
				m.Content.ExecuteDuration = vals[0]
			case "content.timeBegin":
				if m.Content == nil {
					m.Content = &Content{}
				}
				m.Content.TimeBegin = vals[0]
			case "content.timeEnd":
				if m.Content == nil {
					m.Content = &Content{}
				}
				m.Content.TimeEnd = vals[0]
			case "content.pipelineID":
				if m.Content == nil {
					m.Content = &Content{}
				}
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Content.PipelineID = val
			case "content.apiRefSuccessNum":
				if m.Content == nil {
					m.Content = &Content{}
				}
				val, err := strconv.ParseInt(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Content.ApiRefSuccessNum = val
			case "content.apiRefExecNum":
				if m.Content == nil {
					m.Content = &Content{}
				}
				val, err := strconv.ParseInt(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Content.ApiRefExecNum = val
			}
		}
	}
	return nil
}

// Content implement urlenc.URLValuesUnmarshaler.
func (m *Content) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "testPlanID":
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.TestPlanID = val
			case "executeTime":
				m.ExecuteTime = vals[0]
			case "passRate":
				val, err := strconv.ParseFloat(vals[0], 64)
				if err != nil {
					return err
				}
				m.PassRate = val
			case "apiTotalNum":
				val, err := strconv.ParseInt(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.ApiTotalNum = val
			case "costTimeSec":
				val, err := strconv.ParseInt(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.CostTimeSec = val
			case "apiSuccessNum":
				val, err := strconv.ParseInt(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.ApiSuccessNum = val
			case "apiExecNum":
				val, err := strconv.ParseInt(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.ApiExecNum = val
			case "pipelineYml":
				m.PipelineYml = vals[0]
			case "stepAPIType":
				m.StepAPIType = vals[0]
			case "status":
				m.Status = vals[0]
			case "sceneID":
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.SceneID = val
			case "sceneSetID":
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.SceneSetID = val
			case "parentID":
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.ParentID = val
			case "projectID":
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.ProjectID = val
			case "creatorID":
				m.CreatorID = vals[0]
			case "iterationID":
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.IterationID = val
			case "stepID":
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.StepID = val
			case "ExecuteRate":
				val, err := strconv.ParseFloat(vals[0], 64)
				if err != nil {
					return err
				}
				m.ExecuteRate = val
			case "executeDuration":
				m.ExecuteDuration = vals[0]
			case "timeBegin":
				m.TimeBegin = vals[0]
			case "timeEnd":
				m.TimeEnd = vals[0]
			case "pipelineID":
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.PipelineID = val
			case "apiRefSuccessNum":
				val, err := strconv.ParseInt(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.ApiRefSuccessNum = val
			case "apiRefExecNum":
				val, err := strconv.ParseInt(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.ApiRefExecNum = val
			}
		}
	}
	return nil
}

// TestPlanUpdateByHookResponse implement urlenc.URLValuesUnmarshaler.
func (m *TestPlanUpdateByHookResponse) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "data":
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Data = val
			}
		}
	}
	return nil
}
