# MIGRATION_BASE

CREATE TABLE `fdp_master_data_sync` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `type` varchar(128) NOT NULL,
  `sync` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `fdp_master_event_box_log` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `queue_id` varchar(128) DEFAULT NULL COMMENT '队列id',
  `project_id` varchar(128) DEFAULT NULL COMMENT '空间id',
  `status` varchar(255) DEFAULT NULL COMMENT '状态',
  `pipeline_yml_name` varchar(255) DEFAULT NULL COMMENT 'yaml',
  `cluster_name` varchar(128) DEFAULT NULL COMMENT '集群名',
  `h_key` varchar(128) DEFAULT NULL COMMENT 'hkey',
  `count` varchar(128) DEFAULT NULL COMMENT 'count值',
  `request_content` longtext COMMENT '回调原文',
  `pipeline_id` bigint(20) DEFAULT NULL COMMENT 'pipeline_id',
  `created_at` datetime NOT NULL COMMENT '表记录创建时间',
  PRIMARY KEY (`id`),
  KEY `hkey` (`h_key`,`project_id`),
  KEY `yamlName` (`pipeline_yml_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='回调表';

CREATE TABLE `fdp_master_gittar_repo` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `gittar_project_id` bigint(20) DEFAULT NULL COMMENT 'gittar project id',
  `gittar_project_name` varchar(128) DEFAULT NULL COMMENT 'gittar project 名字',
  `gittar_app_id` bigint(20) DEFAULT NULL COMMENT 'gittar应用 id',
  `gittar_app_name` varchar(128) DEFAULT NULL COMMENT 'gittar应用名',
  `repo_url` varchar(256) DEFAULT NULL COMMENT '仓库地址',
  `repo_abbrev` varchar(128) DEFAULT NULL COMMENT '相对地址',
  `token` varchar(128) DEFAULT NULL COMMENT '仓库token',
  `org_name` varchar(128) DEFAULT NULL COMMENT '企业id名字',
  `delete_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `creator_id` varchar(128) DEFAULT NULL COMMENT '创建人 ID',
  `updater_id` varchar(128) DEFAULT NULL COMMENT '更新者ID',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime NOT NULL COMMENT '更新时间',
  `org_id` bigint(20) DEFAULT NULL COMMENT '企业 id',
  `project_id` bigint(20) DEFAULT NULL COMMENT '项目 id',
  `application_id` bigint(20) DEFAULT NULL COMMENT '应用 id',
  `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群 id',
  `cluster_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='gittar仓库表';

CREATE TABLE `fdp_master_model_workflows` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `org_id` bigint(20) DEFAULT NULL COMMENT '企业 id',
  `model_manage_id` bigint(20) NOT NULL COMMENT '模型管理ID',
  `process_type` varchar(128) NOT NULL COMMENT '处理类型',
  `name` varchar(128) NOT NULL DEFAULT '' COMMENT '工作流名',
  `name_pinyin` varchar(128) NOT NULL DEFAULT '' COMMENT '工作流拼音',
  `description` varchar(1024) NOT NULL DEFAULT '' COMMENT '工作流描述',
  `source` varchar(32) DEFAULT '' COMMENT 'workflow 来源: dl/cdp',
  `run_type` varchar(64) NOT NULL DEFAULT '' COMMENT '运行类型: ATONCE、SCHEDULE',
  `cron` varchar(128) DEFAULT '' COMMENT '任务周期',
  `cron_start_from` datetime DEFAULT NULL COMMENT '延时执行时间',
  `pipeline_name` varchar(128) DEFAULT '' COMMENT 'pipeline 名称',
  `pipeline` mediumtext NOT NULL COMMENT 'pipeline 内容',
  `pipeline_id` bigint(20) DEFAULT NULL COMMENT 'pipeline id',
  `node_params` text COMMENT '工作流节点参数',
  `locations` varchar(1024) DEFAULT NULL,
  `creator_id` varchar(128) DEFAULT NULL COMMENT '创建者 ID',
  `updater_id` varchar(128) DEFAULT NULL COMMENT '更新者ID',
  `extra` mediumtext COMMENT '扩展信息',
  `delete_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `cluster_name` varchar(256) DEFAULT NULL COMMENT '集群名',
  `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
  `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
  `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='模型管理工作流表';

CREATE TABLE `fdp_master_oneid_rules` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `rule_code` varchar(64) DEFAULT NULL,
  `rule_desc` varchar(64) NOT NULL COMMENT '规则描述',
  `is_unique` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否唯一',
  `weight` int(11) NOT NULL COMMENT '权重',
  `delete_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `creator_id` varchar(128) DEFAULT NULL COMMENT '创建人 ID',
  `updater_id` varchar(128) DEFAULT NULL COMMENT '更新者ID',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime NOT NULL COMMENT '更新时间',
  `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
  `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
  `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
  `cluster_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
  `org_id` bigint(20) DEFAULT NULL COMMENT '应用id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `rule_code` (`rule_code`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8 COMMENT='oneid规则表';


INSERT INTO `fdp_master_oneid_rules` (`id`, `rule_code`, `rule_desc`, `is_unique`, `weight`, `delete_yn`, `creator_id`, `updater_id`, `created_at`, `updated_at`, `cluster_id`, `project_id`, `application_id`, `cluster_name`, `org_id`) VALUES (1,'phone','手机号',1,2,0,'1','1','2020-04-29 12:00:00','2020-05-14 17:03:39',NULL,NULL,NULL,'terminus-test',NULL),(2,'app ID&open ID','app ID&open ID',1,4,0,'1','1','2020-04-29 12:00:00','2020-05-14 17:03:39',NULL,NULL,NULL,'terminus-test',NULL),(3,'memberid','会员ID',1,1,0,'1','1','2020-04-29 12:00:00','2020-05-14 17:03:39',NULL,NULL,NULL,'terminus-test',NULL),(4,'email','邮箱',1,3,0,'1','1','2020-04-29 12:00:00','2020-05-14 17:03:39',NULL,NULL,NULL,'terminus-test',NULL);

CREATE TABLE `fdp_master_reco_scenario_workflows` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `org_id` bigint(20) DEFAULT NULL COMMENT '企业 id',
  `scenario_name` varchar(128) NOT NULL DEFAULT '',
  `scenario_code` varchar(128) NOT NULL DEFAULT '',
  `process_type` varchar(128) NOT NULL COMMENT '处理类型',
  `name` varchar(128) NOT NULL DEFAULT '' COMMENT '工作流名',
  `name_pinyin` varchar(128) NOT NULL DEFAULT '' COMMENT '工作流拼音',
  `description` varchar(1024) NOT NULL DEFAULT '' COMMENT '工作流描述',
  `source` varchar(32) DEFAULT '' COMMENT 'workflow 来源: dl/cdp',
  `run_type` varchar(64) NOT NULL DEFAULT '' COMMENT '运行类型: ATONCE、SCHEDULE',
  `cron` varchar(128) DEFAULT '' COMMENT '任务周期',
  `cron_start_from` datetime DEFAULT NULL COMMENT '延时执行时间',
  `category_id` bigint(20) NOT NULL COMMENT '工作流目录 ID',
  `pipeline_name` varchar(128) DEFAULT '' COMMENT 'pipeline 名称',
  `pipeline` mediumtext NOT NULL COMMENT 'pipeline 内容',
  `pipeline_id` bigint(20) DEFAULT NULL COMMENT 'pipeline id',
  `node_params` text COMMENT '工作流节点参数',
  `locations` varchar(1024) DEFAULT NULL,
  `creator_id` varchar(128) CHARACTER SET utf8mb4 DEFAULT '' COMMENT '创建者 ID',
  `updater_id` varchar(128) DEFAULT NULL COMMENT '更新者ID',
  `extra` mediumtext COMMENT '扩展信息',
  `delete_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_category_id_name` (`scenario_code`,`process_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='场景工作流表';

CREATE TABLE `fdp_master_sql_history` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `org_id` bigint(20) DEFAULT NULL COMMENT '企业 id',
  `project_id` bigint(20) DEFAULT NULL COMMENT '项目 id',
  `application_id` bigint(20) DEFAULT NULL COMMENT '应用 id',
  `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群 id',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '执行记录名称',
  `query_status` varchar(128) NOT NULL COMMENT '查询响应状态',
  `query_time` bigint(20) NOT NULL COMMENT '查询耗时',
  `sql` text NOT NULL COMMENT '查询sql',
  `data_model_name` varchar(255) NOT NULL COMMENT '数据模型 名称',
  `data_source_id` bigint(20) NOT NULL COMMENT '数据源 ID',
  `delete_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `creator_id` varchar(128) DEFAULT NULL COMMENT '创建人 ID',
  `updater_id` varchar(128) DEFAULT NULL COMMENT '更新者ID',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime NOT NULL COMMENT '更新时间',
  `cluster_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='sql执行历史表';

CREATE TABLE `fdp_master_workflow_copy_detail` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `copy_log_id` int(11) NOT NULL COMMENT '关联字段',
  `workflow_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '工作流名称',
  `operation_type` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '操作类型',
  `copy_success` tinyint(1) DEFAULT '0' COMMENT '复制是否成功',
  `error_reason` text COLLATE utf8mb4_unicode_ci COMMENT '失败原因',
  `begin_date` datetime DEFAULT NULL COMMENT '复制开始时间',
  `end_date` datetime DEFAULT NULL COMMENT '复制结束时间',
  PRIMARY KEY (`id`),
  KEY `workflow_copy_fk1` (`copy_log_id`),
  CONSTRAINT `workflow_copy_fk1` FOREIGN KEY (`copy_log_id`) REFERENCES `fdp_master_workflow_copy_log` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `fdp_master_workflow_copy_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '名称',
  `created_date` datetime NOT NULL COMMENT '创建时间',
  `file_success` tinyint(1) DEFAULT '0' COMMENT '文件生成是否成功',
  `error_reason` text COLLATE utf8mb4_unicode_ci COMMENT '失败原因',
  `file_path` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文件路径',
  `file_date` datetime DEFAULT NULL COMMENT '文件生成成功时间',
  `complete` tinyint(1) DEFAULT '0' COMMENT '复制是否完成',
  `complete_date` datetime DEFAULT NULL COMMENT '复制完成时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `fdp_master_workflow_node_git_checkout` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `workflow_id` bigint(20) NOT NULL COMMENT 'workflow id',
  `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'git checkout',
  `git_app_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT ' git app id',
  `git_url` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'git地址',
  `created_at` datetime NOT NULL COMMENT '表记录创建时间',
  `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
  `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
  `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
  `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
  `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
  `org_id` bigint(20) DEFAULT NULL COMMENT '应用id',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流git切换节点表';

CREATE TABLE `fdp_master_workflow_node_labelcomputing_rt` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `workflow_id` bigint(20) NOT NULL COMMENT 'workflow id',
  `created_at` datetime NOT NULL COMMENT '表记录创建时间',
  `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
  `org_id` bigint(20) DEFAULT NULL COMMENT '企业id',
  `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
  `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
  `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
  `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流实时标签计算节点表';

CREATE TABLE `fdp_master_workflow_node_python` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `workflow_id` bigint(20) NOT NULL COMMENT 'workflow id',
  `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'python任务名',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT 'python描述',
  `version` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'python版本',
  `content_git_path` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'content存在路径',
  `package_git_path` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '安装包存放路径',
  `created_at` datetime NOT NULL COMMENT '表记录创建时间',
  `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
  `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
  `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
  `git_app_id` bigint(20) DEFAULT NULL COMMENT '存放的git应用id',
  `relation_git_node_id` bigint(20) DEFAULT NULL COMMENT '关联的gitnodeid',
  `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
  `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
  `org_id` bigint(20) DEFAULT NULL COMMENT '应用id',
  `persist_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '存储方式',
  `cpu` double DEFAULT '1' COMMENT '节点cpu',
  `memory` double DEFAULT '1024' COMMENT '节点memory',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流python节点表';

CREATE TABLE `fdp_master_integration_service_log` (
                                                      `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                                      `name` varchar(128) DEFAULT NULL COMMENT '第三方服务名称',
                                                      `request_header` longtext COMMENT '请求透',
                                                      `request_body` longtext COMMENT '请求体',
                                                      `request_ok` tinyint(4) DEFAULT NULL COMMENT '是否请求成功',
                                                      `request_url` longtext COMMENT '请求url',
                                                      `request_params` longtext COMMENT 'query的参数',
                                                      `response_data` longtext COMMENT '返回的data',
                                                      `response_body` longtext COMMENT '返回body全文',
                                                      `remark` varchar(256) DEFAULT NULL COMMENT '备注信息',
                                                      `err` longtext COMMENT '错误信息',
                                                      `creator_id` varchar(128) DEFAULT NULL COMMENT '创建者id',
                                                      `created_at` datetime NOT NULL COMMENT '创建时间',
                                                      `updated_at` datetime NOT NULL COMMENT '更新时间',
                                                      PRIMARY KEY (`id`),
                                                      KEY `request_url` (`request_url`(128)),
                                                      KEY `request_ok` (`request_ok`)
) ENGINE=InnoDB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8 COMMENT='集成的第三方服务日志';

CREATE TABLE `fdp_master_workflow_categories` (
                                                  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                                  `org_id` bigint(20) DEFAULT NULL COMMENT '企业 id',
                                                  `source` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '平台来源：DL/CDP',
                                                  `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '目录名',
                                                  `name_pinyin` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '目录名拼音',
                                                  `parent_id` bigint(20) NOT NULL COMMENT '上级目录 ID',
                                                  `creator_id` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '创建人 ID',
                                                  `created_at` datetime NOT NULL COMMENT '表记录创建时间',
                                                  `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
                                                  `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
                                                  `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
                                                  `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
                                                  `cluster_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                                  PRIMARY KEY (`id`),
                                                  UNIQUE KEY `workflow_category_unique_index1` (`parent_id`,`source`,`name`,`cluster_name`,`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流目录表';

CREATE TABLE `fdp_master_workflow_dependencies` (
                                                    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                                    `workflow_id` bigint(20) NOT NULL COMMENT '工作流 ID',
                                                    `depend_workflow_id` bigint(20) NOT NULL COMMENT '依赖的工作流 ID',
                                                    `creator_id` varchar(128) NOT NULL DEFAULT '' COMMENT '创建者 ID',
                                                    `updater_id` varchar(128) NOT NULL DEFAULT '' COMMENT '更新着 ID',
                                                    `created_at` datetime NOT NULL COMMENT '表记录创建时间',
                                                    `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
                                                    `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
                                                    `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
                                                    `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
                                                    `cluster_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
                                                    `org_id` bigint(20) DEFAULT NULL COMMENT '企业 id',
                                                    PRIMARY KEY (`id`),
                                                    UNIQUE KEY `idx_dependWorkflowId_under_workflowId` (`workflow_id`,`depend_workflow_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工作流依赖表';

CREATE TABLE `fdp_master_workflow_node_cleaning` (
                                                     `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                                     `workflow_id` bigint(20) NOT NULL COMMENT ' workflow id',
                                                     `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点名称',
                                                     `mode` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点添加模式: ui/sql',
                                                     `description` text COLLATE utf8mb4_unicode_ci COMMENT '节点描述',
                                                     `clean_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '清洗类型: 维度表(dimension)/事实表(fact)',
                                                     `tb_en_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '表英文名称',
                                                     `tb_cn_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '表中文名称',
                                                     `tb_desc` text COLLATE utf8mb4_unicode_ci COMMENT '表描述',
                                                     `load_strategy` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '加载策略: increment/total',
                                                     `custom_content` text COLLATE utf8mb4_unicode_ci COMMENT '自定义编辑内容',
                                                     `main_model_id` bigint(20) DEFAULT NULL COMMENT '主模型 id',
                                                     `main_model_alias` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主模型别名',
                                                     `main_model_filter_cond` text COLLATE utf8mb4_unicode_ci COMMENT '主模型过滤条件',
                                                     `target_model_id` bigint(20) DEFAULT NULL COMMENT '目标模型 id',
                                                     `target_model_alias` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '目标模型别名',
                                                     `target_model_filter_cond` text COLLATE utf8mb4_unicode_ci COMMENT '目标模型过滤条件',
                                                     `created_at` datetime NOT NULL COMMENT '表记录创建时间',
                                                     `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
                                                     `org_id` bigint(20) DEFAULT NULL COMMENT '企业id',
                                                     `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
                                                     `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
                                                     `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
                                                     `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
                                                     `persist_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '存储方式',
                                                     `cpu` double DEFAULT '1' COMMENT '节点cpu',
                                                     `memory` double DEFAULT '1024' COMMENT '节点memory',
                                                     `create_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT 'CREATE' COMMENT '清洗节点创建方式',
                                                     PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流清洗节点表';

CREATE TABLE `fdp_master_workflow_node_cleaning_rt` (
                                                        `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                                        `workflow_id` bigint(20) NOT NULL COMMENT ' workflow id',
                                                        `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点名称',
                                                        `mode` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点添加模式: ui/sql',
                                                        `description` text COLLATE utf8mb4_unicode_ci COMMENT '节点描述',
                                                        `clean_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '清洗类型: 维度表(dimension)/事实表(fact)',
                                                        `tb_en_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '表英文名称',
                                                        `tb_cn_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '表中文名称',
                                                        `tb_desc` text COLLATE utf8mb4_unicode_ci COMMENT '表描述',
                                                        `load_strategy` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '加载策略: increment/total',
                                                        `custom_content` text COLLATE utf8mb4_unicode_ci COMMENT '自定义编辑内容',
                                                        `main_model_id` bigint(20) DEFAULT NULL COMMENT '主模型 id',
                                                        `main_model_alias` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主模型别名',
                                                        `main_model_filter_cond` text COLLATE utf8mb4_unicode_ci COMMENT '主模型过滤条件',
                                                        `target_model_id` bigint(20) DEFAULT NULL COMMENT '目标模型 id',
                                                        `target_model_alias` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '目标模型别名',
                                                        `target_model_filter_cond` text COLLATE utf8mb4_unicode_ci COMMENT '目标模型过滤条件',
                                                        `created_at` datetime NOT NULL COMMENT '表记录创建时间',
                                                        `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
                                                        `org_id` bigint(20) DEFAULT NULL COMMENT '企业id',
                                                        `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
                                                        `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
                                                        `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
                                                        `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
                                                        `persist_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '存储方式',
                                                        `cpu` double DEFAULT '1' COMMENT '节点cpu',
                                                        `memory` double DEFAULT '1024' COMMENT '节点memory',
                                                        `create_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT 'CREATE' COMMENT '清洗节点创建方式:SELECT,CREATE',
                                                        PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流实时清洗节点表';

CREATE TABLE `fdp_master_workflow_node_data_cancel` (
                                                        `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                                        `workflow_id` bigint(20) NOT NULL COMMENT 'workflow id',
                                                        `created_at` datetime NOT NULL COMMENT '表记录创建时间',
                                                        `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
                                                        `org_id` bigint(20) DEFAULT NULL COMMENT '企业id',
                                                        `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
                                                        `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
                                                        `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
                                                        `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
                                                        `persist_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '存储方式',
                                                        PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流取消节点表';

CREATE TABLE `fdp_master_workflow_node_export` (
                                                   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                                   `workflow_id` bigint(20) NOT NULL COMMENT ' workflow id',
                                                   `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点名称',
                                                   `mode` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点添加模式: ui/sql',
                                                   `description` text COLLATE utf8mb4_unicode_ci COMMENT '节点描述',
                                                   `custom_content` text COLLATE utf8mb4_unicode_ci COMMENT '自定义编辑内容',
                                                   `src_ds_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '源数据源类型: DL',
                                                   `src_ds_id` bigint(20) DEFAULT NULL COMMENT '源数据源 id',
                                                   `src_model_id` bigint(20) DEFAULT NULL COMMENT '源数据模型 id',
                                                   `load_strategy` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '加载策略: increment/total',
                                                   `load_interval` bigint(20) DEFAULT NULL COMMENT '增量加载时间间隔',
                                                   `load_interval_unit` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '增量加载时间间隔单位: MINUTE/HOUR/DAY',
                                                   `target_ds_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '目标数据源类型: CDP',
                                                   `target_ds_id` bigint(20) DEFAULT NULL COMMENT '目标数据源 id',
                                                   `target_model_id` bigint(20) DEFAULT NULL COMMENT '目标数据模型 id',
                                                   `preconditions` text COLLATE utf8mb4_unicode_ci COMMENT '前置条件',
                                                   `filter_cond` text COLLATE utf8mb4_unicode_ci COMMENT '过滤条件',
                                                   `write_mode` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '写入模式',
                                                   `created_at` datetime NOT NULL COMMENT '表记录创建时间',
                                                   `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
                                                   `org_id` bigint(20) DEFAULT NULL COMMENT '企业id',
                                                   `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
                                                   `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
                                                   `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
                                                   `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
                                                   `persist_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '存储方式',
                                                   `cpu` double DEFAULT '1' COMMENT '节点cpu',
                                                   `memory` double DEFAULT '1024' COMMENT '节点memory',
                                                   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流导出节点表';

CREATE TABLE `fdp_master_workflow_node_export_rt` (
                                                      `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                                      `workflow_id` bigint(20) NOT NULL COMMENT ' workflow id',
                                                      `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点名称',
                                                      `mode` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点添加模式: ui/sql',
                                                      `description` text COLLATE utf8mb4_unicode_ci COMMENT '节点描述',
                                                      `custom_content` text COLLATE utf8mb4_unicode_ci COMMENT '自定义编辑内容',
                                                      `src_ds_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '源数据源类型: DL',
                                                      `src_ds_id` bigint(20) DEFAULT NULL COMMENT '源数据源 id',
                                                      `src_model_id` bigint(20) DEFAULT NULL COMMENT '源数据模型 id',
                                                      `target_ds_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '目标数据源类型: CDP',
                                                      `target_ds_id` bigint(20) DEFAULT NULL COMMENT '目标数据源 id',
                                                      `target_model_id` bigint(20) DEFAULT NULL COMMENT '目标数据模型 id',
                                                      `preconditions` text COLLATE utf8mb4_unicode_ci COMMENT '前置条件',
                                                      `filter_cond` text COLLATE utf8mb4_unicode_ci COMMENT '过滤条件',
                                                      `write_mode` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '写入模式',
                                                      `created_at` datetime NOT NULL COMMENT '表记录创建时间',
                                                      `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
                                                      `org_id` bigint(20) DEFAULT NULL COMMENT '企业id',
                                                      `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
                                                      `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
                                                      `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
                                                      `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
                                                      `persist_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '存储方式',
                                                      PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流实时导出节点表';

CREATE TABLE `fdp_master_workflow_node_extracting` (
                                                       `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                                       `workflow_id` bigint(20) NOT NULL COMMENT ' workflow id',
                                                       `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点名称',
                                                       `mode` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点添加模式: ui/sql',
                                                       `description` text COLLATE utf8mb4_unicode_ci COMMENT '节点描述',
                                                       `extract_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '萃取类型: 汇总表(summary)/应用数据表(application)',
                                                       `tb_en_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '表英文名称',
                                                       `tb_cn_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '表中文名称',
                                                       `tb_desc` text COLLATE utf8mb4_unicode_ci COMMENT '表描述',
                                                       `load_strategy` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '加载策略: increment/total',
                                                       `exported` tinyint(1) DEFAULT NULL COMMENT '是否导出',
                                                       `custom_content` text COLLATE utf8mb4_unicode_ci COMMENT '自定义编辑内容',
                                                       `main_model_id` bigint(20) DEFAULT NULL COMMENT '主模型 id',
                                                       `main_model_alias` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主模型别名',
                                                       `main_model_filter_cond` text COLLATE utf8mb4_unicode_ci COMMENT '主模型过滤条件',
                                                       `target_model_id` bigint(20) DEFAULT NULL COMMENT '目标模型 id',
                                                       `target_model_alias` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '目标模型别名',
                                                       `target_model_filter_cond` text COLLATE utf8mb4_unicode_ci COMMENT '目标模型过滤条件',
                                                       `created_at` datetime NOT NULL COMMENT '表记录创建时间',
                                                       `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
                                                       `org_id` bigint(20) DEFAULT NULL COMMENT '企业id',
                                                       `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
                                                       `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
                                                       `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
                                                       `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
                                                       `persist_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '存储方式',
                                                       `cpu` double DEFAULT '1' COMMENT '节点cpu',
                                                       `memory` double DEFAULT '1024' COMMENT '节点memory',
                                                       PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流萃取节点表';

CREATE TABLE `fdp_master_workflow_node_extracting_rt` (
                                                          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                                          `workflow_id` bigint(20) NOT NULL COMMENT ' workflow id',
                                                          `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点名称',
                                                          `mode` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点添加模式: ui/sql',
                                                          `description` text COLLATE utf8mb4_unicode_ci COMMENT '节点描述',
                                                          `extract_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '萃取类型: 汇总表(summary)/应用数据表(application)',
                                                          `tb_en_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '表英文名称',
                                                          `tb_cn_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '表中文名称',
                                                          `tb_desc` text COLLATE utf8mb4_unicode_ci COMMENT '表描述',
                                                          `load_strategy` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '加载策略: increment/total',
                                                          `exported` tinyint(1) DEFAULT NULL COMMENT '是否导出',
                                                          `custom_content` text COLLATE utf8mb4_unicode_ci COMMENT '自定义编辑内容',
                                                          `main_model_id` bigint(20) DEFAULT NULL COMMENT '主模型 id',
                                                          `main_model_alias` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主模型别名',
                                                          `main_model_filter_cond` text COLLATE utf8mb4_unicode_ci COMMENT '主模型过滤条件',
                                                          `target_model_id` bigint(20) DEFAULT NULL COMMENT '目标模型 id',
                                                          `target_model_alias` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '目标模型别名',
                                                          `target_model_filter_cond` text COLLATE utf8mb4_unicode_ci COMMENT '目标模型过滤条件',
                                                          `created_at` datetime NOT NULL COMMENT '表记录创建时间',
                                                          `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
                                                          `org_id` bigint(20) DEFAULT NULL COMMENT '企业id',
                                                          `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
                                                          `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
                                                          `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
                                                          `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
                                                          `persist_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '存储方式',
                                                          PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流实时萃取节点表';

CREATE TABLE `fdp_master_workflow_node_integration` (
                                                        `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                                        `workflow_id` bigint(20) NOT NULL COMMENT ' workflow id',
                                                        `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点名称',
                                                        `mode` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点添加模式: ui/sql',
                                                        `description` text COLLATE utf8mb4_unicode_ci COMMENT '节点描述',
                                                        `custom_content` text COLLATE utf8mb4_unicode_ci COMMENT '自定义编辑内容',
                                                        `src_ds_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '源数据源类型: DL',
                                                        `src_ds_id` bigint(20) DEFAULT NULL COMMENT '源数据源 id',
                                                        `src_model_id` bigint(20) DEFAULT NULL COMMENT '源数据模型 id',
                                                        `src_column_ids` text COLLATE utf8mb4_unicode_ci COMMENT '源数据列 ids',
                                                        `load_strategy` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '加载策略: increment/total',
                                                        `load_interval` bigint(20) DEFAULT NULL COMMENT '增量加载时间间隔',
                                                        `load_interval_unit` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '增量加载时间间隔单位: MINUTE/HOUR/DAY',
                                                        `filter_cond` text COLLATE utf8mb4_unicode_ci COMMENT '源数据模型过滤条件',
                                                        `target_ds_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '目标数据源类型: CDP',
                                                        `target_ds_id` bigint(20) DEFAULT NULL COMMENT '目标数据源 id',
                                                        `target_model_id` bigint(20) DEFAULT NULL COMMENT '目标数据模型 id',
                                                        `target_distinct` tinyint(4) NOT NULL DEFAULT '0' COMMENT '目标表去重',
                                                        `column_default` text COLLATE utf8mb4_unicode_ci COMMENT '模型列默认值，map结构',
                                                        `created_at` datetime NOT NULL COMMENT '表记录创建时间',
                                                        `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
                                                        `org_id` bigint(20) DEFAULT NULL COMMENT '企业id',
                                                        `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
                                                        `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
                                                        `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
                                                        `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
                                                        `persist_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '存储方式',
                                                        `cpu` double DEFAULT '1' COMMENT '节点cpu',
                                                        `memory` double DEFAULT '1024' COMMENT '节点memory',
                                                        PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流集成节点表';

CREATE TABLE `fdp_master_workflow_node_integration_rt` (
                                                           `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                                           `workflow_id` bigint(20) NOT NULL COMMENT ' workflow id',
                                                           `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点名称',
                                                           `mode` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点添加模式: ui/sql',
                                                           `description` text COLLATE utf8mb4_unicode_ci COMMENT '节点描述',
                                                           `custom_content` text COLLATE utf8mb4_unicode_ci COMMENT '自定义编辑内容',
                                                           `src_ds_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '源数据源类型: DL',
                                                           `src_ds_id` bigint(20) DEFAULT NULL COMMENT '源数据源 id',
                                                           `src_model_id` bigint(20) DEFAULT NULL COMMENT '源数据模型 id',
                                                           `src_column_ids` text COLLATE utf8mb4_unicode_ci COMMENT '源列ids',
                                                           `file_path` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文件路径',
                                                           `file_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文件类型：JSON/XML/CSV/REGULAR',
                                                           `file_splitter` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文件分隔符',
                                                           `filter_cond` text COLLATE utf8mb4_unicode_ci COMMENT '源数据模型过滤条件',
                                                           `target_ds_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '目标数据源类型: CDP',
                                                           `target_ds_id` bigint(20) DEFAULT NULL COMMENT '目标数据源 id',
                                                           `target_model_id` bigint(20) DEFAULT NULL COMMENT '目标数据模型 id',
                                                           `target_distinct` tinyint(4) NOT NULL DEFAULT '0' COMMENT '目标表去重',
                                                           `column_default` text COLLATE utf8mb4_unicode_ci COMMENT '模型列默认值，map结构',
                                                           `created_at` datetime NOT NULL COMMENT '表记录创建时间',
                                                           `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
                                                           `org_id` bigint(20) DEFAULT NULL COMMENT '企业id',
                                                           `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
                                                           `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
                                                           `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
                                                           `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
                                                           `persist_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '存储方式',
                                                           PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流实时集成节点表';

CREATE TABLE `fdp_master_workflow_node_labelcomputing` (
                                                           `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                                           `workflow_id` bigint(20) NOT NULL COMMENT 'workflow id',
                                                           `created_at` datetime NOT NULL COMMENT '表记录创建时间',
                                                           `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
                                                           `org_id` bigint(20) DEFAULT NULL COMMENT '企业id',
                                                           `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
                                                           `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
                                                           `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
                                                           `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
                                                           `cpu` double DEFAULT '1' COMMENT '节点cpu',
                                                           `memory` double DEFAULT '1024' COMMENT '节点memory',
                                                           PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流标签计算节点表';

CREATE TABLE `fdp_master_workflow_node_model_mapping` (
                                                          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                                          `node_id` bigint(20) NOT NULL COMMENT '节点 id',
                                                          `node_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点类型: cleaning/extraction',
                                                          `mode` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '配置方式: ui/sql',
                                                          `model_id` bigint(20) NOT NULL COMMENT '目标模型 id',
                                                          `model_field` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '目标模型字段名称',
                                                          `rel_model_id` bigint(20) DEFAULT NULL COMMENT '关联模型 id',
                                                          `rel_model_field` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '关联模型字段名称',
                                                          `custom_content` text COLLATE utf8mb4_unicode_ci COMMENT '自定义编辑内容',
                                                          `created_at` datetime NOT NULL COMMENT '表记录创建时间',
                                                          `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
                                                          `org_id` bigint(20) DEFAULT NULL COMMENT '企业id',
                                                          `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
                                                          `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
                                                          `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
                                                          `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
                                                          PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流模型节点映射表';

CREATE TABLE `fdp_master_workflow_node_one_id` (
                                                   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                                   `workflow_id` bigint(20) NOT NULL COMMENT 'workflow id',
                                                   `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'oneID 节点名称',
                                                   `created_at` datetime NOT NULL COMMENT '表记录创建时间',
                                                   `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
                                                   `org_id` bigint(20) DEFAULT NULL COMMENT '企业id',
                                                   `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
                                                   `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
                                                   `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
                                                   `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
                                                   `persist_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '存储方式',
                                                   `cpu` double DEFAULT '1' COMMENT '节点cpu',
                                                   `memory` double DEFAULT '1024' COMMENT '节点memory',
                                                   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流oneid节点表';

CREATE TABLE `fdp_master_workflow_node_one_id_rel_model_field` (
                                                                   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                                                   `node_id` bigint(20) NOT NULL COMMENT '节点 id',
                                                                   `model_id` bigint(20) NOT NULL COMMENT '数据模型 id',
                                                                   `model_field` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '数据模型字段名称',
                                                                   `note` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '业务说明, 可选值: phone/appID/openID/memberID',
                                                                   `created_at` datetime NOT NULL COMMENT '表记录创建时间',
                                                                   `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
                                                                   `org_id` bigint(20) DEFAULT NULL COMMENT '企业id',
                                                                   `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
                                                                   `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
                                                                   `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
                                                                   `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
                                                                   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流oneid节点模型关联表';

CREATE TABLE `fdp_master_workflow_node_rel_model` (
                                                      `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                                      `workflow_id` bigint(20) NOT NULL COMMENT '工作流ID',
                                                      `node_id` bigint(20) NOT NULL COMMENT '节点 id',
                                                      `node_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点类型: cleaning/extraction',
                                                      `model_id` bigint(20) NOT NULL COMMENT '关联模型 id',
                                                      `model_alias` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '关联模型别名',
                                                      `join_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'join类型, LEFT/RIGHT/INNER/FULL',
                                                      `filter_cond` text COLLATE utf8mb4_unicode_ci COMMENT '关联模型过滤条件',
                                                      `created_at` datetime NOT NULL COMMENT '表记录创建时间',
                                                      `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
                                                      `org_id` bigint(20) DEFAULT NULL COMMENT '企业id',
                                                      `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
                                                      `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
                                                      `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
                                                      `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
                                                      PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流节点模型关联表';

CREATE TABLE `fdp_master_workflow_node_rel_model_field` (
                                                            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                                            `node_id` bigint(20) NOT NULL COMMENT '节点 id',
                                                            `node_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点类型: cleaning/extraction',
                                                            `mode` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '节点添加模式: ui/sql',
                                                            `model_id` bigint(20) NOT NULL COMMENT '关联模型 id',
                                                            `model_field` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '关联模型字段名称',
                                                            `rel_model_id` bigint(20) NOT NULL COMMENT '被关联模型 id',
                                                            `rel_model_field` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '被关联模型字段名称',
                                                            `custom_content` text COLLATE utf8mb4_unicode_ci COMMENT '自定义编辑内容',
                                                            `created_at` datetime NOT NULL COMMENT '表记录创建时间',
                                                            `updated_at` datetime NOT NULL COMMENT '表记录更新时间',
                                                            `org_id` bigint(20) DEFAULT NULL COMMENT '企业id',
                                                            `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
                                                            `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
                                                            `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
                                                            `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
                                                            PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流节点模型字段关联表';

CREATE TABLE `fdp_master_workflows` (
                                        `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
                                        `org_id` bigint(20) DEFAULT NULL COMMENT '企业 id',
                                        `source` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '平台来源：DL/CDP',
                                        `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '工作流名',
                                        `name_pinyin` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '工作流拼音',
                                        `description` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '工作流描述',
                                        `run_type` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '运行类型: ATONCE、SCHEDULE',
                                        `cron` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '任务周期',
                                        `cron_start_from` datetime DEFAULT NULL COMMENT '延时执行时间',
                                        `category_id` bigint(20) NOT NULL COMMENT '工作流目录 ID',
                                        `pipeline_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'pipeline 名称',
                                        `pipeline` mediumtext COLLATE utf8mb4_unicode_ci COMMENT 'pipeline 内容, 最大16MB',
                                        `locations` text COLLATE utf8mb4_unicode_ci COMMENT '工作流节点坐标二维数组',
                                        `node_params` text COLLATE utf8mb4_unicode_ci COMMENT '工作流节点参数',
                                        `creator_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '创建者 ID',
                                        `updater_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建者 ID',
                                        `extra` mediumtext COLLATE utf8mb4_unicode_ci COMMENT '扩展信息',
                                        `delete_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
                                        `created_at` datetime NOT NULL COMMENT '创建时间',
                                        `updated_at` datetime NOT NULL COMMENT '更新时间',
                                        `cluster_id` bigint(20) DEFAULT NULL COMMENT '集群id',
                                        `project_id` bigint(20) DEFAULT NULL COMMENT '项目id',
                                        `application_id` bigint(20) DEFAULT NULL COMMENT '应用id',
                                        `cluster_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '集群名',
                                        `pipeline_status` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'pipeline最近一次执行状态',
                                        `pipeline_begin_time` datetime DEFAULT NULL COMMENT 'pipeline最近一次执行时间',
                                        `task_queue_id` bigint(20) DEFAULT '1' COMMENT '队列id',
                                        `queue_level` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '队列优先级',
                                        PRIMARY KEY (`id`),
                                        KEY `idx_category_id_name` (`category_id`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作流表';
