@url = http://localhost:8080

### StartDiagnosis
POST {{url}}/api/diagnosis
    ?clusterName=terminus-dev
    &namespace=group-addon-log-es--t850554aa0bdf4a2bad000718f60189e7
    &podName=log-elasticsearch-1-0
Accept: application/json
Content-Type: application/json
User-ID: 1100
Org-ID: 1

{
  "labels": {
      "terminus-key": "1234567"
  }
}

### QueryDiagnosisStatus
GET {{url}}/api/diagnosis/namespaces/group-addon-log-es--t850554aa0bdf4a2bad000718f60189e7/pods/log-elasticsearch-1-0/status
    ?clusterName=terminus-dev
Accept: application/json
User-ID: 1100
Org-ID: 1

### ListProcesses
GET {{url}}/api/diagnosis/namespaces/group-addon-log-es--t850554aa0bdf4a2bad000718f60189e7/pods/log-elasticsearch-1-0/processes
    ?clusterName=terminus-dev
    &podIP=10.112.1.63
Accept: application/json
User-ID: 1100
Org-ID: 1
