version: 2.0

envs:
  TERMINUS_APP_NAME: PAMPAS_BLOG
  TERMINUS_TRACE_ENABLE: false

services:
  showcase-front:
    # 可选
    image: nginx:latest
    # 可选
    cmd: echo hello && npm run start
    # 可选
    ports:
      - 8080
    # 可选
    envs:
      TERMINUS_TRACE_ENABLE: false
      TERMINUS_APP_NAME: showcase-front-app
    # 可选
    hosts:
      - 127.0.0.1 www.terminus.io
    # 必填
    resources:
      cpu: 0.2
      mem: 256
      disk: 100
    # 可选
    volumes:
      - /home/admin/logs
    # 必填
    deployments:
      replicas: 1
      # 可选
      # "shuffle", "affinity", "unique"
      policies: shuffle
      labels:
        a: b
    # 可选
    depends_on:
      - blog-service
    # 
    expose:
      - 80
      - 443

    # 健康检查，配置一个命令
    health_check:
      http:
        port: 7070
        path: /status
        duration: 120
      

  blog-service:
    image: blog-service:latest

    # 必填
    resources:
      cpu: 0.2
      mem: 256
      disk: 100
    # 必填
    deployments:
      replicas: 1

    health_check:
      exec:
        cmd: curl http:127.0.0.1:7070/status
        duration: 120

addons:
    mysql: 
      plan: mysql:small
      as: MYSQL
      options:
        version: 5.7
        create_db: blog
      image: dnhsoft/mysql-utf8

    zk:
      plan: zookeeper:medium
