- zookeeper_packets_sent:
    title: "发送数据包数量"
    metric_names: "zookeeper"
    type: "zookeeper_remove"
    order: 5
    defines:
      diffps.packets_sent:
        label: ""
        unit: "个/s"
        unit_type: "CPS"
        axis_index: 0
        chart_type: "line"
    parameters:
      group:
        - "server"

