- name: "kubernetes组件异常退出"
  trigger: "alert"
  target: "dingding,ticket,email,mbox,webhook,dingtalk_work_notice"
  formats:
    started_at_value: "date"
    finished_at_value: "date"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}}异常退出告警】
  template: |
    【kubernetes组件异常退出告警】

    组件: {{pod_name}}

    Pod_Ip: {{pod_ip}}

    集群: {{cluster_name}}

    机器: {{host_ip}}

    启动时间: {{started_at_value}}

    退出时间: {{finished_at_value}}

    退出原因: {{terminated_reason_value}}

    组织名称: {{org_name}}

    告警级别: {{level}}

    时间: {{timestamp}}

    [查看详情]({{display_url}})

    [查看记录]({{record_url}})

- name: "kubernetes组件异常退出"
  trigger: "alert"
  target: "sms"
  formats:
    started_at_value: "date"
    finished_at_value: "date"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}}异常退出告警】
  template: |
    {{cluster_name}}集群{{pod_name}}组件触发kubernetes组件异常退出，组织名称: {{org_name}}，告警级别: {{level}}，退出原因：{{terminated_reason_value}}
- name: "kubernetes组件异常退出"
  trigger: "alert"
  target: "vms"
  formats:
    started_at_value: "date"
    finished_at_value: "date"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}}异常退出告警】
  template: |
    {{cluster_name}}集群{{pod_name}}组件触发kubernetes组件异常退出，组织名称: {{org_name}}，告警级别: {{level}}，退出原因：{{terminated_reason_value}}
- name: "kubernetes组件异常退出恢复"
  trigger: "recover"
  target: "dingding,ticket,email,mbox,webhook,dingtalk_work_notice"
  formats:
    trigger_duration: "time:ms"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}}异常退出恢复】
  template: |
    【kubernetes组件异常退出恢复】

    组件: {{pod_name}}

    Pod_Ip: {{pod_ip}}

    集群: {{cluster_name}}

    机器: {{host_ip}}

    组织名称: {{org_name}}

    持续时间: {{trigger_duration}}

    恢复时间: {{timestamp}}

    [查看记录]({{record_url}})

- name: "kubernetes组件异常退出恢复"
  trigger: "recover"
  target: "sms"
  formats:
    trigger_duration: "time:ms"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}}异常退出恢复】
  template: |
    {{cluster_name}}集群{{pod_name}}组件触发kubernetes组件异常退出告警恢复
- name: "kubernetes组件异常退出"
  trigger: "recover"
  target: "vms"
  formats:
    trigger_duration: "time:ms"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}}异常退出恢复】
  template: |
    {{cluster_name}}集群{{pod_name}}组件触发kubernetes组件异常退出告警恢复
