- name: "kubernetes组件实例CPU异常"
  trigger: "alert"
  target: "dingding,ticket,email,mbox,webhook,dingtalk_work_notice"
  language: "zh-CN"
  formats:
    cpu_usage_percent_avg: "percent:2"
    cpu_limit_value: "fraction:2"
    cpu_allocation_value: "fraction:2"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}} CPU使用率告警】
  template: |
    【kubernetes组件CPU使用率告警】

    Pod: {{pod_name}}

    Pod_Ip: {{pod_ip}}

    使用率: {{cpu_usage_percent_avg}}

    限制: {{cpu_limit_value}}核

    分配: {{cpu_allocation_value}}核

    集群: {{cluster_name}}

    机器: {{host_ip}}

    容器ID: {{container_id}}

    组织名称: {{org_name}}

    告警级别: {{level}}

    时间: {{timestamp}}

    [查看记录]({{record_url}})

- name: "kubernetes组件实例CPU异常"
  trigger: "alert"
  target: "sms"
  language: "zh-CN"
  formats:
    cpu_usage_percent_avg: "percent:2"
    cpu_limit_value: "fraction:2"
    cpu_allocation_value: "fraction:2"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}} CPU使用率告警】
  template: |
    {{cluster_name}}集群{{pod_name}}组件触发kubernetes组件实例CPU使用率异常，组织名称: {{org_name}}，使用率: {{cpu_usage_percent_avg}}，告警级别: {{level}}
- name: "kubernetes组件实例CPU异常"
  trigger: "alert"
  target: "vms"
  language: "zh-CN"
  formats:
    cpu_usage_percent_avg: "percent:2"
    cpu_limit_value: "fraction:2"
    cpu_allocation_value: "fraction:2"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}} CPU使用率告警】
  template: |
    {{cluster_name}}集群{{pod_name}}组件触发kubernetes组件实例CPU使用率异常，组织名称: {{org_name}}，使用率: {{cpu_usage_percent_avg}}，告警级别: {{level}}
- name: "kubernetes组件实例CPU异常恢复"
  trigger: "recover"
  target: "dingding,ticket,email,mbox,webhook,dingtalk_work_notice"
  language: "zh-CN"
  formats:
    cpu_usage_percent_avg: "percent:2"
    trigger_duration: "time:ms"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}} CPU使用率恢复】
  template: |
    【kubernetes组件CPU使用率恢复】

    Pod: {{pod_name}}

    Pod_Ip: {{pod_ip}}

    使用率: {{cpu_usage_percent_avg}}

    集群: {{cluster_name}}

    机器: {{host_ip}}

    容器ID: {{container_id}}

    组织名称: {{org_name}}

    持续时间: {{trigger_duration}}

    恢复时间: {{timestamp}}

    [查看记录]({{record_url}})
- name: "kubernetes组件实例CPU异常恢复"
  trigger: "recover"
  target: "sms"
  language: "zh-CN"
  formats:
    cpu_usage_percent_avg: "percent:2"
    trigger_duration: "time:ms"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}} CPU使用率恢复】
  template: |
    {{cluster_name}}集群{{pod_name}}组件触发kubernetes组件实例CPU使用率异常，组织名称: {{org_name}}，使用率: {{cpu_usage_percent_avg}}
- name: "kubernetes组件实例CPU异常恢复"
  trigger: "recover"
  target: "vms"
  language: "zh-CN"
  formats:
    cpu_usage_percent_avg: "percent:2"
    trigger_duration: "time:ms"
  title: |
    【{{cluster_name}}集群kubernetes组件{{pod_name}} CPU使用率恢复】
  template: |
    {{cluster_name}}集群{{pod_name}}组件触发kubernetes组件实例CPU使用率异常，组织名称: {{org_name}}，使用率: {{cpu_usage_percent_avg}}

- name: "CPU exception of Kubernetes component instance"
  trigger: "alert"
  target: "dingding,ticket,email,mbox,webhook"
  language: "en-US"
  formats:
    cpu_usage_percent_avg: "percent:2"
    cpu_limit_value: "fraction:2"
    cpu_allocation_value: "fraction:2"
  title: |
    [CPU usage alarm of Kubernetes component {{pod_name}} of cluster {{cluster_name}}]
  template: |
    [CPU usage alarm of Kubernetes component]

    Pod: {{pod_name}}

    Pod_Ip: {{pod_ip}}

    Usage: {{cpu_usage_percent_avg}}

    Limit: {{cpu_limit_value}} core

    Allocation: {{cpu_allocation_value}} core

    Cluster: {{cluster_name}}

    Machine: {{host_ip}}

    Container ID: {{container_id}}

    Organization name: {{org_name}}

    Time: {{timestamp}}

    [View records]({{record_url}})

- name: "CPU exception of Kubernetes component instance"
  trigger: "alert"
  target: "sms"
  language: "en-US"
  formats:
    cpu_usage_percent_avg: "percent:2"
    cpu_limit_value: "fraction:2"
    cpu_allocation_value: "fraction:2"
  title: |
    [CPU usage alarm of Kubernetes component {{pod_name}} of cluster {{cluster_name}}]
  template: |
    CPU usage exception of Kubernetes component instance triggered by component {{pod_name}} of cluster {{cluster_name}}, organization name: {{org_name}}, usage: {{cpu_usage_percent_avg}}
- name: "CPU exception of Kubernetes component instance"
  trigger: "alert"
  target: "vms"
  language: "en-US"
  formats:
    cpu_usage_percent_avg: "percent:2"
    cpu_limit_value: "fraction:2"
    cpu_allocation_value: "fraction:2"
  title: |
    [CPU usage alarm of Kubernetes component {{pod_name}} of cluster {{cluster_name}}]
  template: |
    CPU usage exception of Kubernetes component instance triggered by component {{pod_name}} of cluster {{cluster_name}}, organization name: {{org_name}}, usage: {{cpu_usage_percent_avg}}
- name: "CPU exception recovery of Kubernetes component instance"
  trigger: "recover"
  target: "dingding,ticket,email,mbox,webhook"
  language: "en-US"
  formats:
    cpu_usage_percent_avg: "percent:2"
    trigger_duration: "time:ms"
  title: |
    [CPU usage recovery of Kubernetes component {{pod_name}} of cluster {{cluster_name}}]
  template: |
    [CPU usage recovery of Kubernetes component]

    Pod: {{pod_name}}

    Pod_Ip: {{pod_ip}}

    Usage: {{cpu_usage_percent_avg}}

    Cluster: {{cluster_name}}

    Machine: {{host_ip}}

    Container ID: {{container_id}}

    Organization name: {{org_name}}

    Duration: {{trigger_duration}}

    Recovery time: {{timestamp}}

    [View records]({{record_url}})
- name: "CPU exception recovery of Kubernetes component instance"
  trigger: "recover"
  target: "sms"
  language: "en-US"
  formats:
    cpu_usage_percent_avg: "percent:2"
    trigger_duration: "time:ms"
  title: |
    [CPU usage recovery of Kubernetes component {{pod_name}} of cluster {{cluster_name}}]
  template: |
    CPU usage recovery of Kubernetes component instance triggered by component {{pod_name}} of cluster {{cluster_name}}, organization name: {{org_name}}, usage: {{cpu_usage_percent_avg}}
- name: "CPU exception recovery of Kubernetes component instance"
  trigger: "recover"
  target: "vms"
  language: "en-US"
  formats:
    cpu_usage_percent_avg: "percent:2"
    trigger_duration: "time:ms"
  title: |
    [CPU usage recovery of Kubernetes component {{pod_name}} of cluster {{cluster_name}}]
  template: |
    CPU usage recovery of Kubernetes component instance triggered by component {{pod_name}} of cluster {{cluster_name}}, organization name: {{org_name}}, usage: {{cpu_usage_percent_avg}}
