apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateless-deploy
  labels:
    app: stateless-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stateless-deploy
  template:
    metadata:
      labels:
        app: stateless-deploy
    spec:
      nodeSelector:
        kubernetes.io/hostname: node-010000007033
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
