$schema: http://json-schema.org/draft-07/schema#
type: object
properties:
  list:
    type: array
    description: list of test cases
    items:
      type: object
      required:
        - name
        - preCondition
        - stepAndResults
      properties:
        name:
          type: string
          description: the name of the case
        preCondition:
          type: string
          description: pre condition
          items:
            type: string
        stepAndResults:
          type: array
          description: list of step and corresponding result
          items:
            type: object
            properties:
              step:
                type: string
                description: Operation steps
              result:
                type: string
                description: Expected result
required:
  - list
