@url = http://localhost:7096/api

### ListSystemViews
GET {{url}}/dashboard/system/blocks?scope=org&scopeId=terminus

### GetSystemView
GET {{url}}/dashboard/system/blocks/apim_client

### ListCustomViews
GET {{url}}/dashboard/blocks?scope=org&scopeId=terminus

### GetCustomView
GET {{url}}/dashboard/blocks/deb2495438ad45adab7500b53579e80e

### CreateCustomView
POST {{url}}/dashboard/blocks
Content-Type: application/json

{
    "name":"testxx",
    "desc":"xxxx",
    "scope":"org",
    "scopeId":"terminus",
    "version":"v2",
    "viewConfig":[
        {
            "w":8,
            "h":9,
            "x":0,
            "y":0,
            "i":"view-WnVz0zRP",
            "minW":4,
            "minH":3,
            "moved":false,
            "static":false,
            "view":{
                "description":"",
                "hideHeader":true,
                "hideReload":true,
                "dataSourceType":"api",
                "title":"未命名图表",
                "api":{
                    "url":"/api/orgCenter/metrics-query",
                    "method":"post",
                    "query":{
                        "format":"chartv2",
                        "ql":"influxql:ast",
                        "type":"_",
                        "epoch":"ms",
                        "start":1627538099680,
                        "end":1627541699680
                    },
                    "body":{
                        "from":[
                            "host_summary"
                        ],
                        "select":[
                            {
                                "expr":"time()",
                                "alias":"typeP9yAzybe"
                            },
                            {
                                "expr":"round_float(n_cpus::field, 2)",
                                "alias":"valuenNjGK9QC"
                            }
                        ],
                        "groupby":[
                            "time()"
                        ]
                    }
                },
                "config":{
                    "dataSourceConfig":{
                        "activedMetricGroups":[
                            "machine",
                            "machine_cpu"
                        ],
                        "isSqlMode":false,
                        "typeDimensions":[
                            {
                                "type":"time",
                                "alias":"时间",
                                "key":"typeP9yAzybe"
                            }
                        ],
                        "valueDimensions":[
                            {
                                "type":"field",
                                "alias":"CPU核数",
                                "field":"host_summary-n_cpus::field",
                                "resultType":"number",
                                "key":"valuenNjGK9QC"
                            }
                        ]
                    }
                },
                "chartType":"chart:line"
            }
        }
    ]
}

### UpdateCustomView
PUT {{url}}/dashboard/blocks/deb2495438ad45adab7500b53579e80e
Content-Type: application/json

{
    "name":"testview",
    "desc":"yyy",
    "scope":"org",
    "scopeId":"terminus",
    "id":"deb2495438ad45adab7500b53579e80e",
    "version":"v2",
    "viewConfig":[
        {
            "w":21,
            "h":17,
            "x":0,
            "y":0,
            "i":"view-WnVz0zRP",
            "moved":false,
            "static":false,
            "view":{
                "title":"未命名图表",
                "description":"",
                "chartType":"chart:line",
                "dataSourceType":"api",
                "staticData":{

                },
                "config":{
                    "dataSourceConfig":{
                        "activedMetricGroups":[
                            "machine",
                            "machine_cpu"
                        ],
                        "isSqlMode":false,
                        "typeDimensions":[
                            {
                                "alias":"时间",
                                "key":"typeP9yAzybe",
                                "type":"time"
                            }
                        ],
                        "valueDimensions":[
                            {
                                "alias":"CPU核数",
                                "field":"host_summary-n_cpus::field",
                                "key":"valuenNjGK9QC",
                                "resultType":"number",
                                "type":"field"
                            }
                        ]
                    },
                    "optionProps":{
                        "isMoreThanOneDay":false
                    }
                },
                "api":{
                    "url":"/api/orgCenter/metrics-query",
                    "query":{
                        "end":1627612520980,
                        "epoch":"ms",
                        "format":"chartv2",
                        "ql":"influxql:ast",
                        "start":1627608920980,
                        "type":"_"
                    },
                    "body":{
                        "from":[
                            "host_summary"
                        ],
                        "groupby":[
                            "time()"
                        ],
                        "select":[
                            {
                                "alias":"typeP9yAzybe",
                                "expr":"time()"
                            },
                            {
                                "alias":"valuenNjGK9QC",
                                "expr":"round_float(n_cpus::field, 2)"
                            }
                        ]
                    },
                    "header":null,
                    "extraData":null,
                    "method":"post"
                },
                "controls":null
            }
        }
    ]
}

### DeleteCustomView
DELETE {{url}}/dashboard/blocks/deb2495438ad45adab7500b53579e80e
