// Code generated by protoc-gen-go-form. DO NOT EDIT.
// Source: definition.proto

package pb

import (
	json "encoding/json"
	url "net/url"
	strconv "strconv"
	strings "strings"

	urlenc "github.com/erda-project/erda-infra/pkg/urlenc"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the "github.com/erda-project/erda-infra/pkg/urlenc" package it is being compiled against.
var _ urlenc.URLValuesUnmarshaler = (*PipelineDefinitionProcessRequest)(nil)
var _ urlenc.URLValuesUnmarshaler = (*PipelineDefinitionProcessResponse)(nil)
var _ urlenc.URLValuesUnmarshaler = (*PipelineDefinitionProcessVersionRequest)(nil)
var _ urlenc.URLValuesUnmarshaler = (*PipelineDefinitionProcessVersionResponse)(nil)

// PipelineDefinitionProcessRequest implement urlenc.URLValuesUnmarshaler.
func (m *PipelineDefinitionProcessRequest) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "pipelineSource":
				m.PipelineSource = vals[0]
			case "pipelineYmlName":
				m.PipelineYmlName = vals[0]
			case "pipelineYml":
				m.PipelineYml = vals[0]
			case "snippetConfig":
				if len(vals) > 1 {
					var list []interface{}
					for _, text := range vals {
						var v interface{}
						err := json.NewDecoder(strings.NewReader(text)).Decode(&v)
						if err != nil {
							list = append(list, v)
						} else {
							list = append(list, text)
						}
					}
					val, _ := structpb.NewList(list)
					m.SnippetConfig = structpb.NewListValue(val)
				} else {
					var v interface{}
					err := json.NewDecoder(strings.NewReader(vals[0])).Decode(&v)
					if err != nil {
						val, _ := structpb.NewValue(v)
						m.SnippetConfig = val
					} else {
						m.SnippetConfig = structpb.NewStringValue(vals[0])
					}
				}
			case "versionLock":
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.VersionLock = val
			case "isDelete":
				val, err := strconv.ParseBool(vals[0])
				if err != nil {
					return err
				}
				m.IsDelete = val
			case "pipelineCreateRequest":
				if len(vals) > 1 {
					var list []interface{}
					for _, text := range vals {
						var v interface{}
						err := json.NewDecoder(strings.NewReader(text)).Decode(&v)
						if err != nil {
							list = append(list, v)
						} else {
							list = append(list, text)
						}
					}
					val, _ := structpb.NewList(list)
					m.PipelineCreateRequest = structpb.NewListValue(val)
				} else {
					var v interface{}
					err := json.NewDecoder(strings.NewReader(vals[0])).Decode(&v)
					if err != nil {
						val, _ := structpb.NewValue(v)
						m.PipelineCreateRequest = val
					} else {
						m.PipelineCreateRequest = structpb.NewStringValue(vals[0])
					}
				}
			}
		}
	}
	return nil
}

// PipelineDefinitionProcessResponse implement urlenc.URLValuesUnmarshaler.
func (m *PipelineDefinitionProcessResponse) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "id":
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.Id = val
			case "pipelineSource":
				m.PipelineSource = vals[0]
			case "pipelineYmlName":
				m.PipelineYmlName = vals[0]
			case "pipelineYml":
				m.PipelineYml = vals[0]
			case "versionLock":
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.VersionLock = val
			}
		}
	}
	return nil
}

// PipelineDefinitionProcessVersionRequest implement urlenc.URLValuesUnmarshaler.
func (m *PipelineDefinitionProcessVersionRequest) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "pipelineSource":
				m.PipelineSource = vals[0]
			case "pipelineYmlName":
				m.PipelineYmlName = vals[0]
			}
		}
	}
	return nil
}

// PipelineDefinitionProcessVersionResponse implement urlenc.URLValuesUnmarshaler.
func (m *PipelineDefinitionProcessVersionResponse) UnmarshalURLValues(prefix string, values url.Values) error {
	for key, vals := range values {
		if len(vals) > 0 {
			switch prefix + key {
			case "versionLock":
				val, err := strconv.ParseUint(vals[0], 10, 64)
				if err != nil {
					return err
				}
				m.VersionLock = val
			}
		}
	}
	return nil
}
