// Copyright (c) 2021 Terminus, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-register. DO NOT EDIT.
// Sources: exception.proto

package pb

import (
	reflect "reflect"

	transport "github.com/erda-project/erda-infra/pkg/transport"
)

// RegisterExceptionServiceImp exception.proto
func RegisterExceptionServiceImp(regester transport.Register, srv ExceptionServiceServer, opts ...transport.ServiceOption) {
	_ops := transport.DefaultServiceOptions()
	for _, op := range opts {
		op(_ops)
	}
	RegisterExceptionServiceHandler(regester, ExceptionServiceHandler(srv), _ops.HTTP...)
	RegisterExceptionServiceServer(regester, srv, _ops.GRPC...)
}

// ServiceNames return all service names
func ServiceNames(svr ...string) []string {
	return append(svr,
		"erda.msp.apm.exception.ExceptionService",
	)
}

var (
	exceptionServiceClientType  = reflect.TypeOf((*ExceptionServiceClient)(nil)).Elem()
	exceptionServiceServerType  = reflect.TypeOf((*ExceptionServiceServer)(nil)).Elem()
	exceptionServiceHandlerType = reflect.TypeOf((*ExceptionServiceHandler)(nil)).Elem()
)

// ExceptionServiceClientType .
func ExceptionServiceClientType() reflect.Type { return exceptionServiceClientType }

// ExceptionServiceServerType .
func ExceptionServiceServerType() reflect.Type { return exceptionServiceServerType }

// ExceptionServiceHandlerType .
func ExceptionServiceHandlerType() reflect.Type { return exceptionServiceHandlerType }

func Types() []reflect.Type {
	return []reflect.Type{
		// client types
		exceptionServiceClientType,
		// server types
		exceptionServiceServerType,
		// handler types
		exceptionServiceHandlerType,
	}
}
