POST http://{{collector_addr}}/api/v1/collect/logs/container
Content-Type: application/json
# adjust according config
X-Erda-Cluster-Key: {{erda_key}}
Authorization: Bearer {{token}}

[
  {
    "source": "container",
    "id": "3bdcc48e7222be90b889fffba685c762da74b61be8528605ecb2decaab4933f3",
    "stream": "stdout",
    "content": "hello world",
    "offset": 0,
    "timestamp": 1640796626617075700,
    "tags": {
      "application_id": "60",
      "application_name": "log-service",
      "cluster_name": "terminus-dev",
      "container_name": "nginx",
      "dice_application_id": "60",
      "dice_application_name": "log-service",
      "level": "INFO",
      "workspace": "staging"
    }
  }
]

###

# json array
POST http://{{collector_addr}}/api/v1/collect/metrics
Content-Type: application/json
# adjust according config
X-Erda-Cluster-Key: {{erda_key}}
Authorization: Bearer {{token}}

{"metrics":[{"name":"host_summary","timestamp":1644481950000000000,"tags":{"cluster_name":"terminus-dev","host_ip":"10.0.6.221","hostname":"node-010000006221","os":"centos 8.4.2105"},"fields":{"containers":45,"cpu_allocatable":8,"cpu_usage_active":8.799462883889937}},{"name":"host_summary","timestamp":1644481950000000000,"tags":{"cluster_name":"terminus-dev","host_ip":"10.0.6.221","hostname":"node-010000006221","os":"centos 8.4.2105"},"fields":{"containers":45,"cpu_allocatable":8,"cpu_usage_active":8.799462883889937}}]}

###

# json lines
POST http://{{collector_addr}}/api/v1/collect/metrics
# adjust according config
X-Erda-Cluster-Key: {{erda_key}}
Authorization: Bearer {{token}}

{"name":"host_summary","timestamp":1644481950000000000,"tags":{"cluster_name":"terminus-dev","host_ip":"10.0.6.221","hostname":"node-010000006221","os":"centos 8.4.2105"},"fields":{"containers":45,"cpu_allocatable":8,"cpu_usage_active":8.799462883889937}}
{"name":"host_summary","timestamp":1644481950000000000,"tags":{"cluster_name":"terminus-dev","host_ip":"10.0.6.221","hostname":"node-010000006221","os":"centos 8.4.2105"},"fields":{"containers":45,"cpu_allocatable":8,"cpu_usage_active":8.799462883889937}}

###

# json lines b64
POST http://{{collector_addr}}/api/v1/collect/metrics
# adjust according config
X-Erda-Cluster-Key: {{erda_key}}
Authorization: Bearer {{token}}
Custom-Content-Encoding: base64

eyJuYW1lIjoiaG9zdF9zdW1tYXJ5IiwidGltZXN0YW1wIjoxNjQ0NDgxOTUwMDAwMDAwMDAwLCJ0YWdzIjp7ImNsdXN0ZXJfbmFtZSI6InRlcm1pbnVzLWRldiIsImhvc3RfaXAiOiIxMC4wLjYuMjIxIiwiaG9zdG5hbWUiOiJub2RlLTAxMDAwMDAwNjIyMSIsIm9zIjoiY2VudG9zIDguNC4yMTA1In0sImZpZWxkcyI6eyJjb250YWluZXJzIjo0NSwiY3B1X2FsbG9jYXRhYmxlIjo4LCJjcHVfdXNhZ2VfYWN0aXZlIjo4Ljc5OTQ2Mjg4Mzg4OTkzN319CnsibmFtZSI6Imhvc3Rfc3VtbWFyeSIsInRpbWVzdGFtcCI6MTY0NDQ4MTk1MDAwMDAwMDAwMCwidGFncyI6eyJjbHVzdGVyX25hbWUiOiJ0ZXJtaW51cy1kZXYiLCJob3N0X2lwIjoiMTAuMC42LjIyMSIsImhvc3RuYW1lIjoibm9kZS0wMTAwMDAwMDYyMjEiLCJvcyI6ImNlbnRvcyA4LjQuMjEwNSJ9LCJmaWVsZHMiOnsiY29udGFpbmVycyI6NDUsImNwdV9hbGxvY2F0YWJsZSI6OCwiY3B1X3VzYWdlX2FjdGl2ZSI6OC43OTk0NjI4ODM4ODk5Mzd9fQo=

###

# json lines
POST http://{{collector_addr}}/api/v1/collect/trace
# adjust according config
X-Erda-Cluster-Key: {{erda_key}}
Authorization: Bearer {{token}}

{"name":"span","timestamp":1644481950000000000,"tags":{"cluster_name":"terminus-dev","host_ip":"10.0.6.221","hostname":"node-010000006221","os":"centos 8.4.2105"},"fields":{"containers":45,"cpu_allocatable":8,"cpu_usage_active":8.799462883889937}}
{"name":"trace","timestamp":1644481950000000000,"tags":{"cluster_name":"terminus-dev","host_ip":"10.0.6.221","hostname":"node-010000006221","os":"centos 8.4.2105"},"fields":{"containers":45,"cpu_allocatable":8,"cpu_usage_active":8.799462883889937}}
