- elasticsearch_active_primary_shards:
    title: "主分片个数"
    metric_names: "es_cluster_health"
    type: "elasticsearch_remove"
    order: 3
    defines:
      avg.active_primary_shards:
        label: ""
        unit: ""
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
    parameters:

