// Copyright (c) 2021 Terminus, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-client. DO NOT EDIT.
// Sources: source.proto

package client

import (
	context "context"

	grpc "github.com/erda-project/erda-infra/pkg/transport/grpc"
	pb "github.com/erda-project/erda-proto-go/core/pipeline/source/pb"
	grpc1 "google.golang.org/grpc"
)

// Client provide all service clients.
type Client interface {
	// SourceService source.proto
	SourceService() pb.SourceServiceClient
}

// New create client
func New(cc grpc.ClientConnInterface) Client {
	return &serviceClients{
		sourceService: pb.NewSourceServiceClient(cc),
	}
}

type serviceClients struct {
	sourceService pb.SourceServiceClient
}

func (c *serviceClients) SourceService() pb.SourceServiceClient {
	return c.sourceService
}

type sourceServiceWrapper struct {
	client pb.SourceServiceClient
	opts   []grpc1.CallOption
}

func (s *sourceServiceWrapper) Create(ctx context.Context, req *pb.PipelineSourceCreateRequest) (*pb.PipelineSourceCreateResponse, error) {
	return s.client.Create(ctx, req, append(grpc.CallOptionFromContext(ctx), s.opts...)...)
}

func (s *sourceServiceWrapper) Update(ctx context.Context, req *pb.PipelineSourceUpdateRequest) (*pb.PipelineSourceUpdateResponse, error) {
	return s.client.Update(ctx, req, append(grpc.CallOptionFromContext(ctx), s.opts...)...)
}

func (s *sourceServiceWrapper) Delete(ctx context.Context, req *pb.PipelineSourceDeleteRequest) (*pb.PipelineSourceDeleteResponse, error) {
	return s.client.Delete(ctx, req, append(grpc.CallOptionFromContext(ctx), s.opts...)...)
}

func (s *sourceServiceWrapper) Get(ctx context.Context, req *pb.PipelineSourceGetRequest) (*pb.PipelineSourceGetResponse, error) {
	return s.client.Get(ctx, req, append(grpc.CallOptionFromContext(ctx), s.opts...)...)
}

func (s *sourceServiceWrapper) List(ctx context.Context, req *pb.PipelineSourceListRequest) (*pb.PipelineSourceListResponse, error) {
	return s.client.List(ctx, req, append(grpc.CallOptionFromContext(ctx), s.opts...)...)
}
