- role: Owner,Lead
  scope: app
  resource: app
  action: CREATE
- role: Owner,Lead
  scope: app
  resource: app
  action: UPDATE
- role: Owner,Lead
  scope: app
  resource: app
  action: DELETE
- role: Owner,Lead,Ops,Dev,QA,Support,Guest
  scope: app
  resource: app
  action: GET
- role: Owner,Lead,Ops,Dev,QA,Support,Guest
  scope: app
  resource: release
  action: LIST

## runtime 权限 start
- scope: app
  resource: runtime-dev
  action: GET
  role: Owner,Lead,Ops,Dev,QA,Support,Guest
- scope: app
  resource: runtime-dev
  action: OPERATE
  role: Owner,Lead,Dev
- scope: app
  resource: runtime-dev
  action: CREATE
  role: Owner,Lead,Dev
- scope: app
  resource: runtime-dev
  action: DELETE
  role: Owner,Lead,Dev
- scope: app
  resource: runtime-test
  action: GET
  role: Owner,Lead,Ops,Dev,QA,Support,Guest
- scope: app
  resource: runtime-test
  action: OPERATE
  role: Owner,Lead,QA
- scope: app
  resource: runtime-test
  action: CREATE
  role: Owner,Lead,QA
- scope: app
  resource: runtime-test
  action: DELETE
  role: Owner,Lead,QA
- scope: app
  resource: runtime-staging
  action: GET
  role: Owner,Lead,Ops,Dev,QA,Support,Guest
- scope: app
  resource: runtime-staging
  action: OPERATE
  role: Owner,Lead
- scope: app
  resource: runtime-staging
  action: CREATE
  role: Owner,Lead
- scope: app
  resource: runtime-staging
  action: DELETE
  role: Owner,Lead
- scope: app
  resource: runtime-prod
  action: GET
  role: Owner,Lead,Ops,Dev,QA,Support,Guest
- scope: app
  resource: runtime-prod
  action: OPERATE
  role: Owner,Lead
- scope: app
  resource: runtime-prod
  action: CREATE
  role: Owner,Lead
- scope: app
  resource: runtime-prod
  action: DELETE
  role: Owner,Lead
## runtime 权限 end

## 分支 权限 start
- role: Owner,Lead,Dev
  scope: app
  resource: feature
  action: OPERATE
- role: Owner,Lead,Ops,Dev,QA,Support,Guest
  scope: app
  resource: feature
  action: GET

- role: Owner,Lead,QA
  scope: app
  resource: develop
  action: OPERATE
- role: Owner,Lead,Ops,Dev,QA,Support,Guest
  scope: app
  resource: develop
  action: GET

- role: Owner,Lead
  scope: app
  resource: release
  action: OPERATE
- role: Owner,Lead,Ops,Dev,QA,Support,Guest
  scope: app
  resource: release
  action: GET

- role: Owner,Lead
  scope: app
  resource: hotfix
  action: OPERATE
- role: Owner,Lead,Ops,Dev,QA,Support,Guest
  scope: app
  resource: hotfix
  action: GET

- role: Owner,Lead
  scope: app
  resource: master
  action: OPERATE
- role: Owner,Lead,Ops,Dev,QA,Support,Guest
  scope: app
  resource: master
  action: GET

- role: Owner,Lead
  scope: app
  resource: support
  action: OPERATE
- role: Owner,Lead,Ops,Dev,QA,Support,Guest
  scope: app
  resource: support
  action: GET
## 分支 权限 end

## 通知 start
- role: Owner,Lead,Dev,QA
  scope: app
  resource: notify
  action: OPERATE
- role: Owner,Lead,Dev,QA
  scope: app
  resource: notify
  action: CREATE
- role: Owner,Lead,Dev,QA
  scope: app
  resource: notify
  action: DELETE
- role: Owner,Lead,Dev,QA
  scope: app
  resource: notify
  action: UPDATE
- role: Owner,Lead,Dev,QA,Support,Guest
  scope: app
  resource: notify
  action: GET
- role: Owner,Lead,Dev,QA,Support
  scope: app
  resource: notify
  action: LIST
## 通知 end

## repo start
- role: Owner,Lead,Dev,QA,Support,Guest
  scope: app
  resource: repo
  action: CLONE
- role: Owner,Lead,Dev,QA
  scope: app
  resource: repo
  action: ARCHIVE
- role: Owner,Lead,Dev,QA
  scope: app
  resource: repo
  action: CREATE_BRANCH
- role: Owner,Lead,Dev,QA
  scope: app
  resource: repo
  action: PUSH
- role: Owner,Lead,Dev,QA
  scope: app
  resource: repo
  action: CREATE_MR
- role: Owner,Lead
  scope: app
  resource: repo
  action: CLOSE_MR
  resource_role: Creator
- role: Owner,Lead
  scope: app
  resource: repo
  action: EDIT_MR
  resource_role: Creator
- role: Owner,Lead,Dev
  scope: app
  resource: repo
  action: CREATE_TAG
- role: Owner,Lead,Dev
  scope: app
  resource: repo
  action: DELETE_TAG
- role: Owner,Lead,Dev
  scope: app
  resource: repo
  action: DELETE_BRANCH
- role: Owner,Lead
  scope: app
  resource: repo
  action: PUSH_PROTECT_BRANCH
- role: Owner,Lead
  scope: app
  resource: repo
  action: PUSH_PROTECT_BRANCH_FORCE
- role: Owner,Lead,Dev,QA
  scope: app
  resource: repo
  action: MERGE_MR
- role: Owner,Lead
  scope: app
  resource: repo
  action: REPO_LOCKED
## repo end

## 工单 start
- role: Owner,Lead,Dev,QA,Support
  scope: app
  resource: ticket
  action: OPERATE
## 工单 End

## 监控 dashboard start
- role: Owner,Lead,Ops,Dev,QA,Support,Guest
  scope: app
  resource: monitor_runtime
  action: GET
- role: Owner,Lead,Support
  scope: app
  resource: monitor_alert_metrics
  action: GET
## 监控 dashboard end

## 成员 start
- role: Owner,Lead
  scope: app
  resource: member
  action: CREATE
- role: Owner,Lead
  scope: app
  resource: member
  action: UPDATE
- role: Owner,Lead,Ops,Dev,QA,Support,Guest
  scope: app
  resource: member
  action: LIST
- role: Owner,Lead
  scope: app
  resource: cloudaccount
  action: OPERATE
- role: Owner,Lead,Ops,Dev,QA,Support
  scope: app
  resource: terminal
  action: OPERATE
## 成员 end

## addon start
- role: Owner,Lead,Ops,Support,Guest
  scope: app
  resource: middleware
  action: GET
- role: Owner,Lead
  scope: app
  resource: customAddon
  action: UPDATE
- role: Owner,Lead
  scope: app
  resource: customAddon
  action: CREATE
- role: Owner,Lead,Ops,Dev,QA,Support,Guest
  scope: app
  resource: addon
  action: GET
- role: Owner,Lead,Dev,QA
  scope: app
  resource: addon
  action: DELETE
## addon end

## TMC start
- role: Owner,Lead,Ops,Dev,QA,Support,Guest
  scope: app
  resource: config-center_group
  action: GET
- role: Owner,Lead,Ops,Dev,QA,Support,Guest
  scope: app
  resource: config-center_properties
  action: GET
- role: Owner,Lead
  scope: app
  resource: config-center_properties
  action: UPDATE
- role: Owner,Lead,Ops,Dev,QA,Support,Guest
  scope: app
  resource: menu
  action: GET
- role: Owner,Lead,Ops,Dev,QA,Support,Guest
  scope: app
  resource: settings
  action: GET
- role: Owner,Lead,Ops,Dev,QA,Support,Guest
  scope: app
  resource: service-mesh_circuit_breaker
  action: GET
- role: Owner,Lead
  scope: app
  resource: service-mesh_circuit_breaker
  action: UPDATE
- role: Owner,Lead,Dev,QA,Support,Guest
  scope: app
  resource: service-mesh_fault_inject
  action: GET
- role: Owner,Lead
  scope: app
  resource: service-mesh_fault_inject
  action: UPDATE
- role: Owner,Lead
  scope: app
  resource: service-mesh_fault_inject
  action: DELETE
## TMC end

- role: Owner,Lead,Dev,QA,Support
  scope: app
  resource: webhook
  action: OPERATE

## certificate start
- role: Owner,Lead,Dev,QA,Support,Guest
  scope: app
  resource: certificate
  action: GET
- role: Owner,Lead,Dev,QA,Support
  scope: app
  resource: certificate
  action: LIST
- role: Owner,Lead,Dev,QA
  scope: app
  resource: quote-certificate
  action: CREATE
- role: Owner,Lead,Dev,QA
  scope: app
  resource: quote-certificate
  action: UPDATE
- role: Owner,Lead,Dev,QA
  scope: app
  resource: quote-certificate
  action: DELETE
- role: Owner,Lead,Dev,QA,Support
  scope: app
  resource: quote-certificate
  action: LIST
## certificate end

## approve start
- role: Owner,Lead,Dev,QA,Support,Guest
  scope: app
  resource: approve
  action: GET
- role: Owner,Lead,Dev,QA,
  scope: app
  resource: approve
  action: CREATE
- role: Owner,Lead,Dev,QA,Support,Guest
  scope: app
  resource: approve
  action: LIST
## approve end

## libReference start
- role: Owner,Lead,Dev,QA
  scope: app
  resource: libReference
  action: CREATE
- role: Owner,Lead,Dev,QA,
  scope: app
  resource: libReference
  action: UPDATE
- role: Owner,Lead,Dev,QA,
  scope: app
  resource: libReference
  action: DELETE
- role: Owner,Lead,Dev,QA,Support,Guest
  scope: app
  resource: libReference
  action: LIST
## libReference end

## config start
- role: Owner,Lead,Dev,QA
  scope: app
  resource: config
  action: CREATE
- role: Owner,Lead,Dev,QA,
  scope: app
  resource: config
  action: UPDATE
- role: Owner,Lead,Dev,QA,
  scope: app
  resource: config
  action: DELETE
- role: Owner,Lead,Dev,QA,Support,Guest
  scope: app
  resource: config
  action: LIST
- role: Owner,Lead,Dev,QA,Support,Guest
  scope: app
  resource: config
  action: GET
## config end

## 分支权限start
- role: Owner,Lead,Dev,QA,Support
  scope: app
  resource: repo
  action: READ
- role: Owner,Lead,Dev,QA,Support,Guest
  scope: app
  resource: pipeline
  action: READ
- role: Owner,Lead,Dev,QA,Support
  scope: app
  resource: normalBranch
  action: READ
- role: Owner,Lead,Dev,QA
  scope: app
  resource: normalBranch
  action: OPERATE
- role: Owner,Lead,Support
  scope: app
  resource: protectedBranch
  action: READ
- role: Owner,Lead
  scope: app
  resource: protectedBranch
  action: OPERATE
- role: Owner,Lead
  scope: app
  resource: branch_rule
  action: OPERATE
  ## 分支权限end

## 应用公开 start
- role: Owner
  scope: app
  resource: app-public
  action: UPDATE
## 应用公开 end
