// Code generated by protoc-gen-go-client. DO NOT EDIT.
// Sources: member.proto

package client

import (
	fmt "fmt"
	reflect "reflect"
	strings "strings"

	servicehub "github.com/erda-project/erda-infra/base/servicehub"
	grpc "github.com/erda-project/erda-infra/pkg/transport/grpc"
	pb "github.com/erda-project/erda-proto-go/msp/member/pb"
	grpc1 "google.golang.org/grpc"
)

var dependencies = []string{
	"grpc-client@erda.msp.member",
	"grpc-client",
}

// +provider
type provider struct {
	client Client
}

func (p *provider) Init(ctx servicehub.Context) error {
	var conn grpc.ClientConnInterface
	for _, dep := range dependencies {
		c, ok := ctx.Service(dep).(grpc.ClientConnInterface)
		if ok {
			conn = c
			break
		}
	}
	if conn == nil {
		return fmt.Errorf("not found connector in (%s)", strings.Join(dependencies, ", "))
	}
	p.client = New(conn)
	return nil
}

var (
	clientsType             = reflect.TypeOf((*Client)(nil)).Elem()
	memberServiceClientType = reflect.TypeOf((*pb.MemberServiceClient)(nil)).Elem()
	memberServiceServerType = reflect.TypeOf((*pb.MemberServiceServer)(nil)).Elem()
)

func (p *provider) Provide(ctx servicehub.DependencyContext, args ...interface{}) interface{} {
	var opts []grpc1.CallOption
	for _, arg := range args {
		if opt, ok := arg.(grpc1.CallOption); ok {
			opts = append(opts, opt)
		}
	}
	switch ctx.Service() {
	case "erda.msp.member-client":
		return p.client
	case "erda.msp.member.MemberService":
		return &memberServiceWrapper{client: p.client.MemberService(), opts: opts}
	case "erda.msp.member.MemberService.client":
		return p.client.MemberService()
	}
	switch ctx.Type() {
	case clientsType:
		return p.client
	case memberServiceClientType:
		return p.client.MemberService()
	case memberServiceServerType:
		return &memberServiceWrapper{client: p.client.MemberService(), opts: opts}
	}
	return p
}

func init() {
	servicehub.Register("erda.msp.member-client", &servicehub.Spec{
		Services: []string{
			"erda.msp.member.MemberService",
			"erda.msp.member.MemberService.client",
			"erda.msp.member-client",
		},
		Types: []reflect.Type{
			clientsType,
			// client types
			memberServiceClientType,
			// server types
			memberServiceServerType,
		},
		OptionalDependencies: dependencies,
		Creator: func() servicehub.Provider {
			return &provider{}
		},
	})
}
