POST http://localhost:9093/api/members
Content-Type: application/json
User-ID: 2

{"userIds":["1000011"],"roles":["Owner"],"scope":{"id":"74","type":"project"},"options":{"rewrite":true}}

###
### iteration 创建
POST {{coreservices}}/api/iterations
Content-Type: application/json
User-ID: 2

{
  "projectID": 18,
  "title": "3.11",
  "content": "3.11 迭代",
  "startedAt": "2019-12-25T13:14:52+08:00",
  "finishedAt": "2020-01-01T13:14:52+08:00"
}


### iteration 删除
DELETE {{coreservices}}/api/iterations/1
User-ID: 2

### iterations 分页查询
GET {{coreservices}}/api/iterations?projectID=18&pageNo=1&pageSize=1
User-ID: 2

### issue 创建
POST {{coreservices}}/api/issues
Content-Type: application/json
User-ID: 2

{
  "projectID": 27,
  "iterationID": 8,
  "type": "BUG",
  "title": "一个小 BUG",
  "content": "看看呢",
  "priority": "URGENT",
  "complexity": "HARD",
  "assignee": "2",
  "testPlanCaseRelIDs": [35]
}

### issue 分页查询
GET {{coreservices}}/api/issues?pageNo=1&pageSize=10&projectID=18&iterationID=1&type=BUG
User-ID: 2

### issue 查询
GET {{coreservices}}/api/issues/102
User-ID: 2

### issue 更新
PUT {{coreservices}}/api/issues/102
User-ID: 2
Internal-Client: true
Content-Type: application/json

{
  "testPlanCaseRelIDs": [35, 36],
  "removeTestPlanCaseRelIDs": false
}

### comment 创建
POST {{coreservices}}/api/issues/25/streams
User-ID: 2
Content-Type: application/json

{
  "content": "你好，我写下一条评论"
}

### issue 事件流
GET {{coreservices}}/api/issues/25/streams?pageNo=1&pageSize=2
User-ID: 2

### 文件上传

POST {{coreservices}}/api/files?fileFrom=issue&public=true&encrypt=true&expiredIn=60s
Content-Type: multipart/form-data; boundary=WebAppBoundary
User-ID: 2

--WebAppBoundary
#Content-Disposition: form-data; name="file"; filename="%E6%88%91%E7%9A%84%E5%90%8D%E5%AD%97.jar"
Content-Disposition: form-data; name="file"; filename="selinux.png"

#< /Users/sfwn/Downloads/我的 名字.jar
< /Users/sfwn/Pictures/selinux.png
--WebAppBoundary--

### 文件下载
GET {{coreservices}}/api/files?file=08dea1998d7541b587851fada3b3648c
User-ID: 2

### 文件下载2
GET {{coreservices}}/api/files/811028d7aacc4bcca0dd6b4d17e4c87f
User-ID: 2

### 文件下载 HEAD
HEAD {{coreservices}}/api/files/02671ea529104961ab8aeb7a22b50bf7
User-ID: 2

### publisher 创建
POST {{coreservices}}/api/publishers
User-ID: 1
Content-Type: application/json

{
  "name": "test-publisher-1000",
  "publisherType": "ORG",
  "orgId": 2
}

### publisher 查询
GET {{coreservices}}/api/publishers/23
User-ID: 1

### publisher 更新
PUT {{coreservices}}/api/publishers
User-ID: 1
Org-ID: 2
Content-Type: application/json

{
  "id": 23,
  "desc": "测试一下"
}

### org nexus 查询
GET {{coreservices}}/api/orgs/1/nexus
Content-Type: application/json
User-ID: 2

{
  "formats": ["npm"],
  "types": ["group", "hosted"]
}

### org update
PUT {{coreservices}}/api/orgs/2
User-ID: 2
Content-Type: application/json

{
}

### org nexus 查看密码
GET {{coreservices}}/api/orgs/actions/show-nexus-password
Content-Type: application/json
User-ID: 2

{
  "orgID": 2,
  "nexusUserIDs": [1,2]
}

### usecase 创建
POST {{coreservices}}/api/usecases
Content-Type: application/json
User-ID: 2

{
  "name":"123",
  "preCondition":"test111",
  "desc":"",
  "stepAndResult":[
    {
      "step":"test1",
      "result":"val1"
    },
    {
      "step":"test2",
      "result":"val2"
    }
  ],
  "priority":"P3",
  "labels":[

  ],
  "attachments":[

  ],
  "bugIds":[

  ],
  "apis":[
    {
      "apiInfo":"{\"headers\":[],\"method\":\"GET\",\"url\":\"http://www.baidu.com\",\"name\":\"test baidu\",\"params\":[],\"body\":{\"type\":\"none\",\"content\":\"\"},\"outParams\":[],\"asserts\":[[]]}"
    }
  ],
  "title":"test1",
  "testSetId":0,
  "projectId":1,
  "selectProjectId":1
}

### usecase 更新
PATCH {{coreservices}}/api/usecases
Content-Type: application/json
User-ID: 2

{
  "id":11,
  "name":"",
  "preCondition":"test222",
  "desc":"",
  "stepAndResult":[
    {
      "step":"test2",
      "result":"val2"
    },
    {
      "step":"test3",
      "result":"val4"
    }
  ],
  "priority":"P2",
  "labels":[

  ],
  "attachments":[

  ],
  "bugIds":[

  ],
  "apis":[
    {
      "apiInfo":"{\"headers\":[],\"method\":\"GET\",\"url\":\"http://www.baidu.com\",\"name\":\"test baidu\",\"params\":[],\"body\":{\"type\":\"test\",\"content\":\"\"},\"outParams\":[],\"asserts\":[[]]}"
    }
  ],
  "title":"test2",
  "testSetId":1,
  "projectId":1,
  "selectProjectId":1
}

### usecase 获取详情
GET {{coreservices}}/api/usecases?id=11&testSetId=0&projectId=1&selectProjectId=1
User-ID: 2

### usecase 批量更新
### 1.指定testSetId更新优先级
PUT {{coreservices}}/api/usecases/batch?recycled=true&usecaseIds=57&projectId=1&testSetId=0&selectProjectId=1
Content-Type: application/json
User-ID: 2

{"testSetId":9,"recycled":false}

### 2.移动到指定测试集
PUT {{coreservices}}/api/usecases/batch?pageNo=1&testSetId=0&projectId=1&selectProjectId=1
Content-Type: application/json
User-ID: 2

{
  "testSetId":1
}

### 3.批量删除测试用例
PUT {{coreservices}}/api/usecases/batch?pageNo=1&testSetId=1&projectId=1&selectProjectId=1&usecaseIds=2&usecaseIds=3
Content-Type: application/json
User-ID: 2

{
  "recycled":true
}

### usecase 批量复制测试用例
POST {{coreservices}}​/api​/usecases​/copy​/batch?pageNo=1&recycled=false&testSetId=1&projectId=1&selectProjectId=1&targetTestSetId=2&targetProjectId=1
Content-Type: application/json
User-ID: 2

{}

### usecase 获取所有测试用例列表
GET {{coreservices}}/api/usecases/actions/list-usecases?pageNo=1&pageSize=10&testSetId=0&projectId=56&selectProjectId=56
User-ID: 2

### usecase 根据搜索优先级条件， 获取测试用例列表
GET {{coreservices}}/api/usecases/actions/list-usecases?pageNo=1&pageSize=10&testSetId=0&projectId=56&selectProjectId=56&prioritys=P3&prioritys=P1
User-ID: 2

### usecase 根据搜索Recycled条件， 获取测试用例列表
GET {{coreservices}}/api/usecases/actions/list-usecases?pageNo=1&pageSize=10&testSetId=0&projectId=56&selectProjectId=56&recycled=true
User-ID: 2

### usecase 根据搜索updatedIds条件， 获取测试用例列表
GET {{coreservices}}/api/usecases/actions/list-usecases?pageNo=1&pageSize=10&testSetId=0&projectId=56&selectProjectId=56&updatedIds=10473&updatedIds=10475
User-ID: 2

### usecase 根据搜索query条件， 获取测试用例列表
GET {{coreservices}}/api/usecases/actions/list-usecases?pageNo=1&pageSize=10&testSetId=0&projectId=56&selectProjectId=56&updatedIds=10473&updatedIds=10475&query=es
User-ID: 2

### usecase 根据testSetId， 获取测试用例列表
GET {{coreservices}}/api/usecases/actions/list-usecases?pageNo=1&pageSize=10&testSetId=0&projectId=1
User-ID: 2

### usecase 导出测试用例列表
GET {{coreservices}}/api/usecases/actions/download-excel?testSetId=0&projectId=56&selectProjectId=56
User-ID: 2

### usecase 删除回收站测试用例列表
DELETE {{coreservices}}/api/usecases/recycle?testSetId=0&projectId=56&selectProjectId=56&usecaseIds=2&usecaseIds=3
User-ID: 2
###

### access
POST {{coreservices}}/api/permissions/actions/access
User-ID: 2020
Content-Type: application/json

{
  "scope": {
    "type": "org",
    "id": "1"
  }
}

### list member
GET {{coreservices}}/api/members?scopeType=org&scopeId=1&role=Manager
User-ID: 2

### 企业设置制品跨集群部署开关
POST {{coreservices}}/api/orgs/1/actions/set-release-cross-cluster?enable=true
User-ID: 1

### usecase 导入测试用例列表
POST {{coreservices}}/api/usecases/actions/upload-excel?projectId=10&selectProjectId=10&targetTestSetId=16
User-ID: 2

### 创建企业
POST {{coreservices}}/api/orgs
User-ID: 1
Content-Type: application/json

{
  "name": "sa",
  "admins": ["1"]
}

### 更新企业
PUT {{coreservices}}/api/orgs/1
User-ID: 2
Content-Type: application/json

{}

### 根据 image 获取 docker 认证信息
GET {{coreservices}}/api/orgs/1/actions/get-nexus-docker-credential-by-image?image=docker-hosted-org-1-nexus-sys.dev.terminus.io/terminus-dice-dev/test-release-cross-cluster:dockerfile-1593662620685244179
Internal-Client: bundle

### 测试用例 - 导入 excel
POST http://localhost:9093/api/issues/actions/import-excel?orgID=1&projectID=11&type=BUG
User-ID: 2
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="测试用例.xlsx"

< /Users/zhouziyue/Downloads/缺陷%20(7).xlsx
--WebAppBoundary--

### 获取公开应用
GET http://localhost:9093/api/applications/actions/list-public-applications?pageSize=30&pageNo=1&isPublic=true&projectId=1
User-ID: 2
Org-ID: 1

### 获取我的应用
GET http://localhost:9093/api/applications/actions/list-my-applications?pageSize=15&pageNo=1&isPublic=false
User-ID: 2
Org-ID: 1
 
### 获取应用
GET http://localhost:9093/api/applications?pageSize=30&pageNo=1&isPublic=true&projectId=5&public=privat
User-ID: 2
Org-ID: 1

###
PUT http://localhost:9093/api/applications/35
User-ID: 2
Org-ID: 1

{
    "name":"dice",
    "mode":"SERVICE",
    "gitRepo":"https://terminus-org.dev.terminus.io/wb/dice-cicd/dice",
    "desc":"",
    "logo":"",
    "isPublic":true
}
###
GET http://localhost:9093/api/issues/actions/bug-percentage?statisticRange=project&rangeId=1
User-ID: 2

###
GET http://localhost:9093/api/issues/actions/bug-status-percentage?statisticRange=project&rangeId=1
User-ID: 2

###
GET http://localhost:9093/api/issues/actions/bug-severity-percentage?statisticRange=project&rangeId=1
User-ID: 2

###
