UPDATE `sp_alert_notify_template` SET `enable` = 0 WHERE `alert_index` = 'machine_disk' AND `enable` = 0;
INSERT `sp_alert_notify_template`(`alert_index`,`alert_type`,`formats`,`name`,`target`,`template`,`title`,`trigger`) VALUES("machine_disk","machine","{\"total_value\":\"size:byte\",\"used_percent_value\":\"percent:2\"}","磁盘容量异常告警","dingding","【磁盘使用率异常告警】\n\n使用率: {{used_percent_value}}\n\n容量: {{total_value}}\n\n集群: {{cluster_name}}\n\n机器: {{host_ip}}\n\n挂载点: {{device}}\n\n组织名称: {{org_name}}\n\n告警级别: {{level}}\n\n时间: {{timestamp}}\n\n[查看详情]({{display_url}})\n\n[查看记录]({{record_url}})\n","【{{cluster_name}}集群机器{{host_ip}}磁盘使用率异常告警】","alert");
INSERT `sp_alert_notify_template`(`alert_index`,`alert_type`,`formats`,`name`,`target`,`template`,`title`,`trigger`) VALUES("machine_disk","machine","{\"total_value\":\"size:byte\",\"used_percent_value\":\"percent:2\"}","磁盘容量异常告警","ticket","【磁盘使用率异常告警】\n\n使用率: {{used_percent_value}}\n\n容量: {{total_value}}\n\n集群: {{cluster_name}}\n\n机器: {{host_ip}}\n\n挂载点: {{device}}\n\n组织名称: {{org_name}}\n\n告警级别: {{level}}\n\n时间: {{timestamp}}\n\n[查看详情]({{display_url}})\n\n[查看记录]({{record_url}})\n","【{{cluster_name}}集群机器{{host_ip}}磁盘使用率异常告警】","alert");
INSERT `sp_alert_notify_template`(`alert_index`,`alert_type`,`formats`,`name`,`target`,`template`,`title`,`trigger`) VALUES("machine_disk","machine","{\"total_value\":\"size:byte\",\"used_percent_value\":\"percent:2\"}","磁盘容量异常告警","email","【磁盘使用率异常告警】\n\n使用率: {{used_percent_value}}\n\n容量: {{total_value}}\n\n集群: {{cluster_name}}\n\n机器: {{host_ip}}\n\n挂载点: {{device}}\n\n组织名称: {{org_name}}\n\n告警级别: {{level}}\n\n时间: {{timestamp}}\n\n[查看详情]({{display_url}})\n\n[查看记录]({{record_url}})\n","【{{cluster_name}}集群机器{{host_ip}}磁盘使用率异常告警】","alert");
INSERT `sp_alert_notify_template`(`alert_index`,`alert_type`,`formats`,`name`,`target`,`template`,`title`,`trigger`) VALUES("machine_disk","machine","{\"total_value\":\"size:byte\",\"used_percent_value\":\"percent:2\"}","磁盘容量异常告警","mbox","【磁盘使用率异常告警】\n\n使用率: {{used_percent_value}}\n\n容量: {{total_value}}\n\n集群: {{cluster_name}}\n\n机器: {{host_ip}}\n\n挂载点: {{device}}\n\n组织名称: {{org_name}}\n\n告警级别: {{level}}\n\n时间: {{timestamp}}\n\n[查看详情]({{display_url}})\n\n[查看记录]({{record_url}})\n","【{{cluster_name}}集群机器{{host_ip}}磁盘使用率异常告警】","alert");
INSERT `sp_alert_notify_template`(`alert_index`,`alert_type`,`formats`,`name`,`target`,`template`,`title`,`trigger`) VALUES("machine_disk","machine","{\"total_value\":\"size:byte\",\"used_percent_value\":\"percent:2\"}","磁盘容量异常告警","webhook","【磁盘使用率异常告警】\n\n使用率: {{used_percent_value}}\n\n容量: {{total_value}}\n\n集群: {{cluster_name}}\n\n机器: {{host_ip}}\n\n挂载点: {{device}}\n\n组织名称: {{org_name}}\n\n告警级别: {{level}}\n\n时间: {{timestamp}}\n\n[查看详情]({{display_url}})\n\n[查看记录]({{record_url}})\n","【{{cluster_name}}集群机器{{host_ip}}磁盘使用率异常告警】","alert");
INSERT `sp_alert_notify_template`(`alert_index`,`alert_type`,`formats`,`name`,`target`,`template`,`title`,`trigger`) VALUES("machine_disk","machine","{\"total_value\":\"size:byte\",\"used_percent_value\":\"percent:2\"}","磁盘容量异常告警","dingtalk_work_notice","【磁盘使用率异常告警】\n\n使用率: {{used_percent_value}}\n\n容量: {{total_value}}\n\n集群: {{cluster_name}}\n\n机器: {{host_ip}}\n\n挂载点: {{device}}\n\n组织名称: {{org_name}}\n\n告警级别: {{level}}\n\n时间: {{timestamp}}\n\n[查看详情]({{display_url}})\n\n[查看记录]({{record_url}})\n","【{{cluster_name}}集群机器{{host_ip}}磁盘使用率异常告警】","alert");
INSERT `sp_alert_notify_template`(`alert_index`,`alert_type`,`formats`,`name`,`target`,`template`,`title`,`trigger`) VALUES("machine_disk","machine","{\"total_value\":\"size:byte\",\"used_percent_value\":\"percent:2\"}","磁盘容量异常告警","sms","{{cluster_name}}集群机器{{host_ip}}触发磁盘使用率异常告警，组织名称: {{org_name}}，使用率: {{used_percent_value}}，告警级别: {{level}}\n","【{{cluster_name}}集群机器{{host_ip}}磁盘使用率异常告警】","alert");
INSERT `sp_alert_notify_template`(`alert_index`,`alert_type`,`formats`,`name`,`target`,`template`,`title`,`trigger`) VALUES("machine_disk","machine","{\"total_value\":\"size:byte\",\"used_percent_value\":\"percent:2\"}","磁盘容量异常告警","vms","{{cluster_name}}集群机器{{host_ip}}触发磁盘使用率异常告警，组织名称: {{org_name}}，使用率: {{used_percent_value}}，告警级别: {{level}}\n","【{{cluster_name}}集群机器{{host_ip}}磁盘使用率异常告警】","alert");
INSERT `sp_alert_notify_template`(`alert_index`,`alert_type`,`formats`,`name`,`target`,`template`,`title`,`trigger`) VALUES("machine_disk","machine","{\"trigger_duration\":\"time:ms\",\"used_percent_value\":\"percent:2\"}","磁盘容量异常恢复","dingding","【磁盘使用率异常恢复】\n\n使用率: {{used_percent_value}}\n\n集群: {{cluster_name}}\n\n机器: {{host_ip}}\n\n挂载点: {{device}}\n\n组织名称: {{org_name}}\n\n持续时间: {{trigger_duration}}\n\n恢复时间: {{timestamp}}\n\n[查看记录]({{record_url}})\n","【{{cluster_name}}集群机器{{host_ip}}磁盘使用率异常恢复】","recover");
INSERT `sp_alert_notify_template`(`alert_index`,`alert_type`,`formats`,`name`,`target`,`template`,`title`,`trigger`) VALUES("machine_disk","machine","{\"trigger_duration\":\"time:ms\",\"used_percent_value\":\"percent:2\"}","磁盘容量异常恢复","ticket","【磁盘使用率异常恢复】\n\n使用率: {{used_percent_value}}\n\n集群: {{cluster_name}}\n\n机器: {{host_ip}}\n\n挂载点: {{device}}\n\n组织名称: {{org_name}}\n\n持续时间: {{trigger_duration}}\n\n恢复时间: {{timestamp}}\n\n[查看记录]({{record_url}})\n","【{{cluster_name}}集群机器{{host_ip}}磁盘使用率异常恢复】","recover");
INSERT `sp_alert_notify_template`(`alert_index`,`alert_type`,`formats`,`name`,`target`,`template`,`title`,`trigger`) VALUES("machine_disk","machine","{\"trigger_duration\":\"time:ms\",\"used_percent_value\":\"percent:2\"}","磁盘容量异常恢复","email","【磁盘使用率异常恢复】\n\n使用率: {{used_percent_value}}\n\n集群: {{cluster_name}}\n\n机器: {{host_ip}}\n\n挂载点: {{device}}\n\n组织名称: {{org_name}}\n\n持续时间: {{trigger_duration}}\n\n恢复时间: {{timestamp}}\n\n[查看记录]({{record_url}})\n","【{{cluster_name}}集群机器{{host_ip}}磁盘使用率异常恢复】","recover");
INSERT `sp_alert_notify_template`(`alert_index`,`alert_type`,`formats`,`name`,`target`,`template`,`title`,`trigger`) VALUES("machine_disk","machine","{\"trigger_duration\":\"time:ms\",\"used_percent_value\":\"percent:2\"}","磁盘容量异常恢复","mbox","【磁盘使用率异常恢复】\n\n使用率: {{used_percent_value}}\n\n集群: {{cluster_name}}\n\n机器: {{host_ip}}\n\n挂载点: {{device}}\n\n组织名称: {{org_name}}\n\n持续时间: {{trigger_duration}}\n\n恢复时间: {{timestamp}}\n\n[查看记录]({{record_url}})\n","【{{cluster_name}}集群机器{{host_ip}}磁盘使用率异常恢复】","recover");
INSERT `sp_alert_notify_template`(`alert_index`,`alert_type`,`formats`,`name`,`target`,`template`,`title`,`trigger`) VALUES("machine_disk","machine","{\"trigger_duration\":\"time:ms\",\"used_percent_value\":\"percent:2\"}","磁盘容量异常恢复","webhook","【磁盘使用率异常恢复】\n\n使用率: {{used_percent_value}}\n\n集群: {{cluster_name}}\n\n机器: {{host_ip}}\n\n挂载点: {{device}}\n\n组织名称: {{org_name}}\n\n持续时间: {{trigger_duration}}\n\n恢复时间: {{timestamp}}\n\n[查看记录]({{record_url}})\n","【{{cluster_name}}集群机器{{host_ip}}磁盘使用率异常恢复】","recover");
INSERT `sp_alert_notify_template`(`alert_index`,`alert_type`,`formats`,`name`,`target`,`template`,`title`,`trigger`) VALUES("machine_disk","machine","{\"trigger_duration\":\"time:ms\",\"used_percent_value\":\"percent:2\"}","磁盘容量异常恢复","dingtalk_work_notice","【磁盘使用率异常恢复】\n\n使用率: {{used_percent_value}}\n\n集群: {{cluster_name}}\n\n机器: {{host_ip}}\n\n挂载点: {{device}}\n\n组织名称: {{org_name}}\n\n持续时间: {{trigger_duration}}\n\n恢复时间: {{timestamp}}\n\n[查看记录]({{record_url}})\n","【{{cluster_name}}集群机器{{host_ip}}磁盘使用率异常恢复】","recover");
INSERT `sp_alert_notify_template`(`alert_index`,`alert_type`,`formats`,`name`,`target`,`template`,`title`,`trigger`) VALUES("machine_disk","machine","{\"trigger_duration\":\"time:ms\",\"used_percent_value\":\"percent:2\"}","磁盘容量异常恢复","sms","{{cluster_name}}集群机器{{host_ip}}触发磁盘使用率异常告警恢复，组织名称: {{org_name}}，使用率: {{used_percent_value}}\n","【{{cluster_name}}集群机器{{host_ip}}磁盘使用率异常恢复】","recover");
INSERT `sp_alert_notify_template`(`alert_index`,`alert_type`,`formats`,`name`,`target`,`template`,`title`,`trigger`) VALUES("machine_disk","machine","{\"trigger_duration\":\"time:ms\",\"used_percent_value\":\"percent:2\"}","磁盘容量异常恢复","vms","{{cluster_name}}集群机器{{host_ip}}触发磁盘使用率异常告警恢复，组织名称: {{org_name}}，使用率: {{used_percent_value}}\n","【{{cluster_name}}集群机器{{host_ip}}磁盘使用率异常恢复】","recover");

