### List release rules
GET https://openapi.dev.terminus.io/api/release-rules?projectID=66
Org-ID: 1
Cookie: taid=f9902540-58d3-11ec-85d9-c226b743fa5b; u_c_captain_hkci_local=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2dpbiIsInBhdGgiOiIvIiwidG9rZW5LZXkiOiI4Zjc3MWU0ZWZmMDExOTdmNjUxZjU0MGM1ODNiZDc4MGI0NWI4YzJhMmFmMWZlMWJmYjNiYzBkZTZjYzc0YThlIiwibmJmIjoxNjQwNTc0MTE5LCJkb21haW4iOiJ0ZXJtaW51cy5pbyIsImlzcyI6ImRyYWNvIiwidGVuYW50SWQiOjEsImV4cGlyZV90aW1lIjo2MDQ4MDAsImV4cCI6MTY0MTE3ODkxOSwiaWF0IjoxNjQwNTc0MTE5fQ.T2AIuqDjVjRJ1gRtv1ekU2R2V2P8a5vDq9b6fOLz_uc; u_c_captain_dev_local=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2dpbiIsInBhdGgiOiIvIiwidG9rZW5LZXkiOiIwMDBiZDRjZDI5Yjc1MmE0Y2VlNzZiYmJjOTBjYjE0N2MyZDE3Nzg4ZDFkYTQ4YjMzYTE2ZGJmYWEyMzAyZjYwIiwibmJmIjoxNjQwNjk1NDMwLCJkb21haW4iOiJ0ZXJtaW51cy5pbyIsImlzcyI6ImRyYWNvIiwidGVuYW50SWQiOjEsImV4cGlyZV90aW1lIjo2MDQ4MDAsImV4cCI6MTY0MTMwMDIzMCwiaWF0IjoxNjQwNjk1NDMwfQ.DqVouwh7_hfb3ljLk3iRW9I9cxk-Al--yfYM640BlQI; OPENAPISESSION=1bdf109f-b7f5-4eb6-9569-8134a26639b9; OPENAPI-CSRF-TOKEN=OGJg59Do7DJWFCwUMVGplERHagioGkBC

### Create release rule
POST http://openapi.dev.terminus.io/api/release-rules?projectID=66
Org-ID: 1
Cookie: taid=f9902540-58d3-11ec-85d9-c226b743fa5b; u_c_captain_hkci_local=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2dpbiIsInBhdGgiOiIvIiwidG9rZW5LZXkiOiI4Zjc3MWU0ZWZmMDExOTdmNjUxZjU0MGM1ODNiZDc4MGI0NWI4YzJhMmFmMWZlMWJmYjNiYzBkZTZjYzc0YThlIiwibmJmIjoxNjQwNTc0MTE5LCJkb21haW4iOiJ0ZXJtaW51cy5pbyIsImlzcyI6ImRyYWNvIiwidGVuYW50SWQiOjEsImV4cGlyZV90aW1lIjo2MDQ4MDAsImV4cCI6MTY0MTE3ODkxOSwiaWF0IjoxNjQwNTc0MTE5fQ.T2AIuqDjVjRJ1gRtv1ekU2R2V2P8a5vDq9b6fOLz_uc; u_c_captain_dev_local=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2dpbiIsInBhdGgiOiIvIiwidG9rZW5LZXkiOiIwMDBiZDRjZDI5Yjc1MmE0Y2VlNzZiYmJjOTBjYjE0N2MyZDE3Nzg4ZDFkYTQ4YjMzYTE2ZGJmYWEyMzAyZjYwIiwibmJmIjoxNjQwNjk1NDMwLCJkb21haW4iOiJ0ZXJtaW51cy5pbyIsImlzcyI6ImRyYWNvIiwidGVuYW50SWQiOjEsImV4cGlyZV90aW1lIjo2MDQ4MDAsImV4cCI6MTY0MTMwMDIzMCwiaWF0IjoxNjQwNjk1NDMwfQ.DqVouwh7_hfb3ljLk3iRW9I9cxk-Al--yfYM640BlQI; OPENAPISESSION=1bdf109f-b7f5-4eb6-9569-8134a26639b9; OPENAPI-CSRF-TOKEN=OGJg59Do7DJWFCwUMVGplERHagioGkBC
Content-Type: application/json

{
  "pattern": "cmc/*",
  "is_enabled": true
}

