### List release rules
GET https://openapi.dev.terminus.io/api/release-rules?projectID=66
Org-ID: 1
Cookie:

### Create release rule
POST http://openapi.dev.terminus.io/api/release-rules?projectID=66
Org-ID: 1
Cookie:
Content-Type: application/json

{
  "pattern": "cmc/*",
  "is_enabled": true
}

