- mysql_innodb_data_written:
    title: "INNODB写速度"
    metric_names: "mysql"
    type: "mysql"
    order: 15
    defines:
      diffps.innodb_data_written:
        label: "写速度"
        unit: "B/s"
        unit_type: "TRAFFIC"
        axis_index: 0
        chart_type: "line"
    parameters:
      group:
        - "server"

