- mysql_tps:
    title: "TPS"
    metric_names: "mysql"
    type: "mysql"
    order: 5
    defines:
      diffps.(com_commit+com_rollback):
        label: ""
        unit: "次/s"
        unit_type: "NPS"
        axis_index: 0
        chart_type: "line"
    parameters:
      group:
        - "server"

