// create export records
POST https://erda.dev.terminus.io/api/erda/apim/exports
Content-Type: application/json
Cookie:

{"versionID": 1, "specProtocol": "csv"}

###
// list export reocrds
GET https://erda.dev.terminus.io/api/erda/apim/exports
Accept: application/json
Cookie:

###
// delete record
DELETE https://erda.dev.terminus.io/api/erda/apim/exports/1383f4f0-c704-4d82-a5a1-9558a217a938
Accept: application/json
Cookie:
