## 资源报表 按项目聚合
GET http://openapi.dev.terminus.io/api/resource-overview/report-table?clusterName=terminus-dev&cpuPerNode=8&memPerNode=32&groupBy=project
lang: zh-CN
org: erda
accept-language: zh-CN,zh;q=0.9
cookie:

### 资源报表 按所有者聚合
GET http://openapi.dev.terminus.io/api/resource-overview/report-table?clusterName=terminus-dev&cpuPerNode=8&memPerNode=32&groupBy=owner
Accept: application/json
accept: application/vnd.dice+json;version=1.0
lang: zh-CN
org: erda
accept-language: zh-CN,zh;q=0.9
cookie:

### 项目资源趋势
GET http://openapi.hkci.terminus.io/api/resource-overview/project-trend?clusterName=terminus-dev&start=1637810269000&end=1638415069000&interval=day&scope=project&scopeID=1546&resourceType=cpu
lang: zh-CN
org-id: 1
user-id: 2
cookie:

> {%
client.test("项目资源趋势", function (){
    client.assert(response.status===200, "Response status is not 200");
});
%}