// Code generated by protoc-gen-go-register. DO NOT EDIT.
// Sources: org_client.proto

package pb

import (
	reflect "reflect"

	transport "github.com/erda-project/erda-infra/pkg/transport"
)

// RegisterOrgClientServiceImp org_client.proto
func RegisterOrgClientServiceImp(regester transport.Register, srv OrgClientServiceServer, opts ...transport.ServiceOption) {
	_ops := transport.DefaultServiceOptions()
	for _, op := range opts {
		op(_ops)
	}
	RegisterOrgClientServiceHandler(regester, OrgClientServiceHandler(srv), _ops.HTTP...)
	RegisterOrgClientServiceServer(regester, srv, _ops.GRPC...)
}

// ServiceNames return all service names
func ServiceNames(svr ...string) []string {
	return append(svr,
		"erda.core.hepa.org_client.OrgClientService",
	)
}

var (
	orgClientServiceClientType  = reflect.TypeOf((*OrgClientServiceClient)(nil)).Elem()
	orgClientServiceServerType  = reflect.TypeOf((*OrgClientServiceServer)(nil)).Elem()
	orgClientServiceHandlerType = reflect.TypeOf((*OrgClientServiceHandler)(nil)).Elem()
)

// OrgClientServiceClientType .
func OrgClientServiceClientType() reflect.Type { return orgClientServiceClientType }

// OrgClientServiceServerType .
func OrgClientServiceServerType() reflect.Type { return orgClientServiceServerType }

// OrgClientServiceHandlerType .
func OrgClientServiceHandlerType() reflect.Type { return orgClientServiceHandlerType }

func Types() []reflect.Type {
	return []reflect.Type{
		// client types
		orgClientServiceClientType,
		// server types
		orgClientServiceServerType,
		// handler types
		orgClientServiceHandlerType,
	}
}
