- ai_nodejs_async_res:
    title: "Async Resources"
    metric_names: "nodejs_async_resource"
    type: "ai"
    order: 0
    defines:
      sum.count:
        label: "count"
        unit: "B"
        unit_type: "count"
        axis_index: 0
        chart_type: "line"
    parameters:

