- ai_web_cpm:
    title: "吞吐量"
    metric_names: "application_http"
    type: "ai"
    order: 0
    defines:
      sumCpm.elapsed_count:
        label: "吞吐量"
        unit: "cpm"
        unit_type: ""
        axis_index: 0
        chart_type: "line"
    parameters:

