// Copyright (c) 2021 Terminus, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-register. DO NOT EDIT.
// Sources: trigger.proto

package pb

import (
	reflect "reflect"

	transport "github.com/erda-project/erda-infra/pkg/transport"
)

// RegisterTriggerServiceImp trigger.proto
func RegisterTriggerServiceImp(regester transport.Register, srv TriggerServiceServer, opts ...transport.ServiceOption) {
	_ops := transport.DefaultServiceOptions()
	for _, op := range opts {
		op(_ops)
	}
	RegisterTriggerServiceHandler(regester, TriggerServiceHandler(srv), _ops.HTTP...)
	RegisterTriggerServiceServer(regester, srv, _ops.GRPC...)
}

// ServiceNames return all service names
func ServiceNames(svr ...string) []string {
	return append(svr,
		"erda.core.pipeline.trigger.TriggerService",
	)
}

var (
	triggerServiceClientType  = reflect.TypeOf((*TriggerServiceClient)(nil)).Elem()
	triggerServiceServerType  = reflect.TypeOf((*TriggerServiceServer)(nil)).Elem()
	triggerServiceHandlerType = reflect.TypeOf((*TriggerServiceHandler)(nil)).Elem()
)

// TriggerServiceClientType .
func TriggerServiceClientType() reflect.Type { return triggerServiceClientType }

// TriggerServiceServerType .
func TriggerServiceServerType() reflect.Type { return triggerServiceServerType }

// TriggerServiceHandlerType .
func TriggerServiceHandlerType() reflect.Type { return triggerServiceHandlerType }

func Types() []reflect.Type {
	return []reflect.Type{
		// client types
		triggerServiceClientType,
		// server types
		triggerServiceServerType,
		// handler types
		triggerServiceHandlerType,
	}
}
