### create key
POST {{kms}}/api/kms
Content-Type: application/json
Internal-Client: bundle

{
}

### encrypt
POST {{kms}}/api/kms/encrypt
Content-Type: application/json
Internal-Client: bundle

{
  "keyID": "b3bfc57cf2c946e98a2f66e54b5138c0",
  "plaintextBase64": "aGVsbG8="
}

### decrypt
POST {{kms}}/api/kms/decrypt
Content-Type: application/json
Internal-Client: bundle

{
  "keyID": "b3bfc57cf2c946e98a2f66e54b5138c0",
  "ciphertextBase64": "MDMyNWZkMzE1ODc3NGIwNDRjNmExMjA1YWMwOTEyMzI1YTgwMTIDr+PHXhhOU0qKWBlreE6s6icyD3i7T7zPJH60R8UX2fs="
}

### generate data key
POST {{kms}}/api/kms/generate-data-key
Content-Type: application/json
Internal-Client: bundle

{
  "keyID": "03bc9037da184599bf3a077eb6554a80"
}

### rotate key version
POST {{kms}}/api/kms/rotate-key-version
Content-Type: application/json
Internal-Client: bundle

{
  "keyID": "03bc9037da184599bf3a077eb6554a80"
}

### describe key
GET {{kms}}/api/kms/describe-key
Content-Type: application/json
Internal-Client: bundle

{
  "keyID": "e7459fd176d7437c96cc096db42e44ec"
}