- machine_tcp:
    title: "TCP链接数"
    metric_names: "netstat"
    type: "machine_remove"
    order: 11
    defines:
      sum.tcp_none:
        label: "tcp_none"
        unit: "个"
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
      sum.tcp_syn_sent:
        label: "tcp_syn_sent"
        unit: "个"
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
      sum.udp_socket:
        label: "udp_socket"
        unit: "个"
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
      sum.tcp_close_wait:
        label: "tcp_close_wait"
        unit: "个"
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
      sum.tcp_established:
        label: "tcp_established"
        unit: "个"
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
      sum.tcp_fin_wait2:
        label: "tcp_fin_wait2"
        unit: "个"
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
      sum.tcp_last_ack:
        label: "tcp_last_ack"
        unit: "个"
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
      sum.tcp_close:
        label: "tcp_close"
        unit: "个"
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
      sum.tcp_closing:
        label: "tcp_closing"
        unit: "个"
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
      sum.tcp_fin_wait1:
        label: "tcp_fin_wait1"
        unit: "个"
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
      sum.tcp_syn_recv:
        label: "tcp_syn_recv"
        unit: "个"
        unit_type: "NUMBER"
        axis_index: 0
        chart_type: "line"
    parameters:

