name: "Application Service Node"
tags:
    application_id:
        name: "Application ID"
    application_name:
        name: "Application Name"
    cluster_name:
        name: "Cluster Name"
    host:
        name: "Host"
    host_ip:
        name: "Host IP"
    instance_id:
        name: "Instance ID"
    org_name:
        name: "Org Name"
    project_id:
        name: "Project ID"
    project_name:
        name: "Project Name"
    runtime_id:
        name: "Runtime ID"
    runtime_name:
        name: "Runtime Name"
    service_agent_name:
        name: "Service Agent Name"
    service_agent_os_info:
        name: "Service Agent OS Info"
    service_agent_platform:
        name: "Service Agent Platform"
    service_agent_version:
        name: "Service Agent Version"
    service_id:
        name: "Service ID"
    service_instance_id:
        name: "Service Instance ID"
    service_ip:
        name: "Service IP"
    service_name:
        name: "Service Name"
    terminus_key:
        name: "Terminus Key"
    workspace:
        name: "Workspace"
fields:
    start_time_count:
        type: "number"
        name: "Start Time Count"
        unit: 
    start_time_max:
        type: "number"
        name: "Start Time Maximum"
        unit: 
    start_time_mean:
        type: "number"
        name: "Start Time Mean"
        unit: 
    start_time_min:
        type: "number"
        name: "Start Time Minimum"
        unit: 
    start_time_sum:
        type: "number"
        name: "Start Time Sum"
        unit: 

