version: '1.0'

stages:
- name: repo
  tasks:
  - get: repo
    params:
      depth: 1

- name: sonar
  tasks:
  - put: sonar

- name: buildpack
  tasks:
  - aggregate:
    - put: bp-backend
      params:
        only_build: false
    - put: bp-frontend
      params:
        only_build: false

- name: ability
tasks:
- put: ability
  params:
    dice_yml: repo/dice.yml
    init_sql: repo/db
    replacement_images:
    - bp-backend/pack-result
    - bp-frontend/pack-result
    ability_yml: repo/ability.yml
    app: bp-backend/app

- name: dicehub
  tasks:
  - put: dice-hub
    params:
      dice_yml: repo/dice.yml
      #dice_test_yml: repo/dice_test.yml
      #dice_development_yml: repo/dice_development.yml
      #dice_staging_yml: repo/dice_staging.yml
      #dice_production_yml: repo/dice_production.yml
      init_sql: repo/db
      replacement_images:
      - bp-backend/pack-result
      - bp-frontend/pack-result

- name: deploy
  tasks:
  - put: deploy
    params:
      #dice_yml: repo/dice.yml
      #init_sql: repo/db
      time_out: 600
      #replacement_images:
      #- bp-backend/pack-result
      #- bp-frontend/pack-result


resources:
- name: repo
  type: git
  source:
    uri: http://git.terminus.io/buildpacks/dice-bpack-termjava
    branch: master

- name: bp-backend
  type: buildpack
  source:
    context: repo/services/showcase
    modules:
    - name: blog-web
    - name: blog-service
      path: blog-service/blog-service-impl
    - name: user-service
      path: user-service/user-service-impl

- name: bp-frontend
  type: buildpack
  source:
    context: repo/endpoints/showcase-front
    modules:
    - name: showcase-front

- name: ability
  type: ability-test
  source:

- name: dice-hub
  type: dicehub-test


- name: deploy
  type: dice-test

- name: sonar
  type: sonar-test
  source:
    context: services/showcase,endpoints/showcase-front

resource_types:
- name: sonar-test
  type: docker-image
  source:
    repository: registry.cn-hangzhou.aliyuncs.com/terminus/sonar-resource
    tag: test

- name: dicehub-test
  type: docker-image
  source:
    repository: registry.cn-hangzhou.aliyuncs.com/terminus/dicehub-resource
    tag: test
