// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Source: guide.proto

package pb

import (
	context "context"

	transport "github.com/erda-project/erda-infra/pkg/transport"
	grpc1 "github.com/erda-project/erda-infra/pkg/transport/grpc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion5

// GuideServiceClient is the client API for GuideService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuideServiceClient interface {
	ListGuide(ctx context.Context, in *ListGuideRequest, opts ...grpc.CallOption) (*ListGuideResponse, error)
	JudgeCanCreatePipeline(ctx context.Context, in *JudgeCanCreatePipelineRequest, opts ...grpc.CallOption) (*JudgeCanCreatePipelineResponse, error)
}

type guideServiceClient struct {
	cc grpc1.ClientConnInterface
}

func NewGuideServiceClient(cc grpc1.ClientConnInterface) GuideServiceClient {
	return &guideServiceClient{cc}
}

func (c *guideServiceClient) ListGuide(ctx context.Context, in *ListGuideRequest, opts ...grpc.CallOption) (*ListGuideResponse, error) {
	out := new(ListGuideResponse)
	err := c.cc.Invoke(ctx, "/erda.dop.guide.GuideService/ListGuide", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideServiceClient) JudgeCanCreatePipeline(ctx context.Context, in *JudgeCanCreatePipelineRequest, opts ...grpc.CallOption) (*JudgeCanCreatePipelineResponse, error) {
	out := new(JudgeCanCreatePipelineResponse)
	err := c.cc.Invoke(ctx, "/erda.dop.guide.GuideService/JudgeCanCreatePipeline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuideServiceServer is the server API for GuideService service.
// All implementations should embed UnimplementedGuideServiceServer
// for forward compatibility
type GuideServiceServer interface {
	ListGuide(context.Context, *ListGuideRequest) (*ListGuideResponse, error)
	JudgeCanCreatePipeline(context.Context, *JudgeCanCreatePipelineRequest) (*JudgeCanCreatePipelineResponse, error)
}

// UnimplementedGuideServiceServer should be embedded to have forward compatible implementations.
type UnimplementedGuideServiceServer struct {
}

func (*UnimplementedGuideServiceServer) ListGuide(context.Context, *ListGuideRequest) (*ListGuideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGuide not implemented")
}
func (*UnimplementedGuideServiceServer) JudgeCanCreatePipeline(context.Context, *JudgeCanCreatePipelineRequest) (*JudgeCanCreatePipelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JudgeCanCreatePipeline not implemented")
}

func RegisterGuideServiceServer(s grpc1.ServiceRegistrar, srv GuideServiceServer, opts ...grpc1.HandleOption) {
	s.RegisterService(_get_GuideService_serviceDesc(srv, opts...), srv)
}

var _GuideService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "erda.dop.guide.GuideService",
	HandlerType: (*GuideServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "guide.proto",
}

func _get_GuideService_serviceDesc(srv GuideServiceServer, opts ...grpc1.HandleOption) *grpc.ServiceDesc {
	h := grpc1.DefaultHandleOptions()
	for _, op := range opts {
		op(h)
	}

	_GuideService_ListGuide_Handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.ListGuide(ctx, req.(*ListGuideRequest))
	}
	var _GuideService_ListGuide_info transport.ServiceInfo
	if h.Interceptor != nil {
		_GuideService_ListGuide_info = transport.NewServiceInfo("erda.dop.guide.GuideService", "ListGuide", srv)
		_GuideService_ListGuide_Handler = h.Interceptor(_GuideService_ListGuide_Handler)
	}

	_GuideService_JudgeCanCreatePipeline_Handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.JudgeCanCreatePipeline(ctx, req.(*JudgeCanCreatePipelineRequest))
	}
	var _GuideService_JudgeCanCreatePipeline_info transport.ServiceInfo
	if h.Interceptor != nil {
		_GuideService_JudgeCanCreatePipeline_info = transport.NewServiceInfo("erda.dop.guide.GuideService", "JudgeCanCreatePipeline", srv)
		_GuideService_JudgeCanCreatePipeline_Handler = h.Interceptor(_GuideService_JudgeCanCreatePipeline_Handler)
	}

	var serviceDesc = _GuideService_serviceDesc
	serviceDesc.Methods = []grpc.MethodDesc{
		{
			MethodName: "ListGuide",
			Handler: func(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
				in := new(ListGuideRequest)
				if err := dec(in); err != nil {
					return nil, err
				}
				if interceptor == nil && h.Interceptor == nil {
					return srv.(GuideServiceServer).ListGuide(ctx, in)
				}
				if h.Interceptor != nil {
					ctx = context.WithValue(ctx, transport.ServiceInfoContextKey, _GuideService_ListGuide_info)
				}
				if interceptor == nil {
					return _GuideService_ListGuide_Handler(ctx, in)
				}
				info := &grpc.UnaryServerInfo{
					Server:     srv,
					FullMethod: "/erda.dop.guide.GuideService/ListGuide",
				}
				return interceptor(ctx, in, info, _GuideService_ListGuide_Handler)
			},
		},
		{
			MethodName: "JudgeCanCreatePipeline",
			Handler: func(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
				in := new(JudgeCanCreatePipelineRequest)
				if err := dec(in); err != nil {
					return nil, err
				}
				if interceptor == nil && h.Interceptor == nil {
					return srv.(GuideServiceServer).JudgeCanCreatePipeline(ctx, in)
				}
				if h.Interceptor != nil {
					ctx = context.WithValue(ctx, transport.ServiceInfoContextKey, _GuideService_JudgeCanCreatePipeline_info)
				}
				if interceptor == nil {
					return _GuideService_JudgeCanCreatePipeline_Handler(ctx, in)
				}
				info := &grpc.UnaryServerInfo{
					Server:     srv,
					FullMethod: "/erda.dop.guide.GuideService/JudgeCanCreatePipeline",
				}
				return interceptor(ctx, in, info, _GuideService_JudgeCanCreatePipeline_Handler)
			},
		},
	}
	return &serviceDesc
}
