// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dashboard.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GetClustersResourcesRequest) Validate() error {
	return nil
}
func (this *GetClusterResourcesResponse) Validate() error {
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ClusterResourceDetail) Validate() error {
	return nil
}
func (this *GetNamespacesResourcesRequest) Validate() error {
	return nil
}
func (this *GetNamespacesResourcesResponse) Validate() error {
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *NamespaceResourceDetail) Validate() error {
	return nil
}
