@url = http://localhost:7096/api

### GET addon metrics
GET {{url}}/system/addon/metrics/mysql/histogram
    ?start=before_1h
    &end=now
    &points=60
    &filter_addon_id=zd2548efcabd24d67a4381fe27d0c4fd4
Org-ID: 1
User-ID: 1100
Lang: en


### GET addon metrics
GET {{url}}/system/pod/status
    ?timestamp=1591264766764
    &clusterName=terminus-test
    &name=dice-monitor-7dcf7985d7-r98gp
Org-ID: 1
User-ID: 1100
Lang: en
