POST http://localhost:7076/api/v1/collect/metrics
Content-Type: application/json
# adjust according config
X-Erda-Cluster-Key: erda-op
Authorization: Bearer lMh8UjcN2WsCq7959Yb4vCDf

{
  "metrics": [
    {
      "name": "host_summary",
      "timestamp": 1644481950000000000,
      "tags": {
        "cluster_name": "terminus-dev",
        "host": "telegraf-00e2f41199-fpqsc",
        "host_ip": "10.0.6.221",
        "hostname": "node-010000006221",
        "kernel_version": "4.18.0-305.3.1.el8.x86_64",
        "labels": "bigdata-job,location-cluster-service,pack-job,workspace-test,workspace-prod,org-sfwn-org,workspace-dev,org-erda,org-terminus,stateless-service,stateful-service,job,workspace-staging",
        "mem": "31",
        "n_cpus": "8",
        "org_name": "erda",
        "os": "centos 8.4.2105"
      },
      "fields": {
        "containers": 45,
        "cpu_allocatable": 8,
        "cpu_cores_usage": 0.703957030711195,
        "cpu_limit_total": 0,
        "cpu_origin_total": 0,
        "cpu_request_percent": 0,
        "cpu_request_total": 0,
        "cpu_usage_active": 8.799462883889937
      }
    },
    {
      "name": "host_summary",
      "timestamp": 1644481960000000000,
      "tags": {
        "cluster_name": "terminus-dev",
        "host": "telegraf-00e2f41199-fpqsc",
        "host_ip": "10.0.6.221",
        "hostname": "node-010000006221",
        "kernel_version": "4.18.0-305.3.1.el8.x86_64",
        "labels": "bigdata-job,location-cluster-service,pack-job,workspace-test,workspace-prod,org-sfwn-org,workspace-dev,org-erda,org-terminus,stateless-service,stateful-service,job,workspace-staging",
        "mem": "31",
        "n_cpus": "8",
        "org_name": "erda",
        "os": "centos 8.4.2105"
      },
      "fields": {
        "containers": 45,
        "cpu_allocatable": 8,
        "cpu_cores_usage": 0.703957030711195,
        "cpu_limit_total": 0,
        "cpu_origin_total": 0,
        "cpu_request_percent": 0,
        "cpu_request_total": 0,
        "cpu_usage_active": 8.799462883889937
      }
    }
  ]
}