- name: "kubernetes组件实例Ready状态异常"
  trigger: "alert"
  target: "dingding,ticket,email,mbox,webhook,dingtalk_work_notice"
  title: |
    【{{cluster_name}}集群kubernetes组件{{resource_name_value}} Ready状态告警】
  template: |
    【kubernetes组件Ready状态告警】

    组件: {{resource_name_value}}

    不可用实例: {{not_ready_value}}

    期望实例: {{total_value}}

    集群: {{cluster_name}}

    组织名称: {{org_name}}

    告警级别: {{level}}

    时间: {{timestamp}}

    [查看记录]({{record_url}})

- name: "kubernetes组件实例Ready状态异常"
  trigger: "alert"
  target: "sms"
  title: |
    【{{cluster_name}}集群kubernetes组件{{resource_name_value}} Ready状态告警】
  template: |
    {{cluster_name}}集群{{resource_name_value}}组件触发kubernetes组件实例Ready状态异常，组织名称: {{org_name}}，不可用实例: {{not_ready_value}}，告警级别: {{level}}
- name: "kubernetes组件实例Ready状态异常"
  trigger: "alert"
  target: "vms"
  title: |
    【{{cluster_name}}集群kubernetes组件{{resource_name_value}} Ready状态告警】
  template: |
    {{cluster_name}}集群{{resource_name_value}}组件触发kubernetes组件实例Ready状态异常，组织名称: {{org_name}}，不可用实例: {{not_ready_value}}，告警级别: {{level}}
- name: "kubernetes组件实例Ready状态异常"
  trigger: "recover"
  target: "dingding,ticket,email,mbox,webhook,dingtalk_work_notice"
  formats:
    trigger_duration: "time:ms"
  title: |
    【{{cluster_name}}集群kubernetes组件{{resource_name_value}} Ready状态恢复】
  template: |
    【kubernetes组件Ready状态恢复】

    组件: {{resource_name_value}}

    可用实例: {{ready_value}}

    期望实例: {{total_value}}

    集群: {{cluster_name}}

    组织名称: {{org_name}}

    持续时间: {{trigger_duration}}

    恢复时间: {{timestamp}}

    [查看记录]({{record_url}})

- name: "kubernetes组件实例Ready状态异常"
  trigger: "recover"
  target: "sms"
  formats:
    trigger_duration: "time:ms"
  title: |
    【{{cluster_name}}集群kubernetes组件{{resource_name_value}} Ready状态恢复】
  template: |
    {{cluster_name}}集群{{resource_name_value}}组件触发kubernetes组件实例Ready状态异常恢复，组织名称: {{org_name}}，可用实例: {{ready_value}}
- name: "kubernetes组件实例Ready状态异常"
  trigger: "recover"
  target: "vms"
  formats:
    trigger_duration: "time:ms"
  title: |
    【{{cluster_name}}集群kubernetes组件{{resource_name_value}} Ready状态恢复】
  template: |
    {{cluster_name}}集群{{resource_name_value}}组件触发kubernetes组件实例Ready状态异常恢复，组织名称: {{org_name}}，可用实例: {{ready_value}}
