- scope: "app"
  name: "应用 > 外部代码仓库 > 编辑"
  resource: "UI.externalRepo"
  action: "edit"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > 代码仓库 > 查看"
  resource: "UI.repo"
  action: "read"
  role: "Owner,Lead,Dev,QA,Support,Ops,Guest"
- scope: "app"
  name: "应用 > 代码仓库 > 分支管理 > 普通分支管理（创建分支/提交文件/修改文件/删除）"
  resource: "UI.repo.branch"
  action: "writeNormal"
  role: "Owner,Lead,Dev,QA"
- scope: "app"
  name: "应用 > 代码仓库 > 分支管理 > 保护分支管理（创建分支/提交文件/修改文件/删除）"
  resource: "UI.repo.branch"
  action: "writeProtected"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > 代码仓库 > 分支管理 > 设置默认分支"
  resource: "UI.repo.branch"
  action: "setDefaultBranch"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > 代码仓库 > 分支管理 > 添加标签"
  resource: "UI.repo.branch"
  action: "addTag"
  role: "Owner,Lead,Dev,QA,Support,Ops"
- scope: "app"
  name: "应用 > 代码仓库 > 分支管理 > 删除标签"
  resource: "UI.repo.branch"
  action: "deleteTag"
  role: "Lead,Owner,Dev,QA,Support,Ops"
- scope: "app"
  name: "应用 > 代码仓库 > 合并请求 > 新建"
  resource: "UI.repo.mr"
  action: "create"
  role: "Owner,Lead,Dev,QA"
- scope: "app"
  name: "应用 > 代码仓库 > 合并请求 > 编辑"
  resource: "UI.repo.mr"
  action: "edit"
  role: "Owner,Lead"
  resource_role: "Creator"
- scope: "app"
  name: "应用 > 代码仓库 > 合并请求 > 关闭"
  resource: "UI.repo.mr"
  action: "close"
  role: "Owner,Lead"
  resource_role: "Creator"
- scope: "app"
  name: "应用 > 代码仓库 > 备份管理 > 新建备份"
  resource: "UI.repo.backup"
  action: "backupRepo"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > 代码仓库 > 备份管理 > 删除备份"
  resource: "UI.repo.backup"
  action: "deleteBackup"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > 流水线 > 查看"
  resource: "UI.pipeline"
  action: "read"
  role: "Owner,Lead,Dev,QA,Support,Ops,Guest"
- scope: "app"
  name: "应用 > 流水线 > 操作普通分支(开始/取消定时/立即执行/重试/停止)"
  resource: "UI.pipeline"
  action: "executeNormal"
  role: "Owner,Lead,Dev,QA"
- scope: "app"
  name: "应用 > 流水线 > 操作受保护分支(开始/取消定时/立即执行/重试/停止)"
  resource: "UI.pipeline"
  action: "executeProtected"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > 部署中心 > 查看"
  resource: "UI.runtime"
  action: "read"
  role: "Owner,Lead,Dev,QA,Support,Ops"
- scope: "app"
  name: "应用 > 部署中心 > DEV操作（重启/回滚/域名设置/服务扩容）"
  resource: "UI.runtime"
  action: "devDeployOperation"
  role: "Owner,Lead,Dev"
- scope: "app"
  name: "应用 > 部署中心 > DEV删除"
  resource: "UI.runtime"
  action: "devDelete"
  role: "Owner,Lead,Dev"
- scope: "app"
  name: "应用 > 部署中心 > TEST操作（重启/回滚/域名设置/服务扩容）"
  resource: "UI.runtime"
  action: "testDeployOperation"
  role: "Owner,Lead,QA"
- scope: "app"
  name: "应用 > 部署中心 > TEST删除"
  resource: "UI.runtime"
  action: "testDelete"
  role: "Owner,Lead,QA"
- scope: "app"
  name: "应用 > 部署中心 > STAGING操作（重启/回滚/域名设置/服务扩容）"
  resource: "UI.runtime"
  action: "stagingDeployOperation"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > 部署中心 > STAGING删除"
  resource: "UI.runtime"
  action: "stagingDelete"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > 部署中心 > PROD操作（重启/回滚/域名设置/服务扩容）"
  resource: "UI.runtime"
  action: "prodDeployOperation"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > 部署中心 > PROD删除"
  resource: "UI.runtime"
  action: "prodDelete"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > 部署中心 > DEV-详情-控制台"
  resource: "UI.runtime"
  action: "devConsole"
  role: "Owner,Lead,Dev,Ops,Support"
- scope: "app"
  name: "应用 > 部署中心 > TEST-详情-控制台"
  resource: "UI.runtime"
  action: "testConsole"
  role: "Owner,Lead,QA,Ops,Support"
- scope: "app"
  name: "应用 > 部署中心 > STAGING-详情-控制台"
  resource: "UI.runtime"
  action: "stagingConsole"
  role: "Owner,Lead,Support"
- scope: "app"
  name: "应用 > 部署中心 > PROD-详情-控制台"
  resource: "UI.runtime"
  action: "prodConsole"
  role: "Owner,Lead,Support"
- scope: "app"
  name: "应用 > 应用设置 > 编辑应用信息"
  resource: "UI.setting"
  action: "editApp"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > 应用设置 > 删除应用信息"
  resource: "UI.setting"
  action: "deleteApp"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > 应用设置 > 分支规则 > 操作（增删改）"
  resource: "UI.setting.branchRule"
  action: "operation"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > 应用设置 > 仓库设置 > 锁定仓库"
  resource: "UI.setting.repoSetting"
  action: "lockRepo"
  role: "Lead,Owner"
- scope: "app"
  name: "应用 > 应用设置 > 查看"
  resource: "UI.setting"
  action: "read"
  role: "Owner,Lead,Dev,QA,Support,Ops"
- scope: "app"
  name: "应用 > 成员管理 > 应用成员 > 添加成员"
  resource: "UI.member"
  action: "addAppMember"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > 成员管理 > 应用成员 > 编辑成员"
  resource: "UI.member"
  action: "editAppMember"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > 成员管理 > 应用成员 > 移除成员"
  resource: "UI.member"
  action: "deleteAppMember"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > API 管理 > API 集市 > 查看"
  resource: "UI.apiManage.apiMarket"
  action: "read"
  role: "Owner,Lead,Dev,QA,Ops"
- scope: "app"
  name: "应用 > API 管理 > API 集市 > 编辑资源"
  resource: "UI.apiManage.apiMarket"
  action: "edit"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > API 管理 > API 集市 > 删除资源"
  resource: "UI.apiManage.apiMarket"
  action: "delete"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > API 管理 > API 集市 > 公开"
  resource: "UI.apiManage.apiMarket"
  action: "publicAsset"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > API 管理 > API 集市 > 添加版本"
  resource: "UI.apiManage.apiMarket"
  action: "addVersion"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > API 管理 > API 集市 > 删除版本"
  resource: "UI.apiManage.apiMarket"
  action: "deleteVersion"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > API 管理 > API 集市 > 关联项目/应用"
  resource: "UI.apiManage.apiMarket"
  action: "relatedProjectOrApp"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > API 管理 > API 集市 > 关联实例"
  resource: "UI.apiManage.apiMarket"
  action: "relatedInstance"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > API 管理 > 访问管理 > 编辑"
  resource: "UI.apiManage.accessManage"
  action: "edit"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > API 管理 > 访问管理 > 删除"
  resource: "UI.apiManage.accessManage"
  action: "delete"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > API 管理 > 访问管理 > 审批"
  resource: "UI.apiManage.accessManage"
  action: "approve"
  role: "Owner,Lead"
- scope: "app"
  name: "应用 > API设计 > 查看"
  resource: "UI.apiDesign"
  action: "read"
  role: "Owner,Lead,Dev,QA,Support,Ops"
- scope: "app"
  name: "应用 > 数据任务 > 查看"
  resource: "UI.dataTask"
  action: "read"
  role: "Owner,Lead,Dev,QA,Support,Ops"
- scope: "app"
  name: "应用 > 数据模型 > 查看"
  resource: "UI.dataModel"
  action: "read"
  role: "Owner,Lead,Dev,QA,Support,Ops"
- scope: "app"
  name: "应用 > 数据集市 > 查看"
  resource: "UI.dataMarket"
  action: "read"
  role: "Owner,Lead,Dev,QA,Support,Ops"
- scope: "app"
  name: "应用 > 代码质量 > 查看"
  resource: "UI.codeQuality"
  action: "read"
  role: "Owner,Lead,Dev,QA,Support,Ops"
- scope: "app"
  name: "应用 > 制品管理 > 查看"
  resource: "UI.release"
  action: "read"
  role: "Owner,Lead,Dev,QA,Support,Ops,Guest"
- scope: "app"
  name: "应用 > 制品管理 > 详情信息 > 编辑"
  resource: "UI.release.info"
  action: "edit"
  role: "Owner,Lead,Dev,QA,Support,Ops"