# Copyright (c) 2021 Terminus, Inc.
#
# This program is free software: you can use, redistribute, and/or modify
# it under the terms of the GNU Affero General Public License, version 3
# or later ("AGPL"), as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

name: codecov
on:
  push:
    tags:
      - v*
    branches:
      - develop
      - master
      - release/*
    paths:
      - '**'
      - '!**.go'
      - '!**/go.mod'
      - '!**/go.sum'
      - '!**/*.proto'
  pull_request:
    paths:
      - '**'
      - '!**.go'
      - '!**/go.mod'
      - '!**/go.sum'
      - '!**/*.proto'

jobs:
  CHECK-CHANGED-FILES:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v21
      - name: List all changed files
        id: check
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ext="${file##*.}"
            echo "file: $file, ext: $ext"
            echo "::set-output name=have-${ext}::true"
            base_filename=$(basename "${file}")
            if [[ "${base_filename}" == "go.mod" || "${base_filename}" == "go.sum" ]]; then
              echo "::set-output name=have-go::true"
            fi
            if [[ "$ext" == "proto" ]]; then
              echo "::set-output name=have-go::true"
            fi
          done
    outputs:
      have-go: ${{ steps.check.outputs.have-go }}
  patch:
    runs-on: ubuntu-latest
    needs: CHECK-CHANGED-FILES
    if: needs.CHECK-CHANGED-FILES.outputs.have-go != 'true'
    steps:
      - run: echo "No codecov/patch required"
  project:
    runs-on: ubuntu-latest
    needs: CHECK-CHANGED-FILES
    if: needs.CHECK-CHANGED-FILES.outputs.have-go != 'true'
    steps:
      - run: echo "No codecov/project required"
