name: golangci-build
on:
  push:
    tags:
      - v*
    branches:
      - develop
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: Build
      run: make
