name: GIT SYNC

on: [ push, delete ]

jobs:
  build:
    if: github.repository == 'littlejiancc/erda'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: unshallow
        run: | 
          git fetch --unshallow origin
          git fetch origin 'refs/pull/*/head:refs/remotes/origin/pr/*'
      - name: add remote
        run: git remote add mirror https://${{ secrets.ERDA_CLOUD_MIRROR_GIT_USERNAME }}:${{ secrets.ERDA_CLOUD_MIRROR_GIT_PASSWORD }}@erda.daily.terminus.io/erda/dop/wxjcc/erda
      - name: push
        run: git push --tags --force --prune mirror "refs/remotes/origin/pr/*:refs/heads/*"
